<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BinhDinhHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'FLC Luxury Hotel Quy Nhơn',
                'description' => 'Khách sạn 5 sao cao cấp với view biển tuyệt đẹp tại Quy Nhơn',
                'address' => 'Đường Trần Hưng Đạo, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/flc_luxury_1.jpg', 'hotels/flc_luxury_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2333,
                'email' => 'reservations@flcquynhon.com',
                'phone' => '0256 3848 888',
                'website' => 'https://www.flchotels.com/quynhon',
            ],
            [
                'name' => 'Avani Quy Nhơn Resort',
                'description' => 'Resort cao cấp với bãi biển riêng và spa services',
                'address' => 'Bãi biển Kỳ Co, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/avani_1.jpg', 'hotels/avani_2.jpg']),
                'latitude' => 13.7833,
                'longitude' => 109.2833,
                'email' => 'info@avani-quynhon.com',
                'phone' => '0256 3849 999',
                'website' => 'https://www.avanihotels.com/quynhon',
            ],
            [
                'name' => 'Seaside Hotel Quy Nhơn',
                'description' => 'Khách sạn 4 sao với view biển và nhà hàng hải sản',
                'address' => 'Đường Nguyễn Huệ, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/seaside_1.jpg', 'hotels/seaside_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'email' => 'booking@seaside-quynhon.com',
                'phone' => '0256 3847 777',
                'website' => 'https://www.seasidehotel.com',
            ],
            [
                'name' => 'Hoàng Yến Hotel',
                'description' => 'Khách sạn 3 sao với giá cả phải chăng tại trung tâm Quy Nhơn',
                'address' => 'Đường Lê Lợi, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/hoang_yen_1.jpg', 'hotels/hoang_yen_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'email' => 'info@hoangyenhotel.com',
                'phone' => '0256 3846 666',
                'website' => 'https://www.hoangyenhotel.com',
            ],
            [
                'name' => 'Bình Định Beach Resort',
                'description' => 'Resort ven biển với bungalow và nhà hàng hải sản',
                'address' => 'Bãi biển Hải Giang, Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'images' => json_encode(['hotels/binh_dinh_beach_1.jpg', 'hotels/binh_dinh_beach_2.jpg']),
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'email' => 'reservations@binhdinhbeach.com',
                'phone' => '0256 3845 555',
                'website' => 'https://www.binhdinhbeachresort.com',
            ],
            [
                'name' => 'Quy Nhơn Central Hotel',
                'description' => 'Khách sạn trung tâm với tiện nghi hiện đại',
                'address' => 'Đường Trần Phú, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/quy_nhon_central_1.jpg', 'hotels/quy_nhon_central_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'email' => 'info@quynhoncentral.com',
                'phone' => '0256 3844 444',
                'website' => 'https://www.quynhoncentral.com',
            ],
            [
                'name' => 'Kỳ Co Beach Hotel',
                'description' => 'Khách sạn ven biển với view biển xanh cát trắng',
                'address' => 'Bãi biển Kỳ Co, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/ky_co_beach_1.jpg', 'hotels/ky_co_beach_2.jpg']),
                'latitude' => 13.7833,
                'longitude' => 109.2833,
                'email' => 'booking@kycobeach.com',
                'phone' => '0256 3843 333',
                'website' => 'https://www.kycobeachhotel.com',
            ],
            [
                'name' => 'Tây Sơn Hotel',
                'description' => 'Khách sạn gần di tích lịch sử Tây Sơn',
                'address' => 'Huyện Tây Sơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/tay_son_1.jpg', 'hotels/tay_son_2.jpg']),
                'latitude' => 14.0667,
                'longitude' => 108.8833,
                'email' => 'info@taysonhotel.com',
                'phone' => '0256 3842 222',
                'website' => 'https://www.taysonhotel.com',
            ],
            [
                'name' => 'Phù Cát Resort',
                'description' => 'Resort ven biển với không gian yên tĩnh',
                'address' => 'Huyện Phù Cát, Tỉnh Bình Định',
                'images' => json_encode(['hotels/phu_cat_1.jpg', 'hotels/phu_cat_2.jpg']),
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'email' => 'reservations@phucatresort.com',
                'phone' => '0256 3841 111',
                'website' => 'https://www.phucatresort.com',
            ],
            [
                'name' => 'An Nhơn Hotel',
                'description' => 'Khách sạn tại thị xã An Nhơn với giá cả hợp lý',
                'address' => 'Thị xã An Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/an_nhon_1.jpg', 'hotels/an_nhon_2.jpg']),
                'latitude' => 13.8833,
                'longitude' => 109.1167,
                'email' => 'booking@annhonhotel.com',
                'phone' => '0256 3840 000',
                'website' => 'https://www.annhonhotel.com',
            ],
            [
                'name' => 'Tuy Phước Beach Hotel',
                'description' => 'Khách sạn ven biển tại huyện Tuy Phước',
                'address' => 'Huyện Tuy Phước, Tỉnh Bình Định',
                'images' => json_encode(['hotels/tuy_phuoc_1.jpg', 'hotels/tuy_phuoc_2.jpg']),
                'latitude' => 13.9333,
                'longitude' => 109.1000,
                'email' => 'info@tuyphuocbeach.com',
                'phone' => '0256 3839 999',
                'website' => 'https://www.tuyphuocbeach.com',
            ],
            [
                'name' => 'Quy Nhơn Plaza Hotel',
                'description' => 'Khách sạn cao cấp tại trung tâm thương mại',
                'address' => 'Đường Nguyễn Tất Thành, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/quy_nhon_plaza_1.jpg', 'hotels/quy_nhon_plaza_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'email' => 'reservations@quynhonplaza.com',
                'phone' => '0256 3838 888',
                'website' => 'https://www.quynhonplaza.com',
            ],
            [
                'name' => 'Hải Giang Resort',
                'description' => 'Resort ven biển với bungalow và nhà hàng',
                'address' => 'Bãi biển Hải Giang, Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'images' => json_encode(['hotels/hai_giang_1.jpg', 'hotels/hai_giang_2.jpg']),
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'email' => 'booking@haigiangresort.com',
                'phone' => '0256 3837 777',
                'website' => 'https://www.haigiangresort.com',
            ],
            [
                'name' => 'Eo Gió Hotel',
                'description' => 'Khách sạn với view biển Eo Gió tuyệt đẹp',
                'address' => 'Bãi biển Eo Gió, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/eo_gio_1.jpg', 'hotels/eo_gio_2.jpg']),
                'latitude' => 13.8000,
                'longitude' => 109.2667,
                'email' => 'info@eogiohotel.com',
                'phone' => '0256 3836 666',
                'website' => 'https://www.eogiohotel.com',
            ],
            [
                'name' => 'Bình Định Heritage Hotel',
                'description' => 'Khách sạn với kiến trúc truyền thống Bình Định',
                'address' => 'Đường Lý Thường Kiệt, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/binh_dinh_heritage_1.jpg', 'hotels/binh_dinh_heritage_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'email' => 'reservations@binhdinhheritage.com',
                'phone' => '0256 3835 555',
                'website' => 'https://www.binhdinhheritage.com',
            ],
            [
                'name' => 'Quy Nhơn Bay Hotel',
                'description' => 'Khách sạn với view vịnh Quy Nhơn',
                'address' => 'Đường Trần Hưng Đạo, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/quy_nhon_bay_1.jpg', 'hotels/quy_nhon_bay_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2333,
                'email' => 'booking@quynhonbay.com',
                'phone' => '0256 3834 444',
                'website' => 'https://www.quynhonbay.com',
            ],
            [
                'name' => 'Chăm Pa Hotel',
                'description' => 'Khách sạn với chủ đề văn hóa Chăm Pa',
                'address' => 'Đường Nguyễn Huệ, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/cham_pa_1.jpg', 'hotels/cham_pa_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'email' => 'info@champahotel.com',
                'phone' => '0256 3833 333',
                'website' => 'https://www.champahotel.com',
            ],
            [
                'name' => 'Tây Sơn Heritage Hotel',
                'description' => 'Khách sạn gần di tích lịch sử Tây Sơn',
                'address' => 'Huyện Tây Sơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/tay_son_heritage_1.jpg', 'hotels/tay_son_heritage_2.jpg']),
                'latitude' => 14.0667,
                'longitude' => 108.8833,
                'email' => 'reservations@taysonheritage.com',
                'phone' => '0256 3832 222',
                'website' => 'https://www.taysonheritage.com',
            ],
            [
                'name' => 'Phù Cát Beach Resort',
                'description' => 'Resort ven biển tại huyện Phù Cát',
                'address' => 'Huyện Phù Cát, Tỉnh Bình Định',
                'images' => json_encode(['hotels/phu_cat_beach_1.jpg', 'hotels/phu_cat_beach_2.jpg']),
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'email' => 'booking@phucatbeach.com',
                'phone' => '0256 3831 111',
                'website' => 'https://www.phucatbeach.com',
            ],
            [
                'name' => 'An Nhơn Heritage Hotel',
                'description' => 'Khách sạn với kiến trúc truyền thống tại An Nhơn',
                'address' => 'Thị xã An Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/an_nhon_heritage_1.jpg', 'hotels/an_nhon_heritage_2.jpg']),
                'latitude' => 13.8833,
                'longitude' => 109.1167,
                'email' => 'info@annhonheritage.com',
                'phone' => '0256 3830 000',
                'website' => 'https://www.annhonheritage.com',
            ],
            [
                'name' => 'Tuy Phước Heritage Hotel',
                'description' => 'Khách sạn với kiến trúc truyền thống tại Tuy Phước',
                'address' => 'Huyện Tuy Phước, Tỉnh Bình Định',
                'images' => json_encode(['hotels/tuy_phuoc_heritage_1.jpg', 'hotels/tuy_phuoc_heritage_2.jpg']),
                'latitude' => 13.9333,
                'longitude' => 109.1000,
                'email' => 'reservations@tuyphuocheritage.com',
                'phone' => '0256 3829 999',
                'website' => 'https://www.tuyphuocheritage.com',
            ],
            [
                'name' => 'Quy Nhơn Marina Hotel',
                'description' => 'Khách sạn ven cảng với view biển',
                'address' => 'Cảng Quy Nhơn, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/quy_nhon_marina_1.jpg', 'hotels/quy_nhon_marina_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2333,
                'email' => 'booking@quynhonmarina.com',
                'phone' => '0256 3828 888',
                'website' => 'https://www.quynhonmarina.com',
            ],
            [
                'name' => 'Bình Định Mountain Hotel',
                'description' => 'Khách sạn trên núi với view toàn cảnh',
                'address' => 'Núi Vũng Chua, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/binh_dinh_mountain_1.jpg', 'hotels/binh_dinh_mountain_2.jpg']),
                'latitude' => 13.8167,
                'longitude' => 109.2500,
                'email' => 'info@binhdinhmountain.com',
                'phone' => '0256 3827 777',
                'website' => 'https://www.binhdinhmountain.com',
            ],
            [
                'name' => 'Quy Nhơn Garden Hotel',
                'description' => 'Khách sạn với khu vườn xanh mát',
                'address' => 'Đường Lê Lợi, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/quy_nhon_garden_1.jpg', 'hotels/quy_nhon_garden_2.jpg']),
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'email' => 'reservations@quynhongarden.com',
                'phone' => '0256 3826 666',
                'website' => 'https://www.quynhongarden.com',
            ],
            [
                'name' => 'Chăm Pa Heritage Resort',
                'description' => 'Resort với chủ đề văn hóa Chăm Pa',
                'address' => 'Gần tháp Chăm, Huyện Tuy Phước, Tỉnh Bình Định',
                'images' => json_encode(['hotels/cham_pa_heritage_1.jpg', 'hotels/cham_pa_heritage_2.jpg']),
                'latitude' => 13.9167,
                'longitude' => 109.1167,
                'email' => 'booking@champaheritage.com',
                'phone' => '0256 3825 555',
                'website' => 'https://www.champaheritage.com',
            ],
            [
                'name' => 'Tây Sơn Mountain Hotel',
                'description' => 'Khách sạn trên núi tại Tây Sơn',
                'address' => 'Huyện Tây Sơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/tay_son_mountain_1.jpg', 'hotels/tay_son_mountain_2.jpg']),
                'latitude' => 14.0667,
                'longitude' => 108.8833,
                'email' => 'info@taysonmountain.com',
                'phone' => '0256 3824 444',
                'website' => 'https://www.taysonmountain.com',
            ],
            [
                'name' => 'Phù Cát Mountain Resort',
                'description' => 'Resort trên núi tại Phù Cát',
                'address' => 'Huyện Phù Cát, Tỉnh Bình Định',
                'images' => json_encode(['hotels/phu_cat_mountain_1.jpg', 'hotels/phu_cat_mountain_2.jpg']),
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'email' => 'reservations@phucatmountain.com',
                'phone' => '0256 3823 333',
                'website' => 'https://www.phucatmountain.com',
            ],
            [
                'name' => 'An Nhơn Mountain Hotel',
                'description' => 'Khách sạn trên núi tại An Nhơn',
                'address' => 'Thị xã An Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/an_nhon_mountain_1.jpg', 'hotels/an_nhon_mountain_2.jpg']),
                'latitude' => 13.8833,
                'longitude' => 109.1167,
                'email' => 'booking@annhonmountain.com',
                'phone' => '0256 3822 222',
                'website' => 'https://www.annhonmountain.com',
            ],
            [
                'name' => 'Tuy Phước Mountain Resort',
                'description' => 'Resort trên núi tại Tuy Phước',
                'address' => 'Huyện Tuy Phước, Tỉnh Bình Định',
                'images' => json_encode(['hotels/tuy_phuoc_mountain_1.jpg', 'hotels/tuy_phuoc_mountain_2.jpg']),
                'latitude' => 13.9333,
                'longitude' => 109.1000,
                'email' => 'info@tuyphuocmountain.com',
                'phone' => '0256 3821 111',
                'website' => 'https://www.tuyphuocmountain.com',
            ],
            [
                'name' => 'Quy Nhơn Mountain Hotel',
                'description' => 'Khách sạn trên núi tại Quy Nhơn',
                'address' => 'Núi Bà, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'images' => json_encode(['hotels/quy_nhon_mountain_1.jpg', 'hotels/quy_nhon_mountain_2.jpg']),
                'latitude' => 13.8333,
                'longitude' => 109.2333,
                'email' => 'reservations@quynhonmountain.com',
                'phone' => '0256 3820 000',
                'website' => 'https://www.quynhonmountain.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
