<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BinhDinhCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        $binhDinhLocationId = DB::table('locations')->where('name', 'Bình Định')->value('id');
        
        if (!$binhDinhLocationId) {
            $binhDinhLocationId = DB::table('locations')->insertGetId([
                'name' => 'Bình Định',
                'description' => 'Tỉnh Bình Định - vùng đất văn hóa Chăm Pa với nhiều di tích lịch sử',
                'latitude' => 14.1667,
                'longitude' => 108.9027,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Tháp Bánh Ít',
                'description' => 'Quần thể tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử quan trọng',
                'address' => 'Xã Phước Hiệp, Huyện Tuy Phước, Tỉnh Bình Định',
                'latitude' => 13.9167,
                'longitude' => 109.1167,
                'image' => 'checkin/thap_banh_it.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_banh_it_1.jpg', 'checkin/thap_banh_it_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Kỳ Co',
                'description' => 'Bãi biển đẹp với cát trắng, nước trong xanh, được mệnh danh là Maldives của Việt Nam',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7833,
                'longitude' => 109.2833,
                'image' => 'checkin/bai_bien_ky_co.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_ky_co_1.jpg', 'checkin/bai_bien_ky_co_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Thiên đường biển xanh cát trắng',
                'transport_options' => json_encode(['car', 'motorbike', 'boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Khô',
                'description' => 'Đảo nhỏ với bãi biển hoang sơ, lý tưởng cho du lịch và lặn biển',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.3000,
                'image' => 'checkin/hon_kho.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/hon_kho_1.jpg', 'checkin/hon_kho_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Đảo hoang sơ với biển xanh',
                'transport_options' => json_encode(['boat', 'canoe']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Quang Trung',
                'description' => 'Bảo tàng trưng bày hiện vật về vua Quang Trung và phong trào Tây Sơn',
                'address' => 'Xã Bình Thành, Huyện Tây Sơn, Tỉnh Bình Định',
                'latitude' => 14.0667,
                'longitude' => 108.8833,
                'image' => 'checkin/bao_tang_quang_trung.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_quang_trung_1.jpg', 'checkin/bao_tang_quang_trung_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích lịch sử vua Quang Trung',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Eo Gió',
                'description' => 'Bãi biển đẹp với vách đá và view biển tuyệt đẹp, lý tưởng để ngắm hoàng hôn',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8000,
                'longitude' => 109.2667,
                'image' => 'checkin/bai_bien_eo_gio.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_eo_gio_1.jpg', 'checkin/bai_bien_eo_gio_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Điểm ngắm hoàng hôn tuyệt đẹp',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Bình Lâm',
                'description' => 'Tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử quan trọng',
                'address' => 'Xã Phước Hòa, Huyện Tuy Phước, Tỉnh Bình Định',
                'latitude' => 13.9333,
                'longitude' => 109.1000,
                'image' => 'checkin/thap_binh_lam.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_binh_lam_1.jpg', 'checkin/thap_binh_lam_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Hải Giang',
                'description' => 'Bãi biển dài với cát trắng mịn, nước trong xanh, ít người',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'image' => 'checkin/bai_bien_hai_giang.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_hai_giang_1.jpg', 'checkin/bai_bien_hai_giang_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Vũng Chua',
                'description' => 'Núi đá với view toàn cảnh thành phố Quy Nhơn và biển',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8167,
                'longitude' => 109.2500,
                'image' => 'checkin/nui_vung_chua.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/nui_vung_chua_1.jpg', 'checkin/nui_vung_chua_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Điểm ngắm toàn cảnh Quy Nhơn',
                'transport_options' => json_encode(['car', 'motorbike', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Trung Lương',
                'description' => 'Bãi biển đẹp với cát trắng, nước trong, ít người và yên tĩnh',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0333,
                'longitude' => 109.0333,
                'image' => 'checkin/bai_bien_trung_luong.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_trung_luong_1.jpg', 'checkin/bai_bien_trung_luong_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Phú Lốc',
                'description' => 'Tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử',
                'address' => 'Xã Nhơn Thành, Huyện An Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8833,
                'longitude' => 109.1167,
                'image' => 'checkin/thap_phu_loc.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_phu_loc_1.jpg', 'checkin/thap_phu_loc_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Bãi Dài',
                'description' => 'Bãi biển dài với cát trắng mịn, nước trong xanh, lý tưởng cho du lịch',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0500,
                'longitude' => 109.0500,
                'image' => 'checkin/bai_bien_bai_dai.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_bai_dai_1.jpg', 'checkin/bai_bien_bai_dai_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển dài với cát trắng mịn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Bà',
                'description' => 'Núi cao với view toàn cảnh thành phố Quy Nhơn và vịnh biển',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8333,
                'longitude' => 109.2333,
                'image' => 'checkin/nui_ba.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/nui_ba_1.jpg', 'checkin/nui_ba_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Điểm ngắm toàn cảnh Quy Nhơn',
                'transport_options' => json_encode(['car', 'motorbike', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Hòn Khô Nhỏ',
                'description' => 'Bãi biển nhỏ hoang sơ với nước trong xanh, lý tưởng cho lặn biển',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7500,
                'longitude' => 109.3167,
                'image' => 'checkin/bai_bien_hon_kho_nho.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bai_bien_hon_kho_nho_1.jpg', 'checkin/bai_bien_hon_kho_nho_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ với nước trong',
                'transport_options' => json_encode(['boat', 'canoe']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Cánh Tiên',
                'description' => 'Tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử quan trọng',
                'address' => 'Xã Nhơn Thành, Huyện An Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8667,
                'longitude' => 109.1333,
                'image' => 'checkin/thap_canh_tien.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_canh_tien_1.jpg', 'checkin/thap_canh_tien_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Hải Minh',
                'description' => 'Bãi biển đẹp với cát trắng, nước trong xanh, ít người',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0667,
                'longitude' => 109.0167,
                'image' => 'checkin/bai_bien_hai_minh.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_hai_minh_1.jpg', 'checkin/bai_bien_hai_minh_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Vũng Chua Nhỏ',
                'description' => 'Núi đá nhỏ với view biển tuyệt đẹp, lý tưởng để ngắm hoàng hôn',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8167,
                'longitude' => 109.2667,
                'image' => 'checkin/nui_vung_chua_nho.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/nui_vung_chua_nho_1.jpg', 'checkin/nui_vung_chua_nho_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Điểm ngắm hoàng hôn tuyệt đẹp',
                'transport_options' => json_encode(['car', 'motorbike', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Cát Tiến',
                'description' => 'Bãi biển dài với cát trắng mịn, nước trong xanh, ít người',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0833,
                'longitude' => 109.0333,
                'image' => 'checkin/bai_bien_cat_tien.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_cat_tien_1.jpg', 'checkin/bai_bien_cat_tien_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Bình Nghi',
                'description' => 'Tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử',
                'address' => 'Xã Phước Hiệp, Huyện Tuy Phước, Tỉnh Bình Định',
                'latitude' => 13.9000,
                'longitude' => 109.1167,
                'image' => 'checkin/thap_binh_nghi.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_binh_nghi_1.jpg', 'checkin/thap_binh_nghi_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Hải Giang 2',
                'description' => 'Bãi biển đẹp với cát trắng, nước trong xanh, ít người',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0333,
                'longitude' => 109.0167,
                'image' => 'checkin/bai_bien_hai_giang_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_hai_giang_2_1.jpg', 'checkin/bai_bien_hai_giang_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Vũng Chua 2',
                'description' => 'Núi đá với view toàn cảnh thành phố Quy Nhơn và biển',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8167,
                'longitude' => 109.2500,
                'image' => 'checkin/nui_vung_chua_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/nui_vung_chua_2_1.jpg', 'checkin/nui_vung_chua_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Điểm ngắm toàn cảnh Quy Nhơn',
                'transport_options' => json_encode(['car', 'motorbike', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Trung Lương 2',
                'description' => 'Bãi biển đẹp với cát trắng, nước trong, ít người và yên tĩnh',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0500,
                'longitude' => 109.0500,
                'image' => 'checkin/bai_bien_trung_luong_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_trung_luong_2_1.jpg', 'checkin/bai_bien_trung_luong_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Phú Lốc 2',
                'description' => 'Tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử',
                'address' => 'Xã Nhơn Thành, Huyện An Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8833,
                'longitude' => 109.1167,
                'image' => 'checkin/thap_phu_loc_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_phu_loc_2_1.jpg', 'checkin/thap_phu_loc_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Bãi Dài 2',
                'description' => 'Bãi biển dài với cát trắng mịn, nước trong xanh, lý tưởng cho du lịch',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0667,
                'longitude' => 109.0667,
                'image' => 'checkin/bai_bien_bai_dai_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_bai_dai_2_1.jpg', 'checkin/bai_bien_bai_dai_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển dài với cát trắng mịn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Bà 2',
                'description' => 'Núi cao với view toàn cảnh thành phố Quy Nhơn và vịnh biển',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8333,
                'longitude' => 109.2333,
                'image' => 'checkin/nui_ba_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/nui_ba_2_1.jpg', 'checkin/nui_ba_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Điểm ngắm toàn cảnh Quy Nhơn',
                'transport_options' => json_encode(['car', 'motorbike', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Hòn Khô Nhỏ 2',
                'description' => 'Bãi biển nhỏ hoang sơ với nước trong xanh, lý tưởng cho lặn biển',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7500,
                'longitude' => 109.3167,
                'image' => 'checkin/bai_bien_hon_kho_nho_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bai_bien_hon_kho_nho_2_1.jpg', 'checkin/bai_bien_hon_kho_nho_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ với nước trong',
                'transport_options' => json_encode(['boat', 'canoe']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Cánh Tiên 2',
                'description' => 'Tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử quan trọng',
                'address' => 'Xã Nhơn Thành, Huyện An Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8667,
                'longitude' => 109.1333,
                'image' => 'checkin/thap_canh_tien_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_canh_tien_2_1.jpg', 'checkin/thap_canh_tien_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Hải Minh 2',
                'description' => 'Bãi biển đẹp với cát trắng, nước trong xanh, ít người',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0833,
                'longitude' => 109.0333,
                'image' => 'checkin/bai_bien_hai_minh_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_hai_minh_2_1.jpg', 'checkin/bai_bien_hai_minh_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Vũng Chua Nhỏ 2',
                'description' => 'Núi đá nhỏ với view biển tuyệt đẹp, lý tưởng để ngắm hoàng hôn',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8167,
                'longitude' => 109.2667,
                'image' => 'checkin/nui_vung_chua_nho_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/nui_vung_chua_nho_2_1.jpg', 'checkin/nui_vung_chua_nho_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Điểm ngắm hoàng hôn tuyệt đẹp',
                'transport_options' => json_encode(['car', 'motorbike', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Cát Tiến 2',
                'description' => 'Bãi biển dài với cát trắng mịn, nước trong xanh, ít người',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.1000,
                'longitude' => 109.0500,
                'image' => 'checkin/bai_bien_cat_tien_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_cat_tien_2_1.jpg', 'checkin/bai_bien_cat_tien_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Bình Nghi 2',
                'description' => 'Tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử',
                'address' => 'Xã Phước Hiệp, Huyện Tuy Phước, Tỉnh Bình Định',
                'latitude' => 13.9167,
                'longitude' => 109.1167,
                'image' => 'checkin/thap_binh_nghi_2.jpg',
                'location_id' => $binhDinhLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_binh_nghi_2_1.jpg', 'checkin/thap_binh_nghi_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
