<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BinhDinhRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Hải Sản Quy Nhơn',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi ngon tại Quy Nhơn',
                'address' => 'Đường Trần Hưng Đạo, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2333,
                'rating' => 4.5,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/hai_san_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Chăm Pa',
                'description' => 'Nhà hàng với ẩm thực truyền thống Bình Định và văn hóa Chăm Pa',
                'address' => 'Đường Nguyễn Huệ, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'rating' => 4.3,
                'price_range' => '150,000 - 300,000 VND',
                'image' => 'restaurants/cham_pa.jpg',
            ],
            [
                'name' => 'Nhà hàng Tây Sơn',
                'description' => 'Nhà hàng với các món ăn truyền thống Tây Sơn',
                'address' => 'Huyện Tây Sơn, Tỉnh Bình Định',
                'latitude' => 14.0667,
                'longitude' => 108.8833,
                'rating' => 4.2,
                'price_range' => '100,000 - 250,000 VND',
                'image' => 'restaurants/tay_son.jpg',
            ],
            [
                'name' => 'Nhà hàng Biển Xanh',
                'description' => 'Nhà hàng ven biển với view biển tuyệt đẹp',
                'address' => 'Bãi biển Kỳ Co, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7833,
                'longitude' => 109.2833,
                'rating' => 4.4,
                'price_range' => '180,000 - 400,000 VND',
                'image' => 'restaurants/bien_xanh.jpg',
            ],
            [
                'name' => 'Nhà hàng Phù Cát',
                'description' => 'Nhà hàng với ẩm thực địa phương Phù Cát',
                'address' => 'Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'rating' => 4.1,
                'price_range' => '120,000 - 280,000 VND',
                'image' => 'restaurants/phu_cat.jpg',
            ],
            [
                'name' => 'Nhà hàng An Nhơn',
                'description' => 'Nhà hàng tại thị xã An Nhơn với ẩm thực truyền thống',
                'address' => 'Thị xã An Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8833,
                'longitude' => 109.1167,
                'rating' => 4.0,
                'price_range' => '100,000 - 250,000 VND',
                'image' => 'restaurants/an_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Tuy Phước',
                'description' => 'Nhà hàng với ẩm thực địa phương Tuy Phước',
                'address' => 'Huyện Tuy Phước, Tỉnh Bình Định',
                'latitude' => 13.9333,
                'longitude' => 109.1000,
                'rating' => 4.2,
                'price_range' => '120,000 - 280,000 VND',
                'image' => 'restaurants/tuy_phuoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Eo Gió',
                'description' => 'Nhà hàng với view biển Eo Gió tuyệt đẹp',
                'address' => 'Bãi biển Eo Gió, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8000,
                'longitude' => 109.2667,
                'rating' => 4.3,
                'price_range' => '150,000 - 350,000 VND',
                'image' => 'restaurants/eo_gio.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Giang',
                'description' => 'Nhà hàng ven biển Hải Giang với hải sản tươi ngon',
                'address' => 'Bãi biển Hải Giang, Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'rating' => 4.4,
                'price_range' => '180,000 - 400,000 VND',
                'image' => 'restaurants/hai_giang.jpg',
            ],
            [
                'name' => 'Nhà hàng Trung Tâm Quy Nhơn',
                'description' => 'Nhà hàng tại trung tâm thành phố Quy Nhơn',
                'address' => 'Đường Lê Lợi, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'rating' => 4.1,
                'price_range' => '120,000 - 300,000 VND',
                'image' => 'restaurants/trung_tam_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Hòn Khô',
                'description' => 'Nhà hàng trên đảo Hòn Khô với hải sản tươi ngon',
                'address' => 'Đảo Hòn Khô, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.3000,
                'rating' => 4.5,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/hon_kho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bãi Dài',
                'description' => 'Nhà hàng ven biển Bãi Dài với không gian yên tĩnh',
                'address' => 'Bãi biển Bãi Dài, Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0500,
                'longitude' => 109.0500,
                'rating' => 4.2,
                'price_range' => '150,000 - 350,000 VND',
                'image' => 'restaurants/bai_dai.jpg',
            ],
            [
                'name' => 'Nhà hàng Trung Lương',
                'description' => 'Nhà hàng ven biển Trung Lương với hải sản tươi ngon',
                'address' => 'Bãi biển Trung Lương, Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0333,
                'longitude' => 109.0333,
                'rating' => 4.3,
                'price_range' => '160,000 - 380,000 VND',
                'image' => 'restaurants/trung_luong.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Minh',
                'description' => 'Nhà hàng ven biển Hải Minh với không gian yên tĩnh',
                'address' => 'Bãi biển Hải Minh, Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0667,
                'longitude' => 109.0167,
                'rating' => 4.1,
                'price_range' => '140,000 - 320,000 VND',
                'image' => 'restaurants/hai_minh.jpg',
            ],
            [
                'name' => 'Nhà hàng Cát Tiến',
                'description' => 'Nhà hàng tại xã Cát Tiến với ẩm thực địa phương',
                'address' => 'Xã Cát Tiến, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0833,
                'longitude' => 109.0333,
                'rating' => 4.0,
                'price_range' => '120,000 - 280,000 VND',
                'image' => 'restaurants/cat_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng Nhơn Lý',
                'description' => 'Nhà hàng tại xã Nhơn Lý với hải sản tươi ngon',
                'address' => 'Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7833,
                'longitude' => 109.2833,
                'rating' => 4.2,
                'price_range' => '150,000 - 350,000 VND',
                'image' => 'restaurants/nhon_ly.jpg',
            ],
            [
                'name' => 'Nhà hàng Phước Hiệp',
                'description' => 'Nhà hàng tại xã Phước Hiệp với ẩm thực truyền thống',
                'address' => 'Xã Phước Hiệp, Huyện Tuy Phước, Tỉnh Bình Định',
                'latitude' => 13.9167,
                'longitude' => 109.1167,
                'rating' => 4.1,
                'price_range' => '130,000 - 300,000 VND',
                'image' => 'restaurants/phuoc_hiep.jpg',
            ],
            [
                'name' => 'Nhà hàng Phước Hòa',
                'description' => 'Nhà hàng tại xã Phước Hòa với ẩm thực địa phương',
                'address' => 'Xã Phước Hòa, Huyện Tuy Phước, Tỉnh Bình Định',
                'latitude' => 13.9333,
                'longitude' => 109.1000,
                'rating' => 4.0,
                'price_range' => '120,000 - 280,000 VND',
                'image' => 'restaurants/phuoc_hoa.jpg',
            ],
            [
                'name' => 'Nhà hàng Nhơn Thành',
                'description' => 'Nhà hàng tại xã Nhơn Thành với ẩm thực truyền thống',
                'address' => 'Xã Nhơn Thành, Huyện An Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8833,
                'longitude' => 109.1167,
                'rating' => 4.1,
                'price_range' => '130,000 - 300,000 VND',
                'image' => 'restaurants/nhon_thanh.jpg',
            ],
            [
                'name' => 'Nhà hàng Bình Thành',
                'description' => 'Nhà hàng tại xã Bình Thành với ẩm thực Tây Sơn',
                'address' => 'Xã Bình Thành, Huyện Tây Sơn, Tỉnh Bình Định',
                'latitude' => 14.0667,
                'longitude' => 108.8833,
                'rating' => 4.2,
                'price_range' => '140,000 - 320,000 VND',
                'image' => 'restaurants/binh_thanh.jpg',
            ],
            [
                'name' => 'Nhà hàng Biển Đông',
                'description' => 'Nhà hàng với view biển Đông tuyệt đẹp',
                'address' => 'Đường Trần Hưng Đạo, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2333,
                'rating' => 4.4,
                'price_range' => '180,000 - 420,000 VND',
                'image' => 'restaurants/bien_dong.jpg',
            ],
            [
                'name' => 'Nhà hàng Vịnh Quy Nhơn',
                'description' => 'Nhà hàng với view vịnh Quy Nhơn',
                'address' => 'Đường Trần Hưng Đạo, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2333,
                'rating' => 4.3,
                'price_range' => '170,000 - 400,000 VND',
                'image' => 'restaurants/vinh_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Núi Vũng Chua',
                'description' => 'Nhà hàng trên núi Vũng Chua với view toàn cảnh',
                'address' => 'Núi Vũng Chua, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8167,
                'longitude' => 109.2500,
                'rating' => 4.2,
                'price_range' => '160,000 - 380,000 VND',
                'image' => 'restaurants/nui_vung_chua.jpg',
            ],
            [
                'name' => 'Nhà hàng Núi Bà',
                'description' => 'Nhà hàng trên núi Bà với view toàn cảnh',
                'address' => 'Núi Bà, Xã Nhơn Lý, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.8333,
                'longitude' => 109.2333,
                'rating' => 4.1,
                'price_range' => '150,000 - 350,000 VND',
                'image' => 'restaurants/nui_ba.jpg',
            ],
            [
                'name' => 'Nhà hàng Cảng Quy Nhơn',
                'description' => 'Nhà hàng ven cảng với hải sản tươi ngon',
                'address' => 'Cảng Quy Nhơn, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2333,
                'rating' => 4.3,
                'price_range' => '170,000 - 400,000 VND',
                'image' => 'restaurants/cang_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Chợ Quy Nhơn',
                'description' => 'Nhà hàng gần chợ với ẩm thực địa phương',
                'address' => 'Chợ Quy Nhơn, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'rating' => 4.0,
                'price_range' => '120,000 - 280,000 VND',
                'image' => 'restaurants/cho_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Trường Đại học Quy Nhơn',
                'description' => 'Nhà hàng gần trường đại học với giá cả hợp lý',
                'address' => 'Trường Đại học Quy Nhơn, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'rating' => 4.1,
                'price_range' => '100,000 - 250,000 VND',
                'image' => 'restaurants/dai_hoc_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Bệnh viện Quy Nhơn',
                'description' => 'Nhà hàng gần bệnh viện với ẩm thực lành mạnh',
                'address' => 'Bệnh viện Quy Nhơn, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'rating' => 4.0,
                'price_range' => '120,000 - 280,000 VND',
                'image' => 'restaurants/benh_vien_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Sân bay Phù Cát',
                'description' => 'Nhà hàng gần sân bay với ẩm thực đa dạng',
                'address' => 'Sân bay Phù Cát, Huyện Phù Cát, Tỉnh Bình Định',
                'latitude' => 14.0167,
                'longitude' => 109.0167,
                'rating' => 4.2,
                'price_range' => '150,000 - 350,000 VND',
                'image' => 'restaurants/san_bay_phu_cat.jpg',
            ],
            [
                'name' => 'Nhà hàng Ga Quy Nhơn',
                'description' => 'Nhà hàng gần ga xe lửa với ẩm thực địa phương',
                'address' => 'Ga Quy Nhơn, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'rating' => 4.0,
                'price_range' => '120,000 - 280,000 VND',
                'image' => 'restaurants/ga_quy_nhon.jpg',
            ],
            [
                'name' => 'Nhà hàng Bến xe Quy Nhơn',
                'description' => 'Nhà hàng gần bến xe với ẩm thực nhanh',
                'address' => 'Bến xe Quy Nhơn, TP. Quy Nhơn, Tỉnh Bình Định',
                'latitude' => 13.7667,
                'longitude' => 109.2167,
                'rating' => 3.9,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/ben_xe_quy_nhon.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
