<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaLatRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Bánh Căn Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh căn và các món ăn đặc sản Đà Lạt',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9465,
                'longitude' => 108.4419,
                'rating' => 4.5,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_can_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Gà Lá É Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ lẩu gà lá é và các món ăn từ gà',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9454,
                'longitude' => 108.4420,
                'rating' => 4.4,
                'price_range' => '150,000 - 400,000 VND',
                'image' => 'restaurants/lau_ga_la_e_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Huế Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún bò Huế và các món ăn Huế',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9480,
                'longitude' => 108.4380,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/bun_bo_hue_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Niêu Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ cơm niêu và các món ăn truyền thống',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9500,
                'longitude' => 108.4350,
                'rating' => 4.2,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/com_nieu_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì và các món ăn sáng',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9460,
                'longitude' => 108.4400,
                'rating' => 4.1,
                'price_range' => '20,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ phở và các món ăn Việt Nam',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9440,
                'longitude' => 108.4440,
                'rating' => 4.0,
                'price_range' => '40,000 - 120,000 VND',
                'image' => 'restaurants/pho_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Xèo Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh xèo và các món ăn miền Tây',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9420,
                'longitude' => 108.4460,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_xeo_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Chả Cá Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún chả cá và các món ăn từ cá',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9400,
                'longitude' => 108.4480,
                'rating' => 4.2,
                'price_range' => '60,000 - 160,000 VND',
                'image' => 'restaurants/bun_cha_ca_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn và các món ăn truyền thống',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9380,
                'longitude' => 108.4500,
                'rating' => 4.1,
                'price_range' => '40,000 - 100,000 VND',
                'image' => 'restaurants/banh_cuon_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Riêu Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún riêu và các món ăn truyền thống',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9360,
                'longitude' => 108.4520,
                'rating' => 4.0,
                'price_range' => '45,000 - 120,000 VND',
                'image' => 'restaurants/bun_rieu_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh bèo và các món ăn Huế',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9340,
                'longitude' => 108.4540,
                'rating' => 4.3,
                'price_range' => '50,000 - 130,000 VND',
                'image' => 'restaurants/banh_beo_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Nam Bộ Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún bò Nam Bộ và các món ăn miền Nam',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9320,
                'longitude' => 108.4560,
                'rating' => 4.2,
                'price_range' => '55,000 - 140,000 VND',
                'image' => 'restaurants/bun_bo_nam_bo_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng và các món ăn sáng',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9300,
                'longitude' => 108.4580,
                'rating' => 4.1,
                'price_range' => '25,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Bò Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ phở bò và các món ăn Việt Nam',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9280,
                'longitude' => 108.4600,
                'rating' => 4.0,
                'price_range' => '45,000 - 130,000 VND',
                'image' => 'restaurants/pho_bo_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Xèo Tôm Nhảy Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh xèo tôm nhảy và các món ăn miền Tây',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9260,
                'longitude' => 108.4620,
                'rating' => 4.3,
                'price_range' => '60,000 - 160,000 VND',
                'image' => 'restaurants/banh_xeo_tom_nhay_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Chả Cá Lăng Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún chả cá lăng và các món ăn từ cá',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9240,
                'longitude' => 108.4640,
                'rating' => 4.2,
                'price_range' => '70,000 - 180,000 VND',
                'image' => 'restaurants/bun_cha_ca_lang_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Nóng Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn nóng và các món ăn truyền thống',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9220,
                'longitude' => 108.4660,
                'rating' => 4.1,
                'price_range' => '50,000 - 120,000 VND',
                'image' => 'restaurants/banh_cuon_nong_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Riêu Cua Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún riêu cua và các món ăn truyền thống',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9200,
                'longitude' => 108.4680,
                'rating' => 4.0,
                'price_range' => '55,000 - 140,000 VND',
                'image' => 'restaurants/bun_rieu_cua_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Nậm Lọc Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh bèo nậm lọc và các món ăn Huế',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9180,
                'longitude' => 108.4700,
                'rating' => 4.3,
                'price_range' => '60,000 - 150,000 VND',
                'image' => 'restaurants/banh_beo_nam_loc_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Gà Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún bò gà và các món ăn miền Nam',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9160,
                'longitude' => 108.4720,
                'rating' => 4.2,
                'price_range' => '65,000 - 160,000 VND',
                'image' => 'restaurants/bun_bo_ga_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì chả cá và các món ăn sáng',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9140,
                'longitude' => 108.4740,
                'rating' => 4.1,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Gà Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ phở gà và các món ăn Việt Nam',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9120,
                'longitude' => 108.4760,
                'rating' => 4.0,
                'price_range' => '50,000 - 140,000 VND',
                'image' => 'restaurants/pho_ga_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Xèo Hải Sản Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh xèo hải sản và các món ăn miền Tây',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9100,
                'longitude' => 108.4780,
                'rating' => 4.3,
                'price_range' => '70,000 - 180,000 VND',
                'image' => 'restaurants/banh_xeo_hai_san_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Chả Cá Thu Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún chả cá thu và các món ăn từ cá',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9080,
                'longitude' => 108.4800,
                'rating' => 4.2,
                'price_range' => '75,000 - 190,000 VND',
                'image' => 'restaurants/bun_cha_ca_thu_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Tôm Thịt Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn tôm thịt và các món ăn truyền thống',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9060,
                'longitude' => 108.4820,
                'rating' => 4.1,
                'price_range' => '60,000 - 140,000 VND',
                'image' => 'restaurants/banh_cuon_tom_thit_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Riêu Tôm Cua Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún riêu tôm cua và các món ăn truyền thống',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9040,
                'longitude' => 108.4840,
                'rating' => 4.0,
                'price_range' => '65,000 - 160,000 VND',
                'image' => 'restaurants/bun_rieu_tom_cua_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Bánh Lọc Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh bèo bánh lọc và các món ăn Huế',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9020,
                'longitude' => 108.4860,
                'rating' => 4.3,
                'price_range' => '70,000 - 170,000 VND',
                'image' => 'restaurants/banh_beo_banh_loc_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Huế Đặc Biệt Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bún bò Huế đặc biệt và các món ăn Huế',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9000,
                'longitude' => 108.4880,
                'rating' => 4.2,
                'price_range' => '75,000 - 180,000 VND',
                'image' => 'restaurants/bun_bo_hue_dac_biet_dalat.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Đặc Biệt Đà Lạt',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng đặc biệt và các món ăn sáng',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.8980,
                'longitude' => 108.4900,
                'rating' => 4.1,
                'price_range' => '35,000 - 110,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_dac_biet_dalat.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
