<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaLatCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        // Kiểm tra và tạo location Đà Lạt nếu chưa có
        $daLatLocationId = DB::table('locations')->where('name', 'Đà Lạt')->value('id');

        if (!$daLatLocationId) {
            $daLatLocationId = DB::table('locations')->insertGetId([
                'name' => 'Đà Lạt',
                'description' => 'Thành phố Đà Lạt - thành phố ngàn hoa với khí hậu mát mẻ và cảnh quan thiên nhiên tuyệt đẹp',
                'latitude' => 11.9465,
                'longitude' => 108.4419,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Hồ Xuân Hương',
                'description' => 'Hồ nước đẹp ở trung tâm thành phố với view núi và không gian lãng mạn',
                'address' => 'Hồ Xuân Hương, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9465,
                'longitude' => 108.4419,
                'image' => 'checkin/ho_xuan_huong_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/ho_xuan_huong_dalat_1.jpg', 'checkin/ho_xuan_huong_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Trái tim của thành phố Đà Lạt',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Hoa Đà Lạt',
                'description' => 'Vườn hoa lớn với nhiều loài hoa đẹp và không gian xanh mát',
                'address' => 'Vườn Hoa Đà Lạt, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9454,
                'longitude' => 108.4420,
                'image' => 'checkin/vuon_hoa_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_hoa_dalat_1.jpg', 'checkin/vuon_hoa_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thiên đường hoa Đà Lạt',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Datanla',
                'description' => 'Thác nước đẹp với máng trượt và không gian mát mẻ',
                'address' => 'Thác Datanla, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9480,
                'longitude' => 108.4380,
                'image' => 'checkin/thac_datanla_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 60000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_datanla_dalat_1.jpg', 'checkin/thac_datanla_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thác nước nổi tiếng Đà Lạt',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đồi Chè Cầu Đất',
                'description' => 'Đồi chè xanh mướt với view núi và không gian yên tĩnh',
                'address' => 'Đồi Chè Cầu Đất, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9500,
                'longitude' => 108.4350,
                'image' => 'checkin/doi_che_cau_dat_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/doi_che_cau_dat_dalat_1.jpg', 'checkin/doi_che_cau_dat_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Đồi chè xanh mướt',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Tuyền Lâm',
                'description' => 'Hồ nước lớn với view núi và không gian yên tĩnh',
                'address' => 'Hồ Tuyền Lâm, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9460,
                'longitude' => 108.4400,
                'image' => 'checkin/ho_tuyen_lam_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ho_tuyen_lam_dalat_1.jpg', 'checkin/ho_tuyen_lam_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Hồ nước lớn nhất Đà Lạt',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Thung Lũng Tình Yêu',
                'description' => 'Thung lũng lãng mạn với hoa và không gian yên tĩnh',
                'address' => 'Thung Lũng Tình Yêu, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9440,
                'longitude' => 108.4440,
                'image' => 'checkin/thung_lung_tinh_yeu_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thung_lung_tinh_yeu_dalat_1.jpg', 'checkin/thung_lung_tinh_yeu_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thung lũng lãng mạn cho cặp đôi',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đồi Thiên Phúc Đức',
                'description' => 'Đồi thông với view toàn cảnh thành phố và không gian yên tĩnh',
                'address' => 'Đồi Thiên Phúc Đức, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9420,
                'longitude' => 108.4460,
                'image' => 'checkin/doi_thien_phuc_duc_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/doi_thien_phuc_duc_dalat_1.jpg', 'checkin/doi_thien_phuc_duc_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Điểm ngắm cảnh đẹp nhất',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Lan Đà Lạt',
                'description' => 'Vườn lan với nhiều loài lan đẹp và không gian thanh lịch',
                'address' => 'Vườn Lan Đà Lạt, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9400,
                'longitude' => 108.4480,
                'image' => 'checkin/vuon_lan_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_lan_dalat_1.jpg', 'checkin/vuon_lan_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Vườn lan đẹp nhất Đà Lạt',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Prenn',
                'description' => 'Thác nước đẹp với cầu treo và không gian mát mẻ',
                'address' => 'Thác Prenn, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9380,
                'longitude' => 108.4500,
                'image' => 'checkin/thac_prenn_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_prenn_dalat_1.jpg', 'checkin/thac_prenn_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thác nước với cầu treo đẹp',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đồi Chè Mộng Mơ',
                'description' => 'Đồi chè với view núi và không gian lãng mạn',
                'address' => 'Đồi Chè Mộng Mơ, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9360,
                'longitude' => 108.4520,
                'image' => 'checkin/doi_che_mong_mo_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/doi_che_mong_mo_dalat_1.jpg', 'checkin/doi_che_mong_mo_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Đồi chè lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Than Thở',
                'description' => 'Hồ nước nhỏ với không gian yên tĩnh và view núi',
                'address' => 'Hồ Than Thở, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9340,
                'longitude' => 108.4540,
                'image' => 'checkin/ho_than_tho_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ho_than_tho_dalat_1.jpg', 'checkin/ho_than_tho_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Hồ nước yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Hoa Hồng Đà Lạt',
                'description' => 'Vườn hoa hồng với nhiều loài hoa hồng đẹp',
                'address' => 'Vườn Hoa Hồng Đà Lạt, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9320,
                'longitude' => 108.4560,
                'image' => 'checkin/vuon_hoa_hong_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_hoa_hong_dalat_1.jpg', 'checkin/vuon_hoa_hong_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Vườn hoa hồng lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Cam Ly',
                'description' => 'Thác nước trong thành phố với không gian mát mẻ',
                'address' => 'Thác Cam Ly, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9300,
                'longitude' => 108.4580,
                'image' => 'checkin/thac_cam_ly_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_cam_ly_dalat_1.jpg', 'checkin/thac_cam_ly_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thác nước trong lòng thành phố',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đồi Chè Tuyết',
                'description' => 'Đồi chè tuyết với view núi và không gian hoang dã',
                'address' => 'Đồi Chè Tuyết, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9280,
                'longitude' => 108.4600,
                'image' => 'checkin/doi_che_tuyet_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/doi_che_tuyet_dalat_1.jpg', 'checkin/doi_che_tuyet_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Đồi chè tuyết hoang dã',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Mê Linh',
                'description' => 'Hồ nước nhỏ với không gian yên tĩnh và view núi',
                'address' => 'Hồ Mê Linh, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9260,
                'longitude' => 108.4620,
                'image' => 'checkin/ho_me_linh_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ho_me_linh_dalat_1.jpg', 'checkin/ho_me_linh_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Hồ nước yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Hoa Cẩm Tú Cầu Đà Lạt',
                'description' => 'Vườn hoa cẩm tú cầu với nhiều màu sắc đẹp',
                'address' => 'Vườn Hoa Cẩm Tú Cầu, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9240,
                'longitude' => 108.4640,
                'image' => 'checkin/vuon_hoa_cam_tu_cau_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_hoa_cam_tu_cau_dalat_1.jpg', 'checkin/vuon_hoa_cam_tu_cau_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Vườn hoa cẩm tú cầu rực rỡ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Voi',
                'description' => 'Thác nước lớn với view núi và không gian hoang dã',
                'address' => 'Thác Voi, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9220,
                'longitude' => 108.4660,
                'image' => 'checkin/thac_voi_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 45000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_voi_dalat_1.jpg', 'checkin/thac_voi_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thác nước hoang dã',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đồi Chè Bảo Lộc',
                'description' => 'Đồi chè với view núi và không gian yên tĩnh',
                'address' => 'Đồi Chè Bảo Lộc, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9200,
                'longitude' => 108.4680,
                'image' => 'checkin/doi_che_bao_loc_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/doi_che_bao_loc_dalat_1.jpg', 'checkin/doi_che_bao_loc_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Đồi chè yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Đan Kia',
                'description' => 'Hồ nước nhỏ với không gian yên tĩnh và view núi',
                'address' => 'Hồ Đan Kia, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9180,
                'longitude' => 108.4700,
                'image' => 'checkin/ho_dan_kia_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ho_dan_kia_dalat_1.jpg', 'checkin/ho_dan_kia_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Hồ nước yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Hoa Oải Hương Đà Lạt',
                'description' => 'Vườn hoa oải hương với không gian thơ mộng',
                'address' => 'Vườn Hoa Oải Hương, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9160,
                'longitude' => 108.4720,
                'image' => 'checkin/vuon_hoa_oai_huong_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_hoa_oai_huong_dalat_1.jpg', 'checkin/vuon_hoa_oai_huong_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Vườn hoa oải hương thơ mộng',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Liên Khương',
                'description' => 'Thác nước với view núi và không gian mát mẻ',
                'address' => 'Thác Liên Khương, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9140,
                'longitude' => 108.4740,
                'image' => 'checkin/thac_lien_khuong_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_lien_khuong_dalat_1.jpg', 'checkin/thac_lien_khuong_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thác nước mát mẻ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đồi Chè Lâm Đồng',
                'description' => 'Đồi chè với view núi và không gian yên tĩnh',
                'address' => 'Đồi Chè Lâm Đồng, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9120,
                'longitude' => 108.4760,
                'image' => 'checkin/doi_che_lam_dong_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/doi_che_lam_dong_dalat_1.jpg', 'checkin/doi_che_lam_dong_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Đồi chè yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Suối Vàng',
                'description' => 'Hồ nước với view núi và không gian yên tĩnh',
                'address' => 'Hồ Suối Vàng, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9100,
                'longitude' => 108.4780,
                'image' => 'checkin/ho_suoi_vang_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ho_suoi_vang_dalat_1.jpg', 'checkin/ho_suoi_vang_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Hồ nước yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Hoa Hướng Dương Đà Lạt',
                'description' => 'Vườn hoa hướng dương với không gian ấm áp',
                'address' => 'Vườn Hoa Hướng Dương, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9080,
                'longitude' => 108.4800,
                'image' => 'checkin/vuon_hoa_huong_duong_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_hoa_huong_duong_dalat_1.jpg', 'checkin/vuon_hoa_huong_duong_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Vườn hoa hướng dương ấm áp',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Gougah',
                'description' => 'Thác nước với view núi và không gian hoang dã',
                'address' => 'Thác Gougah, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9060,
                'longitude' => 108.4820,
                'image' => 'checkin/thac_gougah_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_gougah_dalat_1.jpg', 'checkin/thac_gougah_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Thác nước hoang dã',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đồi Chè Đà Lạt',
                'description' => 'Đồi chè với view núi và không gian yên tĩnh',
                'address' => 'Đồi Chè Đà Lạt, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9040,
                'longitude' => 108.4840,
                'image' => 'checkin/doi_che_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/doi_che_dalat_1.jpg', 'checkin/doi_che_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Đồi chè yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Đa Nhim',
                'description' => 'Hồ nước với view núi và không gian yên tĩnh',
                'address' => 'Hồ Đa Nhim, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9020,
                'longitude' => 108.4860,
                'image' => 'checkin/ho_da_nhim_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ho_da_nhim_dalat_1.jpg', 'checkin/ho_da_nhim_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Hồ nước yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Hoa Cúc Đà Lạt',
                'description' => 'Vườn hoa cúc với không gian tươi mới',
                'address' => 'Vườn Hoa Cúc, Phường 8, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'latitude' => 11.9000,
                'longitude' => 108.4880,
                'image' => 'checkin/vuon_hoa_cuc_dalat.jpg',
                'location_id' => $daLatLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_hoa_cuc_dalat_1.jpg', 'checkin/vuon_hoa_cuc_dalat_2.jpg']),
                'region' => 'Tây Nguyên',
                'caption' => 'Vườn hoa cúc tươi mới',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
