<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaLatHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'Ana Mandara Villas Dalat Resort & Spa',
                'description' => 'Resort 5 sao cao cấp với biệt thự Pháp cổ điển và view núi tuyệt đẹp',
                'address' => 'Đường Lê Lai, Phường 5, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/ana_mandara_dalat_1.jpg', 'hotels/ana_mandara_dalat_2.jpg']),
                'latitude' => 11.9465,
                'longitude' => 108.4419,
                'email' => 'reservations@anamandara-dalat.com',
                'phone' => '0263 3555 888',
                'website' => 'https://www.anamandara-dalat.com',
            ],
            [
                'name' => 'Dalat Palace Heritage Hotel',
                'description' => 'Khách sạn 5 sao di sản với kiến trúc Pháp cổ điển và dịch vụ sang trọng',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/dalat_palace_1.jpg', 'hotels/dalat_palace_2.jpg']),
                'latitude' => 11.9454,
                'longitude' => 108.4420,
                'email' => 'reservations@dalatpalace.com',
                'phone' => '0263 3825 444',
                'website' => 'https://www.dalatpalace.com',
            ],
            [
                'name' => 'Terracotta Hotel & Resort Dalat',
                'description' => 'Resort 4 sao với thiết kế hiện đại và view hồ Xuân Hương',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/terracotta_dalat_1.jpg', 'hotels/terracotta_dalat_2.jpg']),
                'latitude' => 11.9480,
                'longitude' => 108.4380,
                'email' => 'reservations@terracotta-dalat.com',
                'phone' => '0263 3555 777',
                'website' => 'https://www.terracotta-dalat.com',
            ],
            [
                'name' => 'Dalat Edensee Lake Resort & Spa',
                'description' => 'Resort 4 sao với view hồ Tuyền Lâm và không gian yên tĩnh',
                'address' => 'Hồ Tuyền Lâm, Phường 11, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/edensee_dalat_1.jpg', 'hotels/edensee_dalat_2.jpg']),
                'latitude' => 11.9500,
                'longitude' => 108.4350,
                'email' => 'reservations@edensee-dalat.com',
                'phone' => '0263 3555 666',
                'website' => 'https://www.edensee-dalat.com',
            ],
            [
                'name' => 'Mercure Dalat Resort',
                'description' => 'Resort 4 sao quốc tế với thiết kế hiện đại và dịch vụ chất lượng',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/mercure_dalat_1.jpg', 'hotels/mercure_dalat_2.jpg']),
                'latitude' => 11.9460,
                'longitude' => 108.4400,
                'email' => 'reservations@mercure-dalat.com',
                'phone' => '0263 3555 555',
                'website' => 'https://www.mercure.com/dalat',
            ],
            [
                'name' => 'Dalat Heritage Hotel',
                'description' => 'Khách sạn 4 sao với kiến trúc Pháp cổ điển và dịch vụ ấm cúng',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/heritage_dalat_1.jpg', 'hotels/heritage_dalat_2.jpg']),
                'latitude' => 11.9440,
                'longitude' => 108.4440,
                'email' => 'reservations@heritage-dalat.com',
                'phone' => '0263 3555 444',
                'website' => 'https://www.heritage-dalat.com',
            ],
            [
                'name' => 'Dalat Wonder Resort',
                'description' => 'Resort 4 sao với view núi và không gian xanh mát',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/wonder_dalat_1.jpg', 'hotels/wonder_dalat_2.jpg']),
                'latitude' => 11.9420,
                'longitude' => 108.4460,
                'email' => 'reservations@wonder-dalat.com',
                'phone' => '0263 3555 333',
                'website' => 'https://www.wonder-dalat.com',
            ],
            [
                'name' => 'Dalat Cadasa Resort',
                'description' => 'Resort 3 sao với thiết kế độc đáo và không gian yên tĩnh',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/cadasa_dalat_1.jpg', 'hotels/cadasa_dalat_2.jpg']),
                'latitude' => 11.9400,
                'longitude' => 108.4480,
                'email' => 'reservations@cadasa-dalat.com',
                'phone' => '0263 3555 222',
                'website' => 'https://www.cadasa-dalat.com',
            ],
            [
                'name' => 'Dalat Golf Valley Resort',
                'description' => 'Resort 4 sao với sân golf và view núi tuyệt đẹp',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/golf_valley_dalat_1.jpg', 'hotels/golf_valley_dalat_2.jpg']),
                'latitude' => 11.9380,
                'longitude' => 108.4500,
                'email' => 'reservations@golfvalley-dalat.com',
                'phone' => '0263 3555 111',
                'website' => 'https://www.golfvalley-dalat.com',
            ],
            [
                'name' => 'Dalat Central Hotel',
                'description' => 'Khách sạn 3 sao tại trung tâm thành phố với vị trí thuận tiện',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/central_dalat_1.jpg', 'hotels/central_dalat_2.jpg']),
                'latitude' => 11.9360,
                'longitude' => 108.4520,
                'email' => 'reservations@central-dalat.com',
                'phone' => '0263 3555 000',
                'website' => 'https://www.central-dalat.com',
            ],
            [
                'name' => 'Dalat Boutique Hotel',
                'description' => 'Khách sạn boutique 3 sao với thiết kế độc đáo và dịch vụ thân thiện',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/boutique_dalat_1.jpg', 'hotels/boutique_dalat_2.jpg']),
                'latitude' => 11.9340,
                'longitude' => 108.4540,
                'email' => 'reservations@boutique-dalat.com',
                'phone' => '0263 3544 999',
                'website' => 'https://www.boutique-dalat.com',
            ],
            [
                'name' => 'Dalat Mountain View Hotel',
                'description' => 'Khách sạn 3 sao với view núi và không gian ấm cúng',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/mountain_view_dalat_1.jpg', 'hotels/mountain_view_dalat_2.jpg']),
                'latitude' => 11.9320,
                'longitude' => 108.4560,
                'email' => 'reservations@mountainview-dalat.com',
                'phone' => '0263 3544 888',
                'website' => 'https://www.mountainview-dalat.com',
            ],
            [
                'name' => 'Dalat Garden Hotel',
                'description' => 'Khách sạn 3 sao với vườn hoa đẹp và không gian xanh mát',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/garden_dalat_1.jpg', 'hotels/garden_dalat_2.jpg']),
                'latitude' => 11.9300,
                'longitude' => 108.4580,
                'email' => 'reservations@garden-dalat.com',
                'phone' => '0263 3544 777',
                'website' => 'https://www.garden-dalat.com',
            ],
            [
                'name' => 'Dalat Lake View Hotel',
                'description' => 'Khách sạn 3 sao với view hồ Xuân Hương và dịch vụ thân thiện',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/lake_view_dalat_1.jpg', 'hotels/lake_view_dalat_2.jpg']),
                'latitude' => 11.9280,
                'longitude' => 108.4600,
                'email' => 'reservations@lakeview-dalat.com',
                'phone' => '0263 3544 666',
                'website' => 'https://www.lakeview-dalat.com',
            ],
            [
                'name' => 'Dalat Flower Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề hoa và không gian lãng mạn',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/flower_dalat_1.jpg', 'hotels/flower_dalat_2.jpg']),
                'latitude' => 11.9260,
                'longitude' => 108.4620,
                'email' => 'reservations@flower-dalat.com',
                'phone' => '0263 3544 555',
                'website' => 'https://www.flower-dalat.com',
            ],
            [
                'name' => 'Dalat Pine Hotel',
                'description' => 'Khách sạn 3 sao với view rừng thông và không gian yên tĩnh',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/pine_dalat_1.jpg', 'hotels/pine_dalat_2.jpg']),
                'latitude' => 11.9240,
                'longitude' => 108.4640,
                'email' => 'reservations@pine-dalat.com',
                'phone' => '0263 3544 444',
                'website' => 'https://www.pine-dalat.com',
            ],
            [
                'name' => 'Dalat Valley Hotel',
                'description' => 'Khách sạn 3 sao với view thung lũng và không gian mát mẻ',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/valley_dalat_1.jpg', 'hotels/valley_dalat_2.jpg']),
                'latitude' => 11.9220,
                'longitude' => 108.4660,
                'email' => 'reservations@valley-dalat.com',
                'phone' => '0263 3544 333',
                'website' => 'https://www.valley-dalat.com',
            ],
            [
                'name' => 'Dalat Spring Hotel',
                'description' => 'Khách sạn 3 sao với view suối và không gian tự nhiên',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/spring_dalat_1.jpg', 'hotels/spring_dalat_2.jpg']),
                'latitude' => 11.9200,
                'longitude' => 108.4680,
                'email' => 'reservations@spring-dalat.com',
                'phone' => '0263 3544 222',
                'website' => 'https://www.spring-dalat.com',
            ],
            [
                'name' => 'Dalat Forest Hotel',
                'description' => 'Khách sạn 3 sao với view rừng và không gian hoang dã',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/forest_dalat_1.jpg', 'hotels/forest_dalat_2.jpg']),
                'latitude' => 11.9180,
                'longitude' => 108.4700,
                'email' => 'reservations@forest-dalat.com',
                'phone' => '0263 3544 111',
                'website' => 'https://www.forest-dalat.com',
            ],
            [
                'name' => 'Dalat Cloud Hotel',
                'description' => 'Khách sạn 3 sao với view mây và không gian lãng mạn',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/cloud_dalat_1.jpg', 'hotels/cloud_dalat_2.jpg']),
                'latitude' => 11.9160,
                'longitude' => 108.4720,
                'email' => 'reservations@cloud-dalat.com',
                'phone' => '0263 3544 000',
                'website' => 'https://www.cloud-dalat.com',
            ],
            [
                'name' => 'Dalat Mist Hotel',
                'description' => 'Khách sạn 3 sao với view sương mù và không gian huyền ảo',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/mist_dalat_1.jpg', 'hotels/mist_dalat_2.jpg']),
                'latitude' => 11.9140,
                'longitude' => 108.4740,
                'email' => 'reservations@mist-dalat.com',
                'phone' => '0263 3533 999',
                'website' => 'https://www.mist-dalat.com',
            ],
            [
                'name' => 'Dalat Rose Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề hoa hồng và không gian lãng mạn',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/rose_dalat_1.jpg', 'hotels/rose_dalat_2.jpg']),
                'latitude' => 11.9120,
                'longitude' => 108.4760,
                'email' => 'reservations@rose-dalat.com',
                'phone' => '0263 3533 888',
                'website' => 'https://www.rose-dalat.com',
            ],
            [
                'name' => 'Dalat Lavender Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề oải hương và không gian thơ mộng',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/lavender_dalat_1.jpg', 'hotels/lavender_dalat_2.jpg']),
                'latitude' => 11.9100,
                'longitude' => 108.4780,
                'email' => 'reservations@lavender-dalat.com',
                'phone' => '0263 3533 777',
                'website' => 'https://www.lavender-dalat.com',
            ],
            [
                'name' => 'Dalat Orchid Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề lan và không gian thanh lịch',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/orchid_dalat_1.jpg', 'hotels/orchid_dalat_2.jpg']),
                'latitude' => 11.9080,
                'longitude' => 108.4800,
                'email' => 'reservations@orchid-dalat.com',
                'phone' => '0263 3533 666',
                'website' => 'https://www.orchid-dalat.com',
            ],
            [
                'name' => 'Dalat Daisy Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề cúc và không gian tươi mới',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/daisy_dalat_1.jpg', 'hotels/daisy_dalat_2.jpg']),
                'latitude' => 11.9060,
                'longitude' => 108.4820,
                'email' => 'reservations@daisy-dalat.com',
                'phone' => '0263 3533 555',
                'website' => 'https://www.daisy-dalat.com',
            ],
            [
                'name' => 'Dalat Tulip Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề tulip và không gian rực rỡ',
                'address' => 'Đường Trần Hưng Đạo, Phường 10, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/tulip_dalat_1.jpg', 'hotels/tulip_dalat_2.jpg']),
                'latitude' => 11.9040,
                'longitude' => 108.4840,
                'email' => 'reservations@tulip-dalat.com',
                'phone' => '0263 3533 444',
                'website' => 'https://www.tulip-dalat.com',
            ],
            [
                'name' => 'Dalat Sunflower Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề hướng dương và không gian ấm áp',
                'address' => 'Đường Phan Chu Trinh, Phường 9, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/sunflower_dalat_1.jpg', 'hotels/sunflower_dalat_2.jpg']),
                'latitude' => 11.9020,
                'longitude' => 108.4860,
                'email' => 'reservations@sunflower-dalat.com',
                'phone' => '0263 3533 333',
                'website' => 'https://www.sunflower-dalat.com',
            ],
            [
                'name' => 'Dalat Lily Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề huệ và không gian thanh khiết',
                'address' => 'Đường Trần Phú, Phường 3, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/lily_dalat_1.jpg', 'hotels/lily_dalat_2.jpg']),
                'latitude' => 11.9000,
                'longitude' => 108.4880,
                'email' => 'reservations@lily-dalat.com',
                'phone' => '0263 3533 222',
                'website' => 'https://www.lily-dalat.com',
            ],
            [
                'name' => 'Dalat Carnation Hotel',
                'description' => 'Khách sạn 3 sao với chủ đề cẩm chướng và không gian dịu dàng',
                'address' => 'Đường Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt, Tỉnh Lâm Đồng',
                'images' => json_encode(['hotels/carnation_dalat_1.jpg', 'hotels/carnation_dalat_2.jpg']),
                'latitude' => 11.8980,
                'longitude' => 108.4900,
                'email' => 'reservations@carnation-dalat.com',
                'phone' => '0263 3533 111',
                'website' => 'https://www.carnation-dalat.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
