<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaiPhongHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'Vinpearl Hotel Hai Phong',
                'description' => 'Khách sạn 5 sao cao cấp với view sông Lạch Tray tuyệt đẹp',
                'address' => 'Đường Lạch Tray, Quận Ngô Quyền, TP. Hải Phòng',
                'images' => json_encode(['hotels/vinpearl_hai_phong_1.jpg', 'hotels/vinpearl_hai_phong_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@vinpearl-hai-phong.com',
                'phone' => '0225 3958 888',
                'website' => 'https://www.vinpearl.com/hai-phong',
            ],
            [
                'name' => 'Hai Phong Grand Hotel',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Đường Điện Biên Phủ, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_grand_1.jpg', 'hotels/hai_phong_grand_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-grand.com',
                'phone' => '0225 3958 777',
                'website' => 'https://www.hai-phong-grand.com',
            ],
            [
                'name' => 'Cat Ba Island Resort & Spa',
                'description' => 'Resort 4 sao với view biển tuyệt đẹp tại đảo Cát Bà',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_resort_1.jpg', 'hotels/cat_ba_resort_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-resort.com',
                'phone' => '0225 3958 666',
                'website' => 'https://www.cat-ba-resort.com',
            ],
            [
                'name' => 'Do Son Beach Hotel',
                'description' => 'Khách sạn 3 sao với view biển Đồ Sơn đẹp',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_beach_1.jpg', 'hotels/do_son_beach_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-beach.com',
                'phone' => '0225 3958 555',
                'website' => 'https://www.do-son-beach.com',
            ],
            [
                'name' => 'Hai Phong Central Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_central_1.jpg', 'hotels/hai_phong_central_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-central.com',
                'phone' => '0225 3958 444',
                'website' => 'https://www.hai-phong-central.com',
            ],
            [
                'name' => 'Cat Ba Sunrise Resort',
                'description' => 'Resort 4 sao với view bình minh tuyệt đẹp tại Cát Bà',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_sunrise_1.jpg', 'hotels/cat_ba_sunrise_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-sunrise.com',
                'phone' => '0225 3958 333',
                'website' => 'https://www.cat-ba-sunrise.com',
            ],
            [
                'name' => 'Hai Phong Riverside Hotel',
                'description' => 'Khách sạn 3 sao với view sông Lạch Tray',
                'address' => 'Đường Lạch Tray, Quận Ngô Quyền, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_riverside_1.jpg', 'hotels/hai_phong_riverside_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-riverside.com',
                'phone' => '0225 3958 222',
                'website' => 'https://www.hai-phong-riverside.com',
            ],
            [
                'name' => 'Do Son Resort & Spa',
                'description' => 'Resort 4 sao với spa và dịch vụ cao cấp tại Đồ Sơn',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_resort_1.jpg', 'hotels/do_son_resort_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-resort.com',
                'phone' => '0225 3958 111',
                'website' => 'https://www.do-son-resort.com',
            ],
            [
                'name' => 'Hai Phong City Hotel',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm thành phố',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_city_1.jpg', 'hotels/hai_phong_city_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-city.com',
                'phone' => '0225 3958 000',
                'website' => 'https://www.hai-phong-city.com',
            ],
            [
                'name' => 'Cat Ba Eco Resort',
                'description' => 'Resort sinh thái 3 sao với không gian xanh tại Cát Bà',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_eco_1.jpg', 'hotels/cat_ba_eco_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-eco.com',
                'phone' => '0225 3957 999',
                'website' => 'https://www.cat-ba-eco.com',
            ],
            [
                'name' => 'Hai Phong Garden Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_garden_1.jpg', 'hotels/hai_phong_garden_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-garden.com',
                'phone' => '0225 3957 888',
                'website' => 'https://www.hai-phong-garden.com',
            ],
            [
                'name' => 'Do Son Palace Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng tại Đồ Sơn',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_palace_1.jpg', 'hotels/do_son_palace_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-palace.com',
                'phone' => '0225 3957 777',
                'website' => 'https://www.do-son-palace.com',
            ],
            [
                'name' => 'Hai Phong Plaza Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm mua sắm',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_plaza_1.jpg', 'hotels/hai_phong_plaza_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-plaza.com',
                'phone' => '0225 3957 666',
                'website' => 'https://www.hai-phong-plaza.com',
            ],
            [
                'name' => 'Cat Ba Bay Resort',
                'description' => 'Resort 4 sao với view vịnh Cát Bà tuyệt đẹp',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_bay_1.jpg', 'hotels/cat_ba_bay_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-bay.com',
                'phone' => '0225 3957 555',
                'website' => 'https://www.cat-ba-bay.com',
            ],
            [
                'name' => 'Hai Phong Royal Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và dịch vụ cao cấp',
                'address' => 'Đường Điện Biên Phủ, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_royal_1.jpg', 'hotels/hai_phong_royal_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-royal.com',
                'phone' => '0225 3957 444',
                'website' => 'https://www.hai-phong-royal.com',
            ],
            [
                'name' => 'Do Son Beach Resort',
                'description' => 'Resort 3 sao với bãi biển đẹp và không gian thoáng đãng',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_beach_resort_1.jpg', 'hotels/do_son_beach_resort_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-beach-resort.com',
                'phone' => '0225 3957 333',
                'website' => 'https://www.do-son-beach-resort.com',
            ],
            [
                'name' => 'Hai Phong Sky Hotel',
                'description' => 'Khách sạn 4 sao với view toàn cảnh thành phố từ trên cao',
                'address' => 'Đường Lạch Tray, Quận Ngô Quyền, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_sky_1.jpg', 'hotels/hai_phong_sky_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-sky.com',
                'phone' => '0225 3957 222',
                'website' => 'https://www.hai-phong-sky.com',
            ],
            [
                'name' => 'Cat Ba Mountain Resort',
                'description' => 'Resort 3 sao với view núi và biển tại Cát Bà',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_mountain_1.jpg', 'hotels/cat_ba_mountain_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-mountain.com',
                'phone' => '0225 3957 111',
                'website' => 'https://www.cat-ba-mountain.com',
            ],
            [
                'name' => 'Hai Phong Tower Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và view đẹp',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_tower_1.jpg', 'hotels/hai_phong_tower_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-tower.com',
                'phone' => '0225 3957 000',
                'website' => 'https://www.hai-phong-tower.com',
            ],
            [
                'name' => 'Do Son Ocean Hotel',
                'description' => 'Khách sạn 3 sao với view biển và không gian thoáng đãng',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_ocean_1.jpg', 'hotels/do_son_ocean_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-ocean.com',
                'phone' => '0225 3956 999',
                'website' => 'https://www.do-son-ocean.com',
            ],
            [
                'name' => 'Hai Phong View Hotel',
                'description' => 'Khách sạn 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_view_1.jpg', 'hotels/hai_phong_view_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-view.com',
                'phone' => '0225 3956 888',
                'website' => 'https://www.hai-phong-view.com',
            ],
            [
                'name' => 'Cat Ba Sea Resort',
                'description' => 'Resort 3 sao với view biển và không gian yên tĩnh',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_sea_1.jpg', 'hotels/cat_ba_sea_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-sea.com',
                'phone' => '0225 3956 777',
                'website' => 'https://www.cat-ba-sea.com',
            ],
            [
                'name' => 'Hai Phong Central Plaza Hotel',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_central_plaza_1.jpg', 'hotels/hai_phong_central_plaza_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-central-plaza.com',
                'phone' => '0225 3956 666',
                'website' => 'https://www.hai-phong-central-plaza.com',
            ],
            [
                'name' => 'Do Son Beach Palace',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng và bãi biển đẹp',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_beach_palace_1.jpg', 'hotels/do_son_beach_palace_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-beach-palace.com',
                'phone' => '0225 3956 555',
                'website' => 'https://www.do-son-beach-palace.com',
            ],
            [
                'name' => 'Hai Phong Golden Hotel',
                'description' => 'Khách sạn 3 sao với dịch vụ tốt và giá cả hợp lý',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_golden_1.jpg', 'hotels/hai_phong_golden_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-golden.com',
                'phone' => '0225 3956 444',
                'website' => 'https://www.hai-phong-golden.com',
            ],
            [
                'name' => 'Cat Ba Pearl Resort',
                'description' => 'Resort 4 sao với view biển và dịch vụ cao cấp',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_pearl_1.jpg', 'hotels/cat_ba_pearl_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-pearl.com',
                'phone' => '0225 3956 333',
                'website' => 'https://www.cat-ba-pearl.com',
            ],
            [
                'name' => 'Hai Phong Diamond Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và dịch vụ cao cấp',
                'address' => 'Đường Điện Biên Phủ, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_diamond_1.jpg', 'hotels/hai_phong_diamond_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-diamond.com',
                'phone' => '0225 3956 222',
                'website' => 'https://www.hai-phong-diamond.com',
            ],
            [
                'name' => 'Do Son Ocean Resort',
                'description' => 'Resort 3 sao với view biển và không gian thoáng đãng',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_ocean_resort_1.jpg', 'hotels/do_son_ocean_resort_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-ocean-resort.com',
                'phone' => '0225 3956 111',
                'website' => 'https://www.do-son-ocean-resort.com',
            ],
            [
                'name' => 'Hai Phong Emerald Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Lạch Tray, Quận Ngô Quyền, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_emerald_1.jpg', 'hotels/hai_phong_emerald_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-emerald.com',
                'phone' => '0225 3956 000',
                'website' => 'https://www.hai-phong-emerald.com',
            ],
            [
                'name' => 'Cat Ba Crystal Resort',
                'description' => 'Resort 3 sao với view biển trong xanh như pha lê',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'images' => json_encode(['hotels/cat_ba_crystal_1.jpg', 'hotels/cat_ba_crystal_2.jpg']),
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'email' => 'reservations@cat-ba-crystal.com',
                'phone' => '0225 3955 999',
                'website' => 'https://www.cat-ba-crystal.com',
            ],
            [
                'name' => 'Hai Phong Sapphire Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng như ngọc bích',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'images' => json_encode(['hotels/hai_phong_sapphire_1.jpg', 'hotels/hai_phong_sapphire_2.jpg']),
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'email' => 'reservations@hai-phong-sapphire.com',
                'phone' => '0225 3955 888',
                'website' => 'https://www.hai-phong-sapphire.com',
            ],
            [
                'name' => 'Do Son Ruby Resort',
                'description' => 'Resort 4 sao với thiết kế sang trọng như ngọc ruby',
                'address' => 'Đường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'images' => json_encode(['hotels/do_son_ruby_1.jpg', 'hotels/do_son_ruby_2.jpg']),
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'email' => 'reservations@do-son-ruby.com',
                'phone' => '0225 3955 777',
                'website' => 'https://www.do-son-ruby.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
