<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaiPhongRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Hải Sản Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi ngon với view sông Lạch Tray',
                'address' => 'Đường Lạch Tray, Quận Ngô Quyền, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.5,
                'price_range' => '200,000 - 800,000 VND',
                'image' => 'restaurants/hai_san_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Đa Cua Hải Phòng',
                'description' => 'Nhà hàng nổi tiếng với món bánh đa cua truyền thống Hải Phòng',
                'address' => 'Đường Điện Biên Phủ, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.4,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_da_cua_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Cá Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bún cá - đặc sản Hải Phòng',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.3,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/bun_ca_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh mì pate với pate tự làm đặc biệt',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '20,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_pate_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn với nhân thịt và nấm',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '40,000 - 100,000 VND',
                'image' => 'restaurants/banh_cuon_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Hải Phòng',
                'description' => 'Nhà hàng phục vụ phở với nước dùng ngọt thanh và thịt tươi',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '50,000 - 120,000 VND',
                'image' => 'restaurants/pho_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm với các món ăn kèm đa dạng',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '60,000 - 150,000 VND',
                'image' => 'restaurants/com_tam_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh mì với nhiều loại nhân và nước sốt đặc biệt',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '20,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Chè Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ các loại chè truyền thống và hiện đại',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/che_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh bèo với nước mắm đặc biệt',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_beo_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh bột lọc với nhân tôm thịt tươi ngon',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh nậm với lá chuối thơm',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_nam_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Ít Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh ít với nhân đậu xanh và dừa',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/banh_it_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bò Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh bò với hương vị đặc trưng',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '10,000 - 40,000 VND',
                'image' => 'restaurants/banh_bo_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Đúc Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh đúc với nước mắm và rau sống',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_duc_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Khọt Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh khọt với tôm tươi và nước mắm',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.3,
                'price_range' => '35,000 - 90,000 VND',
                'image' => 'restaurants/banh_khot_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Căn Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh căn với trứng cút và nước mắm',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_can_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Chén Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh bèo chén với nước mắm đặc biệt',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_beo_chen_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Lọc Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh lọc với nhân tôm thịt',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_loc_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Lá Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh nậm lá với nhân thịt và đậu xanh',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_nam_la_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Trần Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh bột lọc trần với nước mắm',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_tran_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Nậm Lọc Hải Phòng',
                'description' => 'Nhà hàng phục vụ combo bánh bèo, nậm, lọc truyền thống',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_beo_nam_loc_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng với nước sốt đặc biệt',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh mì chả cá với chả cá tươi ngon',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '30,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Hải Phòng 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì pate với pate tự làm',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_pate_hai_phong_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Xíu Mại Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh mì xíu mại với nước dùng đậm đà',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_mi_xiu_mai_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nguội Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nguội với rau sống',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_mi_thit_nguoi_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Lụa Hải Phòng',
                'description' => 'Nhà hàng phục vụ bánh mì chả lụa với chả lụa tự làm',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_cha_lua_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Xá Xíu Hải Phòng',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt xá xíu với nước sốt đặc biệt',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_xa_xiu_hai_phong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Hải Phòng 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng với nước sốt đặc biệt',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_hai_phong_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Hải Phòng 2',
                'description' => 'Nhà hàng phục vụ bánh mì chả cá với chả cá tươi ngon',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '30,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_hai_phong_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Hải Phòng 3',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì pate với pate tự làm',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_pate_hai_phong_3.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Xíu Mại Hải Phòng 2',
                'description' => 'Nhà hàng phục vụ bánh mì xíu mại với nước dùng đậm đà',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_mi_xiu_mai_hai_phong_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nguội Hải Phòng 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nguội với rau sống',
                'address' => 'Đường Nguyễn Văn Linh, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_mi_thit_nguoi_hai_phong_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Lụa Hải Phòng 2',
                'description' => 'Nhà hàng phục vụ bánh mì chả lụa với chả lụa tự làm',
                'address' => 'Đường Lê Duẩn, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.1,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_cha_lua_hai_phong_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Xá Xíu Hải Phòng 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt xá xíu với nước sốt đặc biệt',
                'address' => 'Đường Trần Phú, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_xa_xiu_hai_phong_2.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
