<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaLongHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'Vinpearl Resort & Spa Ha Long Bay',
                'description' => 'Resort 5 sao cao cấp với view vịnh Hạ Long tuyệt đẹp',
                'address' => 'Đảo Rều, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/vinpearl_ha_long_1.jpg', 'hotels/vinpearl_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@vinpearl-halong.com',
                'phone' => '0203 3848 888',
                'website' => 'https://www.vinpearl.com/ha-long',
            ],
            [
                'name' => 'Novotel Ha Long Bay',
                'description' => 'Khách sạn 4 sao với view vịnh Hạ Long và dịch vụ quốc tế',
                'address' => '160 Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/novotel_ha_long_1.jpg', 'hotels/novotel_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@novotel-halong.com',
                'phone' => '0203 3848 777',
                'website' => 'https://www.novotel.com/ha-long',
            ],
            [
                'name' => 'Royal Lotus Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng và view vịnh đẹp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/royal_lotus_ha_long_1.jpg', 'hotels/royal_lotus_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@royal-lotus-halong.com',
                'phone' => '0203 3848 666',
                'website' => 'https://www.royal-lotus-halong.com',
            ],
            [
                'name' => 'Muong Thanh Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với vị trí thuận tiện và dịch vụ tốt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/muong_thanh_ha_long_1.jpg', 'hotels/muong_thanh_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@muong-thanh-halong.com',
                'phone' => '0203 3848 555',
                'website' => 'https://www.muong-thanh-halong.com',
            ],
            [
                'name' => 'Saigon Ha Long Hotel',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm và giá cả hợp lý',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/saigon_ha_long_1.jpg', 'hotels/saigon_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@saigon-halong.com',
                'phone' => '0203 3848 444',
                'website' => 'https://www.saigon-halong.com',
            ],
            [
                'name' => 'Ha Long Bay Hotel',
                'description' => 'Khách sạn 3 sao với view vịnh Hạ Long đẹp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_bay_hotel_1.jpg', 'hotels/ha_long_bay_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-bay-hotel.com',
                'phone' => '0203 3848 333',
                'website' => 'https://www.halong-bay-hotel.com',
            ],
            [
                'name' => 'Dragon Pearl Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và view vịnh',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/dragon_pearl_ha_long_1.jpg', 'hotels/dragon_pearl_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@dragon-pearl-halong.com',
                'phone' => '0203 3848 222',
                'website' => 'https://www.dragon-pearl-halong.com',
            ],
            [
                'name' => 'Golden Bay Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với view vịnh vàng tuyệt đẹp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/golden_bay_ha_long_1.jpg', 'hotels/golden_bay_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@golden-bay-halong.com',
                'phone' => '0203 3848 111',
                'website' => 'https://www.golden-bay-halong.com',
            ],
            [
                'name' => 'Ha Long Pearl Hotel',
                'description' => 'Khách sạn 3 sao với dịch vụ tốt và giá cả hợp lý',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_pearl_hotel_1.jpg', 'hotels/ha_long_pearl_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-pearl-hotel.com',
                'phone' => '0203 3848 000',
                'website' => 'https://www.halong-pearl-hotel.com',
            ],
            [
                'name' => 'Emerald Bay Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với view vịnh ngọc lục bảo',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/emerald_bay_ha_long_1.jpg', 'hotels/emerald_bay_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@emerald-bay-halong.com',
                'phone' => '0203 3847 999',
                'website' => 'https://www.emerald-bay-halong.com',
            ],
            [
                'name' => 'Ha Long Central Hotel',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm thuận tiện',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_central_hotel_1.jpg', 'hotels/ha_long_central_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-central-hotel.com',
                'phone' => '0203 3847 888',
                'website' => 'https://www.halong-central-hotel.com',
            ],
            [
                'name' => 'Sapphire Bay Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với view vịnh ngọc bích',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/sapphire_bay_ha_long_1.jpg', 'hotels/sapphire_bay_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@sapphire-bay-halong.com',
                'phone' => '0203 3847 777',
                'website' => 'https://www.sapphire-bay-halong.com',
            ],
            [
                'name' => 'Ha Long Garden Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_garden_hotel_1.jpg', 'hotels/ha_long_garden_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-garden-hotel.com',
                'phone' => '0203 3847 666',
                'website' => 'https://www.halong-garden-hotel.com',
            ],
            [
                'name' => 'Ruby Bay Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với view vịnh ngọc ruby',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ruby_bay_ha_long_1.jpg', 'hotels/ruby_bay_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@ruby-bay-halong.com',
                'phone' => '0203 3847 555',
                'website' => 'https://www.ruby-bay-halong.com',
            ],
            [
                'name' => 'Ha Long Plaza Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm mua sắm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_plaza_hotel_1.jpg', 'hotels/ha_long_plaza_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-plaza-hotel.com',
                'phone' => '0203 3847 444',
                'website' => 'https://www.halong-plaza-hotel.com',
            ],
            [
                'name' => 'Diamond Bay Ha Long Hotel',
                'description' => 'Khách sạn 4 sao với view vịnh kim cương',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/diamond_bay_ha_long_1.jpg', 'hotels/diamond_bay_ha_long_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@diamond-bay-halong.com',
                'phone' => '0203 3847 333',
                'website' => 'https://www.diamond-bay-halong.com',
            ],
            [
                'name' => 'Ha Long Royal Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và dịch vụ cao cấp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_royal_hotel_1.jpg', 'hotels/ha_long_royal_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-royal-hotel.com',
                'phone' => '0203 3847 222',
                'website' => 'https://www.halong-royal-hotel.com',
            ],
            [
                'name' => 'Ha Long Sky Hotel',
                'description' => 'Khách sạn 4 sao với view toàn cảnh vịnh từ trên cao',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_sky_hotel_1.jpg', 'hotels/ha_long_sky_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-sky-hotel.com',
                'phone' => '0203 3847 111',
                'website' => 'https://www.halong-sky-hotel.com',
            ],
            [
                'name' => 'Ha Long Tower Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và view đẹp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_tower_hotel_1.jpg', 'hotels/ha_long_tower_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-tower-hotel.com',
                'phone' => '0203 3847 000',
                'website' => 'https://www.halong-tower-hotel.com',
            ],
            [
                'name' => 'Ha Long View Hotel',
                'description' => 'Khách sạn 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_view_hotel_1.jpg', 'hotels/ha_long_view_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-view-hotel.com',
                'phone' => '0203 3846 999',
                'website' => 'https://www.halong-view-hotel.com',
            ],
            [
                'name' => 'Ha Long Central Plaza Hotel',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_central_plaza_1.jpg', 'hotels/ha_long_central_plaza_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-central-plaza.com',
                'phone' => '0203 3846 888',
                'website' => 'https://www.halong-central-plaza.com',
            ],
            [
                'name' => 'Ha Long Beach Palace',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng và bãi biển đẹp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_beach_palace_1.jpg', 'hotels/ha_long_beach_palace_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-beach-palace.com',
                'phone' => '0203 3846 777',
                'website' => 'https://www.halong-beach-palace.com',
            ],
            [
                'name' => 'Ha Long Golden Hotel',
                'description' => 'Khách sạn 3 sao với dịch vụ tốt và giá cả hợp lý',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_golden_hotel_1.jpg', 'hotels/ha_long_golden_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-golden-hotel.com',
                'phone' => '0203 3846 666',
                'website' => 'https://www.halong-golden-hotel.com',
            ],
            [
                'name' => 'Ha Long Pearl Resort',
                'description' => 'Resort 4 sao với view vịnh và dịch vụ cao cấp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_pearl_resort_1.jpg', 'hotels/ha_long_pearl_resort_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-pearl-resort.com',
                'phone' => '0203 3846 555',
                'website' => 'https://www.halong-pearl-resort.com',
            ],
            [
                'name' => 'Ha Long Diamond Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và dịch vụ cao cấp',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_diamond_hotel_1.jpg', 'hotels/ha_long_diamond_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-diamond-hotel.com',
                'phone' => '0203 3846 444',
                'website' => 'https://www.halong-diamond-hotel.com',
            ],
            [
                'name' => 'Ha Long Ocean Resort',
                'description' => 'Resort 3 sao với view biển và không gian thoáng đãng',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_ocean_resort_1.jpg', 'hotels/ha_long_ocean_resort_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-ocean-resort.com',
                'phone' => '0203 3846 333',
                'website' => 'https://www.halong-ocean-resort.com',
            ],
            [
                'name' => 'Ha Long Emerald Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_emerald_hotel_1.jpg', 'hotels/ha_long_emerald_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-emerald-hotel.com',
                'phone' => '0203 3846 222',
                'website' => 'https://www.halong-emerald-hotel.com',
            ],
            [
                'name' => 'Ha Long Crystal Resort',
                'description' => 'Resort 3 sao với view vịnh trong xanh như pha lê',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_crystal_resort_1.jpg', 'hotels/ha_long_crystal_resort_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-crystal-resort.com',
                'phone' => '0203 3846 111',
                'website' => 'https://www.halong-crystal-resort.com',
            ],
            [
                'name' => 'Ha Long Sapphire Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng như ngọc bích',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_sapphire_hotel_1.jpg', 'hotels/ha_long_sapphire_hotel_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-sapphire-hotel.com',
                'phone' => '0203 3846 000',
                'website' => 'https://www.halong-sapphire-hotel.com',
            ],
            [
                'name' => 'Ha Long Ruby Resort',
                'description' => 'Resort 4 sao với thiết kế sang trọng như ngọc ruby',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'images' => json_encode(['hotels/ha_long_ruby_resort_1.jpg', 'hotels/ha_long_ruby_resort_2.jpg']),
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'email' => 'reservations@halong-ruby-resort.com',
                'phone' => '0203 3845 999',
                'website' => 'https://www.halong-ruby-resort.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
