<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaNoiCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        $haNoiLocationId = DB::table('locations')->where('name', 'Hà Nội')->value('id');
        
        if (!$haNoiLocationId) {
            $haNoiLocationId = DB::table('locations')->insertGetId([
                'name' => 'Hà Nội',
                'description' => 'Thủ đô Hà Nội - trung tâm chính trị, văn hóa, kinh tế của Việt Nam',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Văn Miếu - Quốc Tử Giám',
                'description' => 'Di tích lịch sử văn hóa quan trọng, trường đại học đầu tiên của Việt Nam',
                'address' => '58 Quốc Tử Giám, Đống Đa, Hà Nội',
                'latitude' => 21.0278,
                'longitude' => 105.8342,
                'image' => 'checkin/van_mieu.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/van_mieu_1.jpg', 'checkin/van_mieu_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Di tích lịch sử văn hóa nghìn năm',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Hoàn Kiếm',
                'description' => 'Hồ nước đẹp ở trung tâm Hà Nội với tháp Rùa và đền Ngọc Sơn',
                'address' => 'Hàng Trống, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'image' => 'checkin/ho_hoan_kiem.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/ho_hoan_kiem_1.jpg', 'checkin/ho_hoan_kiem_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Trái tim của Hà Nội',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố cổ Hà Nội',
                'description' => 'Khu phố cổ với 36 phố phường, nét đặc trưng của Hà Nội xưa',
                'address' => 'Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'image' => 'checkin/pho_co_ha_noi.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '23:00']]),
                'images' => json_encode(['checkin/pho_co_ha_noi_1.jpg', 'checkin/pho_co_ha_noi_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Nét đẹp cổ kính Hà Nội',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Lăng Chủ tịch Hồ Chí Minh',
                'description' => 'Nơi yên nghỉ của Chủ tịch Hồ Chí Minh, di tích lịch sử quan trọng',
                'address' => 'Hùng Vương, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'image' => 'checkin/lang_bac.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:30', 'close' => '16:30']]),
                'images' => json_encode(['checkin/lang_bac_1.jpg', 'checkin/lang_bac_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Nơi yên nghỉ của Bác Hồ',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Một Cột',
                'description' => 'Chùa có kiến trúc độc đáo hình hoa sen, biểu tượng của Hà Nội',
                'address' => 'Chùa Một Cột, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'image' => 'checkin/chua_mot_cot.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/chua_mot_cot_1.jpg', 'checkin/chua_mot_cot_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Kiến trúc độc đáo hình hoa sen',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Dân tộc học',
                'description' => 'Bảo tàng trưng bày văn hóa 54 dân tộc Việt Nam',
                'address' => 'Nguyễn Văn Huyên, Cầu Giấy, Hà Nội',
                'latitude' => 21.0408,
                'longitude' => 105.8000,
                'image' => 'checkin/bao_tang_dan_toc_hoc.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:30', 'close' => '17:30']]),
                'images' => json_encode(['checkin/bao_tang_dan_toc_hoc_1.jpg', 'checkin/bao_tang_dan_toc_hoc_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Văn hóa 54 dân tộc Việt Nam',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Tây',
                'description' => 'Hồ nước lớn nhất Hà Nội với cảnh đẹp và nhiều nhà hàng',
                'address' => 'Tây Hồ, Hà Nội',
                'latitude' => 21.0500,
                'longitude' => 105.8167,
                'image' => 'checkin/ho_tay.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/ho_tay_1.jpg', 'checkin/ho_tay_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hồ nước lớn nhất Hà Nội',
                'transport_options' => json_encode(['taxi', 'bus', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Trấn Quốc',
                'description' => 'Ngôi chùa cổ nhất Hà Nội nằm trên đảo giữa Hồ Tây',
                'address' => 'Đường Thanh Niên, Tây Hồ, Hà Nội',
                'latitude' => 21.0500,
                'longitude' => 105.8167,
                'image' => 'checkin/chua_tran_quoc.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/chua_tran_quoc_1.jpg', 'checkin/chua_tran_quoc_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Ngôi chùa cổ nhất Hà Nội',
                'transport_options' => json_encode(['taxi', 'bus', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Phụ nữ Việt Nam',
                'description' => 'Bảo tàng trưng bày lịch sử và văn hóa phụ nữ Việt Nam',
                'address' => '36 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'image' => 'checkin/bao_tang_phu_nu.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_phu_nu_1.jpg', 'checkin/bao_tang_phu_nu_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Lịch sử phụ nữ Việt Nam',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Nhà hát Lớn Hà Nội',
                'description' => 'Nhà hát với kiến trúc Pháp cổ điển, biểu diễn nghệ thuật',
                'address' => '1 Tràng Tiền, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'image' => 'checkin/nha_hat_lon.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/nha_hat_lon_1.jpg', 'checkin/nha_hat_lon_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Kiến trúc Pháp cổ điển',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Lịch sử Quân sự',
                'description' => 'Bảo tàng trưng bày lịch sử quân sự Việt Nam',
                'address' => '28A Điện Biên Phủ, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'image' => 'checkin/bao_tang_lich_su_quan_su.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_lich_su_quan_su_1.jpg', 'checkin/bao_tang_lich_su_quan_su_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Lịch sử quân sự Việt Nam',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Cột cờ Hà Nội',
                'description' => 'Cột cờ lịch sử trong khu vực Bảo tàng Lịch sử Quân sự',
                'address' => '28A Điện Biên Phủ, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'image' => 'checkin/cot_co_ha_noi.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/cot_co_ha_noi_1.jpg', 'checkin/cot_co_ha_noi_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cột cờ lịch sử Hà Nội',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Mỹ thuật Việt Nam',
                'description' => 'Bảo tàng trưng bày các tác phẩm mỹ thuật Việt Nam',
                'address' => '66 Nguyễn Thái Học, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'image' => 'checkin/bao_tang_my_thuat.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:30', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_my_thuat_1.jpg', 'checkin/bao_tang_my_thuat_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Nghệ thuật mỹ thuật Việt Nam',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Hương',
                'description' => 'Khu di tích chùa Hương với cảnh đẹp núi non và hang động',
                'address' => 'Hương Sơn, Mỹ Đức, Hà Nội',
                'latitude' => 20.6167,
                'longitude' => 105.7167,
                'image' => 'checkin/chua_huong.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 80000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/chua_huong_1.jpg', 'checkin/chua_huong_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cảnh đẹp núi non và hang động',
                'transport_options' => json_encode(['car', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng gốm Bát Tràng',
                'description' => 'Làng nghề truyền thống làm gốm sứ nổi tiếng',
                'address' => 'Bát Tràng, Gia Lâm, Hà Nội',
                'latitude' => 21.0333,
                'longitude' => 105.9333,
                'image' => 'checkin/lang_gom_bat_trang.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_gom_bat_trang_1.jpg', 'checkin/lang_gom_bat_trang_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng nghề gốm sứ truyền thống',
                'transport_options' => json_encode(['car', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng cổ Đường Lâm',
                'description' => 'Làng cổ với kiến trúc truyền thống và văn hóa dân gian',
                'address' => 'Đường Lâm, Sơn Tây, Hà Nội',
                'latitude' => 21.1333,
                'longitude' => 105.4833,
                'image' => 'checkin/lang_co_duong_lam.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_co_duong_lam_1.jpg', 'checkin/lang_co_duong_lam_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng cổ với kiến trúc truyền thống',
                'transport_options' => json_encode(['car', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn quốc gia Ba Vì',
                'description' => 'Vườn quốc gia với cảnh đẹp thiên nhiên và khí hậu mát mẻ',
                'address' => 'Ba Vì, Hà Nội',
                'latitude' => 21.0833,
                'longitude' => 105.4167,
                'image' => 'checkin/vuon_quoc_gia_ba_vi.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_quoc_gia_ba_vi_1.jpg', 'checkin/vuon_quoc_gia_ba_vi_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thiên nhiên hoang dã và khí hậu mát mẻ',
                'transport_options' => json_encode(['car', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Đồng Mô',
                'description' => 'Hồ nước đẹp với cảnh quan thiên nhiên và du lịch sinh thái',
                'address' => 'Sơn Tây, Hà Nội',
                'latitude' => 21.1333,
                'longitude' => 105.4833,
                'image' => 'checkin/ho_dong_mo.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ho_dong_mo_1.jpg', 'checkin/ho_dong_mo_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Du lịch sinh thái và nghỉ dưỡng',
                'transport_options' => json_encode(['car', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Thầy',
                'description' => 'Chùa cổ với kiến trúc độc đáo và cảnh đẹp núi non',
                'address' => 'Sài Sơn, Quốc Oai, Hà Nội',
                'latitude' => 20.9667,
                'longitude' => 105.6167,
                'image' => 'checkin/chua_thay.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/chua_thay_1.jpg', 'checkin/chua_thay_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Chùa cổ với kiến trúc độc đáo',
                'transport_options' => json_encode(['car', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng nghề Vạn Phúc',
                'description' => 'Làng nghề dệt lụa truyền thống nổi tiếng',
                'address' => 'Vạn Phúc, Hà Đông, Hà Nội',
                'latitude' => 20.9667,
                'longitude' => 105.7667,
                'image' => 'checkin/lang_nghe_van_phuc.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_nghe_van_phuc_1.jpg', 'checkin/lang_nghe_van_phuc_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng nghề dệt lụa truyền thống',
                'transport_options' => json_encode(['car', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Hà Nội',
                'description' => 'Bảo tàng trưng bày lịch sử và văn hóa Hà Nội',
                'address' => 'Phạm Hùng, Nam Từ Liêm, Hà Nội',
                'latitude' => 21.0167,
                'longitude' => 105.7833,
                'image' => 'checkin/bao_tang_ha_noi.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_ha_noi_1.jpg', 'checkin/bao_tang_ha_noi_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Lịch sử và văn hóa Hà Nội',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Thủ Lệ',
                'description' => 'Công viên với vườn thú và khu vui chơi giải trí',
                'address' => 'Cầu Giấy, Hà Nội',
                'latitude' => 21.0408,
                'longitude' => 105.8000,
                'image' => 'checkin/cong_vien_thu_le.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cong_vien_thu_le_1.jpg', 'checkin/cong_vien_thu_le_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Vườn thú và khu vui chơi giải trí',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Thiên nhiên Việt Nam',
                'description' => 'Bảo tàng trưng bày các mẫu vật thiên nhiên',
                'address' => '18 Hoàng Quốc Việt, Cầu Giấy, Hà Nội',
                'latitude' => 21.0408,
                'longitude' => 105.8000,
                'image' => 'checkin/bao_tang_thien_nhien.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:30', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_thien_nhien_1.jpg', 'checkin/bao_tang_thien_nhien_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thiên nhiên và đa dạng sinh học',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Yên Sở',
                'description' => 'Công viên lớn với không gian xanh và khu vui chơi',
                'address' => 'Yên Sở, Hoàng Mai, Hà Nội',
                'latitude' => 20.9667,
                'longitude' => 105.8500,
                'image' => 'checkin/cong_vien_yen_so.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cong_vien_yen_so_1.jpg', 'checkin/cong_vien_yen_so_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Không gian xanh và khu vui chơi',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Công an Nhân dân',
                'description' => 'Bảo tàng trưng bày lịch sử lực lượng công an',
                'address' => '66 Nguyễn Du, Hai Bà Trưng, Hà Nội',
                'latitude' => 21.0167,
                'longitude' => 105.8500,
                'image' => 'checkin/bao_tang_cong_an.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_cong_an_1.jpg', 'checkin/bao_tang_cong_an_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Lịch sử lực lượng công an',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Hồ Tây',
                'description' => 'Công viên ven Hồ Tây với cảnh đẹp và không gian thư giãn',
                'address' => 'Tây Hồ, Hà Nội',
                'latitude' => 21.0500,
                'longitude' => 105.8167,
                'image' => 'checkin/cong_vien_ho_tay.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cong_vien_ho_tay_1.jpg', 'checkin/cong_vien_ho_tay_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Không gian thư giãn ven hồ',
                'transport_options' => json_encode(['taxi', 'bus', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Chiến thắng B52',
                'description' => 'Bảo tàng trưng bày chiến thắng B52 trong chiến tranh',
                'address' => '157 Đội Cấn, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'image' => 'checkin/bao_tang_chien_thang_b52.jpg',
                'location_id' => $haNoiLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_chien_thang_b52_1.jpg', 'checkin/bao_tang_chien_thang_b52_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Chiến thắng B52 lịch sử',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
