<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaNoiRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Chả Cá Lã Vọng',
                'description' => 'Nhà hàng nổi tiếng với món chả cá truyền thống Hà Nội',
                'address' => '14 Chả Cá, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.5,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/cha_ca_la_vong.jpg',
            ],
            [
                'name' => 'Phở Gia Truyền Bát Đàn',
                'description' => 'Quán phở nổi tiếng với nước dùng đậm đà truyền thống',
                'address' => '49 Bát Đàn, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.4,
                'price_range' => '50,000 - 100,000 VND',
                'image' => 'restaurants/pho_bat_dan.jpg',
            ],
            [
                'name' => 'Bún Chả Hương Liên',
                'description' => 'Nhà hàng nổi tiếng với món bún chả Hà Nội',
                'address' => '24 Lê Văn Hưu, Hai Bà Trưng, Hà Nội',
                'latitude' => 21.0167,
                'longitude' => 105.8500,
                'rating' => 4.3,
                'price_range' => '80,000 - 150,000 VND',
                'image' => 'restaurants/bun_cha_huong_lien.jpg',
            ],
            [
                'name' => 'Nhà hàng Quán Ăn Ngon',
                'description' => 'Nhà hàng phục vụ các món ăn truyền thống Việt Nam',
                'address' => '18 Phan Bội Châu, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.2,
                'price_range' => '150,000 - 300,000 VND',
                'image' => 'restaurants/quan_an_ngon.jpg',
            ],
            [
                'name' => 'Nhà hàng La Verticale',
                'description' => 'Nhà hàng Pháp cao cấp với ẩm thực fusion',
                'address' => '19 Ngô Văn Sở, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.6,
                'price_range' => '500,000 - 1,500,000 VND',
                'image' => 'restaurants/la_verticale.jpg',
            ],
            [
                'name' => 'Nhà hàng Green Tangerine',
                'description' => 'Nhà hàng với ẩm thực Pháp-Việt trong không gian cổ kính',
                'address' => '48 Hàng Bè, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.4,
                'price_range' => '300,000 - 800,000 VND',
                'image' => 'restaurants/green_tangerine.jpg',
            ],
            [
                'name' => 'Nhà hàng Madame Hien',
                'description' => 'Nhà hàng ẩm thực Việt Nam truyền thống',
                'address' => '15 Chan Cam, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.3,
                'price_range' => '250,000 - 600,000 VND',
                'image' => 'restaurants/madame_hien.jpg',
            ],
            [
                'name' => 'Nhà hàng Essence Restaurant',
                'description' => 'Nhà hàng cao cấp với ẩm thực Việt Nam hiện đại',
                'address' => '22 Ta Hien, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.5,
                'price_range' => '400,000 - 1,000,000 VND',
                'image' => 'restaurants/essence_restaurant.jpg',
            ],
            [
                'name' => 'Nhà hàng Cau Go Vietnamese Cuisine',
                'description' => 'Nhà hàng với view Hồ Hoàn Kiếm và ẩm thực Việt Nam',
                'address' => '5th Floor, 111 Cau Go, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.4,
                'price_range' => '300,000 - 700,000 VND',
                'image' => 'restaurants/cau_go.jpg',
            ],
            [
                'name' => 'Nhà hàng Chim Sáo',
                'description' => 'Nhà hàng với ẩm thực miền Bắc truyền thống',
                'address' => '65 Ngo Si Lien, Đống Đa, Hà Nội',
                'latitude' => 21.0278,
                'longitude' => 105.8342,
                'rating' => 4.2,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/chim_sao.jpg',
            ],
            [
                'name' => 'Nhà hàng Sen Tây Hồ',
                'description' => 'Nhà hàng buffet với view Hồ Tây',
                'address' => '614 Lac Long Quan, Tây Hồ, Hà Nội',
                'latitude' => 21.0500,
                'longitude' => 105.8167,
                'rating' => 4.1,
                'price_range' => '400,000 - 800,000 VND',
                'image' => 'restaurants/sen_tay_ho.jpg',
            ],
            [
                'name' => 'Nhà hàng Hà Nội House',
                'description' => 'Nhà hàng với ẩm thực Hà Nội truyền thống',
                'address' => '47A Ly Quoc Su, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.3,
                'price_range' => '250,000 - 600,000 VND',
                'image' => 'restaurants/ha_noi_house.jpg',
            ],
            [
                'name' => 'Nhà hàng KOTO',
                'description' => 'Nhà hàng xã hội với ẩm thực Việt Nam và đào tạo nghề',
                'address' => '59 Van Mieu, Đống Đa, Hà Nội',
                'latitude' => 21.0278,
                'longitude' => 105.8342,
                'rating' => 4.2,
                'price_range' => '150,000 - 400,000 VND',
                'image' => 'restaurants/koto.jpg',
            ],
            [
                'name' => 'Nhà hàng The Hanoi Social Club',
                'description' => 'Quán cà phê và nhà hàng với không gian sáng tạo',
                'address' => '6 Hoi Vu, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.1,
                'price_range' => '100,000 - 300,000 VND',
                'image' => 'restaurants/hanoi_social_club.jpg',
            ],
            [
                'name' => 'Nhà hàng The Gourmet Corner',
                'description' => 'Nhà hàng cao cấp với ẩm thực quốc tế',
                'address' => 'Sofitel Legend Metropole Hanoi, 15 Ngo Quyen, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'rating' => 4.6,
                'price_range' => '600,000 - 1,500,000 VND',
                'image' => 'restaurants/gourmet_corner.jpg',
            ],
            [
                'name' => 'Nhà hàng Spices Garden',
                'description' => 'Nhà hàng với ẩm thực Việt Nam truyền thống',
                'address' => 'Sofitel Legend Metropole Hanoi, 15 Ngo Quyen, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'rating' => 4.5,
                'price_range' => '500,000 - 1,200,000 VND',
                'image' => 'restaurants/spices_garden.jpg',
            ],
            [
                'name' => 'Nhà hàng Le Beaulieu',
                'description' => 'Nhà hàng Pháp cao cấp với ẩm thực châu Âu',
                'address' => 'Sofitel Legend Metropole Hanoi, 15 Ngo Quyen, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'rating' => 4.7,
                'price_range' => '800,000 - 2,000,000 VND',
                'image' => 'restaurants/le_beaulieu.jpg',
            ],
            [
                'name' => 'Nhà hàng Angelina',
                'description' => 'Nhà hàng Ý với pizza và pasta truyền thống',
                'address' => '6 Hang Bai, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.2,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/angelina.jpg',
            ],
            [
                'name' => 'Nhà hàng Pizza 4P\'s',
                'description' => 'Nhà hàng pizza Nhật-Việt với nguyên liệu tươi ngon',
                'address' => '24 Ly Quoc Su, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.3,
                'price_range' => '250,000 - 600,000 VND',
                'image' => 'restaurants/pizza_4ps.jpg',
            ],
            [
                'name' => 'Nhà hàng Joma Bakery Café',
                'description' => 'Quán cà phê và bánh ngọt với không gian thoải mái',
                'address' => '22 Nha Chung, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.1,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/joma.jpg',
            ],
            [
                'name' => 'Nhà hàng Highlands Coffee',
                'description' => 'Chuỗi cà phê Việt Nam với không gian hiện đại',
                'address' => '1 Trang Tien, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'rating' => 4.0,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/highlands_coffee.jpg',
            ],
            [
                'name' => 'Nhà hàng The Coffee House',
                'description' => 'Chuỗi cà phê với không gian làm việc lý tưởng',
                'address' => '52 Ly Thai To, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.1,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/the_coffee_house.jpg',
            ],
            [
                'name' => 'Nhà hàng Cong Caphe',
                'description' => 'Chuỗi cà phê với phong cách retro Việt Nam',
                'address' => '116 Nguyen Thai Hoc, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'rating' => 4.2,
                'price_range' => '40,000 - 120,000 VND',
                'image' => 'restaurants/cong_caphe.jpg',
            ],
            [
                'name' => 'Nhà hàng Trill Rooftop Café',
                'description' => 'Quán cà phê rooftop với view toàn cảnh Hà Nội',
                'address' => 'Tầng 19, 1 Ba Trieu, Hai Bà Trưng, Hà Nội',
                'latitude' => 21.0167,
                'longitude' => 105.8500,
                'rating' => 4.3,
                'price_range' => '100,000 - 300,000 VND',
                'image' => 'restaurants/trill_rooftop.jpg',
            ],
            [
                'name' => 'Nhà hàng Skyline Hanoi',
                'description' => 'Nhà hàng rooftop với view Hồ Tây',
                'address' => 'Tầng 65, Lotte Center Hanoi, 54 Lieu Giai, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'rating' => 4.5,
                'price_range' => '500,000 - 1,500,000 VND',
                'image' => 'restaurants/skyline_hanoi.jpg',
            ],
            [
                'name' => 'Nhà hàng Summit Lounge',
                'description' => 'Lounge bar với view toàn cảnh Hà Nội',
                'address' => 'Tầng 20, Pan Pacific Hanoi, 1 Thanh Nien, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'rating' => 4.4,
                'price_range' => '300,000 - 800,000 VND',
                'image' => 'restaurants/summit_lounge.jpg',
            ],
            [
                'name' => 'Nhà hàng The Rooftop',
                'description' => 'Nhà hàng rooftop với ẩm thực quốc tế',
                'address' => 'Tầng 19, Pacific Place, 83B Ly Thuong Kiet, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.3,
                'price_range' => '400,000 - 1,000,000 VND',
                'image' => 'restaurants/the_rooftop.jpg',
            ],
            [
                'name' => 'Nhà hàng Cloud Nine',
                'description' => 'Nhà hàng rooftop với không gian sang trọng',
                'address' => 'Tầng 9, Hanoi Daewoo Hotel, 360 Kim Ma, Ba Đình, Hà Nội',
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'rating' => 4.4,
                'price_range' => '350,000 - 900,000 VND',
                'image' => 'restaurants/cloud_nine.jpg',
            ],
            [
                'name' => 'Nhà hàng The Oriental Jade',
                'description' => 'Nhà hàng với ẩm thực châu Á',
                'address' => 'Tầng 2, Sofitel Legend Metropole Hanoi, 15 Ngo Quyen, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'rating' => 4.5,
                'price_range' => '600,000 - 1,500,000 VND',
                'image' => 'restaurants/oriental_jade.jpg',
            ],
            [
                'name' => 'Nhà hàng The Red Bean',
                'description' => 'Nhà hàng với ẩm thực Việt Nam hiện đại',
                'address' => '94 Ma May, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.2,
                'price_range' => '250,000 - 600,000 VND',
                'image' => 'restaurants/the_red_bean.jpg',
            ],
            [
                'name' => 'Nhà hàng The Hanoi Press Club',
                'description' => 'Nhà hàng với ẩm thực quốc tế và không gian cổ điển',
                'address' => '59A Ly Thai To, Hoàn Kiếm, Hà Nội',
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'rating' => 4.3,
                'price_range' => '300,000 - 700,000 VND',
                'image' => 'restaurants/hanoi_press_club.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
