<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HCMCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        $hcmLocationId = DB::table('locations')->where('name', 'Hồ Chí Minh')->value('id');
        
        if (!$hcmLocationId) {
            $hcmLocationId = DB::table('locations')->insertGetId([
                'name' => 'Hồ Chí Minh',
                'description' => 'Thành phố Hồ Chí Minh - trung tâm kinh tế, văn hóa của Việt Nam',
                'latitude' => 10.8231,
                'longitude' => 106.6297,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Nhà Thờ Đức Bà Sài Gòn',
                'description' => 'Nhà thờ Công giáo nổi tiếng với kiến trúc Gothic tại trung tâm TP.HCM',
                'address' => '01 Công xã Paris, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7797,
                'longitude' => 106.6992,
                'image' => 'checkin/nha_tho_duc_ba.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/nha_tho_duc_ba_1.jpg', 'checkin/nha_tho_duc_ba_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Biểu tượng kiến trúc của Sài Gòn',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bưu Điện Trung Tâm Sài Gòn',
                'description' => 'Công trình kiến trúc Pháp cổ đẹp mắt tại trung tâm thành phố',
                'address' => '02 Công xã Paris, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7799,
                'longitude' => 106.6998,
                'image' => 'checkin/buu_dien_trung_tam.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '20:00']]),
                'images' => json_encode(['checkin/buu_dien_1.jpg', 'checkin/buu_dien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Kiến trúc Pháp cổ đẹp mắt',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Dinh Độc Lập',
                'description' => 'Di tích lịch sử quan trọng, nơi đánh dấu sự kết thúc chiến tranh Việt Nam',
                'address' => '135 Nam Kỳ Khởi Nghĩa, Bến Thành, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.6954,
                'image' => 'checkin/dinh_doc_lap.jpg',
                'location_id' => $hcmLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:30', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dinh_doc_lap_1.jpg', 'checkin/dinh_doc_lap_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Di tích lịch sử quan trọng',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Bến Thành',
                'description' => 'Chợ truyền thống nổi tiếng với nhiều mặt hàng đặc trưng Sài Gòn',
                'address' => 'Lê Lợi, Bến Thành, Quận 1, TP.HCM',
                'latitude' => 10.7720,
                'longitude' => 106.6983,
                'image' => 'checkin/cho_ben_thanh.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cho_ben_thanh_1.jpg', 'checkin/cho_ben_thanh_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chợ truyền thống nổi tiếng',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Đi Bộ Bùi Viện',
                'description' => 'Phố đi bộ sôi động với nhiều quán bar, nhà hàng và hoạt động giải trí',
                'address' => 'Bùi Viện, Phạm Ngũ Lão, Quận 1, TP.HCM',
                'latitude' => 10.7697,
                'longitude' => 106.6934,
                'image' => 'checkin/pho_di_bo_bui_vien.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '18:00', 'close' => '02:00']]),
                'images' => json_encode(['checkin/bui_vien_1.jpg', 'checkin/bui_vien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Phố đi bộ sôi động về đêm',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo Tàng Chứng Tích Chiến Tranh',
                'description' => 'Bảo tàng lưu giữ những chứng tích về chiến tranh Việt Nam',
                'address' => '28 Võ Văn Tần, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7797,
                'longitude' => 106.6922,
                'image' => 'checkin/bao_tang_chien_tranh.jpg',
                'location_id' => $hcmLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:30', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_1.jpg', 'checkin/bao_tang_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bảo tàng lịch sử quan trọng',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Landmark 81',
                'description' => 'Tòa nhà cao nhất Việt Nam với view toàn cảnh thành phố',
                'address' => 'Vinhomes Central Park, 720A Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
                'latitude' => 10.7951,
                'longitude' => 106.7219,
                'image' => 'checkin/landmark_81.jpg',
                'location_id' => $hcmLocationId,
                'price' => 200000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '09:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/landmark_1.jpg', 'checkin/landmark_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Tòa nhà cao nhất Việt Nam',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Tây (Đường Nguyễn Huệ)',
                'description' => 'Phố đi bộ sôi động với nhiều hoạt động văn hóa và giải trí',
                'address' => 'Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'image' => 'checkin/pho_nguyen_hue.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/nguyen_hue_1.jpg', 'checkin/nguyen_hue_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Phố đi bộ trung tâm',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Công Viên Tao Đàn',
                'description' => 'Công viên xanh mát với nhiều cây cổ thụ tại trung tâm thành phố',
                'address' => 'Nguyễn Thị Minh Khai, Bến Thành, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/cong_vien_tao_dan.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/tao_dan_1.jpg', 'checkin/tao_dan_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Công viên xanh mát trung tâm',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Nhà Hát Lớn TP.HCM',
                'description' => 'Nhà hát opera với kiến trúc Pháp cổ đẹp mắt',
                'address' => '07 Công Trường Lam Sơn, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'image' => 'checkin/nha_hat_lon.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/nha_hat_1.jpg', 'checkin/nha_hat_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Nhà hát opera kiến trúc Pháp',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo Tàng Mỹ Thuật TP.HCM',
                'description' => 'Bảo tàng trưng bày các tác phẩm mỹ thuật Việt Nam',
                'address' => '97A Phó Đức Chính, Nguyễn Thái Bình, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/bao_tang_my_thuat.jpg',
                'location_id' => $hcmLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '09:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/my_thuat_1.jpg', 'checkin/my_thuat_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bảo tàng mỹ thuật thành phố',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Ẩm Thực Vạn Thành',
                'description' => 'Khu ẩm thực đường phố nổi tiếng với nhiều món ăn đặc sắc',
                'address' => 'Vạn Thành, Phường 8, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/pho_am_thuc_van_thanh.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '17:00', 'close' => '02:00']]),
                'images' => json_encode(['checkin/van_thanh_1.jpg', 'checkin/van_thanh_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Khu ẩm thực đường phố sôi động',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Ánh Sao',
                'description' => 'Cây cầu đi bộ đẹp mắt với hệ thống ánh sáng LED',
                'address' => 'Phú Mỹ Hưng, Quận 7, TP.HCM',
                'latitude' => 10.7308,
                'longitude' => 106.7313,
                'image' => 'checkin/cau_anh_sao.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/cau_anh_sao_1.jpg', 'checkin/cau_anh_sao_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Cầu đi bộ đẹp mắt',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Suối Tiên',
                'description' => 'Khu du lịch sinh thái với nhiều trò chơi giải trí',
                'address' => '120 Xa lộ Hà Nội, Phường Tân Phú, Quận 9, TP.HCM',
                'latitude' => 10.8517,
                'longitude' => 106.8019,
                'image' => 'checkin/suoi_tien.jpg',
                'location_id' => $hcmLocationId,
                'price' => 180000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/suoi_tien_1.jpg', 'checkin/suoi_tien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Khu du lịch sinh thái nổi tiếng',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Đầm Sen',
                'description' => 'Công viên nước với nhiều trò chơi thú vị',
                'address' => '03 Hòa Bình, Phường 3, Quận 11, TP.HCM',
                'latitude' => 10.7633,
                'longitude' => 106.6433,
                'image' => 'checkin/dam_sen.jpg',
                'location_id' => $hcmLocationId,
                'price' => 150000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/dam_sen_1.jpg', 'checkin/dam_sen_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Công viên nước giải trí',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Đi Bộ Nguyễn Huệ',
                'description' => 'Phố đi bộ trung tâm với nhiều hoạt động văn hóa',
                'address' => 'Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'image' => 'checkin/pho_nguyen_hue_di_bo.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/nguyen_hue_di_bo_1.jpg', 'checkin/nguyen_hue_di_bo_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Phố đi bộ trung tâm sôi động',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo Tàng Lịch Sử TP.HCM',
                'description' => 'Bảo tàng trưng bày lịch sử Việt Nam và TP.HCM',
                'address' => '02 Nguyễn Bỉnh Khiêm, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/bao_tang_lich_su.jpg',
                'location_id' => $hcmLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lich_su_1.jpg', 'checkin/lich_su_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bảo tàng lịch sử thành phố',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Ẩm Thực Lê Văn Sỹ',
                'description' => 'Khu ẩm thực đường phố với nhiều món ăn ngon',
                'address' => 'Lê Văn Sỹ, Phường 10, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/pho_am_thuc_le_van_sy.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '17:00', 'close' => '02:00']]),
                'images' => json_encode(['checkin/le_van_sy_1.jpg', 'checkin/le_van_sy_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Khu ẩm thực đường phố',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công Viên 23/9',
                'description' => 'Công viên xanh mát tại trung tâm thành phố',
                'address' => 'Lê Lai, Bến Thành, Quận 1, TP.HCM',
                'latitude' => 10.7720,
                'longitude' => 106.6983,
                'image' => 'checkin/cong_vien_23_9.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/23_9_1.jpg', 'checkin/23_9_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Công viên trung tâm',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Đi Bộ Đồng Khởi',
                'description' => 'Phố đi bộ sang trọng với nhiều cửa hàng cao cấp',
                'address' => 'Đồng Khởi, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'image' => 'checkin/pho_dong_khoi.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dong_khoi_1.jpg', 'checkin/dong_khoi_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Phố đi bộ sang trọng',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo Tàng Dân Tộc Học',
                'description' => 'Bảo tàng trưng bày văn hóa các dân tộc Việt Nam',
                'address' => 'Nguyễn Văn Huyên, Nghĩa Đô, Cầu Giấy, Hà Nội',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/bao_tang_dan_toc.jpg',
                'location_id' => $hcmLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:30', 'close' => '17:30']]),
                'images' => json_encode(['checkin/dan_toc_1.jpg', 'checkin/dan_toc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bảo tàng văn hóa dân tộc',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Ẩm Thực Võ Thị Sáu',
                'description' => 'Khu ẩm thực đường phố với nhiều món ăn đặc sắc',
                'address' => 'Võ Thị Sáu, Phường 8, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/pho_am_thuc_vo_thi_sau.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '17:00', 'close' => '02:00']]),
                'images' => json_encode(['checkin/vo_thi_sau_1.jpg', 'checkin/vo_thi_sau_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Khu ẩm thực đường phố',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công Viên Gia Định',
                'description' => 'Công viên xanh mát với nhiều cây cổ thụ',
                'address' => 'Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/cong_vien_gia_dinh.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/gia_dinh_1.jpg', 'checkin/gia_dinh_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Công viên xanh mát',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Đi Bộ Lê Lợi',
                'description' => 'Phố đi bộ sôi động với nhiều hoạt động văn hóa',
                'address' => 'Lê Lợi, Bến Thành, Quận 1, TP.HCM',
                'latitude' => 10.7720,
                'longitude' => 106.6983,
                'image' => 'checkin/pho_le_loi.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/le_loi_1.jpg', 'checkin/le_loi_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Phố đi bộ sôi động',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo Tàng Phụ Nữ Nam Bộ',
                'description' => 'Bảo tàng trưng bày lịch sử phụ nữ Nam Bộ',
                'address' => '202 Võ Thị Sáu, Phường 7, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/bao_tang_phu_nu.jpg',
                'location_id' => $hcmLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/phu_nu_1.jpg', 'checkin/phu_nu_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bảo tàng phụ nữ Nam Bộ',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Ẩm Thực Nguyễn Thị Minh Khai',
                'description' => 'Khu ẩm thực đường phố với nhiều món ăn ngon',
                'address' => 'Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/pho_am_thuc_minh_khai.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '17:00', 'close' => '02:00']]),
                'images' => json_encode(['checkin/minh_khai_1.jpg', 'checkin/minh_khai_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Khu ẩm thực đường phố',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công Viên Lê Văn Tám',
                'description' => 'Công viên xanh mát với nhiều hoạt động giải trí',
                'address' => 'Võ Thị Sáu, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/cong_vien_le_van_tam.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/le_van_tam_1.jpg', 'checkin/le_van_tam_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Công viên giải trí',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Đi Bộ Trần Hưng Đạo',
                'description' => 'Phố đi bộ với nhiều cửa hàng và nhà hàng',
                'address' => 'Trần Hưng Đạo, Phường 6, Quận 5, TP.HCM',
                'latitude' => 10.7533,
                'longitude' => 106.6633,
                'image' => 'checkin/pho_tran_hung_dao.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/tran_hung_dao_1.jpg', 'checkin/tran_hung_dao_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Phố đi bộ sôi động',
                'transport_options' => json_encode(['walking', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo Tàng TP.HCM',
                'description' => 'Bảo tàng trưng bày lịch sử và văn hóa TP.HCM',
                'address' => '65 Lý Tự Trọng, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'image' => 'checkin/bao_tang_tphcm.jpg',
                'location_id' => $hcmLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/tphcm_1.jpg', 'checkin/tphcm_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bảo tàng thành phố',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Phố Ẩm Thực Nguyễn Tri Phương',
                'description' => 'Khu ẩm thực đường phố với nhiều món ăn đặc sắc',
                'address' => 'Nguyễn Tri Phương, Phường 10, Quận 5, TP.HCM',
                'latitude' => 10.7533,
                'longitude' => 106.6633,
                'image' => 'checkin/pho_am_thuc_nguyen_tri_phuong.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '17:00', 'close' => '02:00']]),
                'images' => json_encode(['checkin/nguyen_tri_phuong_1.jpg', 'checkin/nguyen_tri_phuong_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Khu ẩm thực đường phố',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công Viên Văn Lang',
                'description' => 'Công viên xanh mát với nhiều cây cổ thụ',
                'address' => 'Võ Văn Tần, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'image' => 'checkin/cong_vien_van_lang.jpg',
                'location_id' => $hcmLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/van_lang_1.jpg', 'checkin/van_lang_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Công viên xanh mát',
                'transport_options' => json_encode(['taxi', 'bus']),
                'status' => 'active',
            ]
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
