<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HCMRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Ngon',
                'description' => 'Nhà hàng phục vụ các món ăn truyền thống Việt Nam với không gian đẹp',
                'address' => '160 Pasteur, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7797,
                'longitude' => 106.7019,
                'rating' => 4.2,
                'price_range' => '100,000 - 300,000 VND',
                'image' => 'restaurants/nha_hang_ngon.jpg',
            ],
            [
                'name' => 'The Deck Saigon',
                'description' => 'Nhà hàng sang trọng bên sông Sài Gòn với view tuyệt đẹp',
                'address' => '38 Nguyễn Ư Dĩ, Thảo Điền, Quận 2, TP.HCM',
                'latitude' => 10.7969,
                'longitude' => 106.7328,
                'rating' => 4.7,
                'price_range' => '800,000 - 2,000,000 VND',
                'image' => 'restaurants/the_deck_saigon.jpg',
            ],
            [
                'name' => 'Quán Ăn Ngon Sài Gòn',
                'description' => 'Nhà hàng nổi tiếng với các món ăn Việt Nam đặc sắc',
                'address' => '160 Pasteur, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7797,
                'longitude' => 106.7019,
                'rating' => 4.3,
                'price_range' => '150,000 - 400,000 VND',
                'image' => 'restaurants/quan_an_ngon.jpg',
            ],
            [
                'name' => 'Nhà hàng Hội An',
                'description' => 'Nhà hàng chuyên về ẩm thực miền Trung với không gian cổ kính',
                'address' => '11 Lê Thánh Tôn, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 4.1,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/nha_hang_hoi_an.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở 24',
                'description' => 'Chuỗi nhà hàng phở nổi tiếng với hương vị đặc trưng',
                'address' => '65 Lê Lợi, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7720,
                'longitude' => 106.6983,
                'rating' => 3.8,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/pho_24.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Huế',
                'description' => 'Chuyên về món bún bò Huế đúng chuẩn xứ Huế',
                'address' => '17A Nguyễn Thị Minh Khai, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 4.0,
                'price_range' => '60,000 - 120,000 VND',
                'image' => 'restaurants/bun_bo_hue.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Sài Gòn',
                'description' => 'Nhà hàng chuyên về cơm tấm với nhiều món ăn đặc sắc',
                'address' => '84 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.9,
                'price_range' => '40,000 - 100,000 VND',
                'image' => 'restaurants/com_tam_saigon.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Biển Đông',
                'description' => 'Chuyên về hải sản tươi sống với không gian sang trọng',
                'address' => '234 Võ Văn Tần, Phường 5, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 4.4,
                'price_range' => '300,000 - 800,000 VND',
                'image' => 'restaurants/hai_san_bien_dong.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Dê',
                'description' => 'Chuyên về lẩu dê với hương vị đặc trưng',
                'address' => '123 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 4.2,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/lau_de.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Xèo',
                'description' => 'Chuyên về bánh xèo và các món ăn miền Tây',
                'address' => '46A Đinh Công Tráng, Tân Định, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.7,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/banh_xeo.jpg',
            ],
            [
                'name' => 'Nhà hàng Chả Cá Lã Vọng',
                'description' => 'Chuyên về chả cá với công thức gia truyền',
                'address' => '14 Nguyễn Thị Minh Khai, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 4.1,
                'price_range' => '150,000 - 350,000 VND',
                'image' => 'restaurants/cha_ca_la_vong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Chả Hà Nội',
                'description' => 'Chuyên về bún chả Hà Nội đúng chuẩn',
                'address' => '89 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.9,
                'price_range' => '70,000 - 150,000 VND',
                'image' => 'restaurants/bun_cha_ha_noi.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Hòa',
                'description' => 'Nhà hàng phở nổi tiếng với hương vị đặc trưng',
                'address' => '260C Pasteur, Phường 8, Quận 3, TP.HCM',
                'latitude' => 10.7797,
                'longitude' => 106.7019,
                'rating' => 4.0,
                'price_range' => '60,000 - 120,000 VND',
                'image' => 'restaurants/pho_hoa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn',
                'description' => 'Chuyên về bánh cuốn và các món ăn truyền thống',
                'address' => '14 Nguyễn Thị Minh Khai, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.8,
                'price_range' => '50,000 - 120,000 VND',
                'image' => 'restaurants/banh_cuon.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Riêu',
                'description' => 'Chuyên về bún riêu với hương vị đặc trưng',
                'address' => '67 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.7,
                'price_range' => '55,000 - 110,000 VND',
                'image' => 'restaurants/bun_rieu.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Niêu',
                'description' => 'Chuyên về cơm niêu với không gian dân dã',
                'address' => '45 Nguyễn Thị Minh Khai, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.9,
                'price_range' => '80,000 - 180,000 VND',
                'image' => 'restaurants/com_nieu.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì',
                'description' => 'Chuyên về bánh mì với nhiều loại nhân đặc sắc',
                'address' => '23 Lê Lợi, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7720,
                'longitude' => 106.6983,
                'rating' => 3.6,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi.jpg',
            ],
            [
                'name' => 'Nhà hàng Chè',
                'description' => 'Chuyên về các loại chè truyền thống Việt Nam',
                'address' => '78 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.8,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/che.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Flan',
                'description' => 'Chuyên về bánh flan và các món tráng miệng',
                'address' => '156 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.5,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_flan.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo',
                'description' => 'Chuyên về bánh bèo và các món ăn Huế',
                'address' => '34 Nguyễn Thị Minh Khai, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.9,
                'price_range' => '40,000 - 100,000 VND',
                'image' => 'restaurants/banh_beo.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc',
                'description' => 'Chuyên về bánh bột lọc và các món ăn miền Trung',
                'address' => '89 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.7,
                'price_range' => '35,000 - 90,000 VND',
                'image' => 'restaurants/banh_bot_loc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Đúc',
                'description' => 'Chuyên về bánh đúc và các món ăn dân dã',
                'address' => '123 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.6,
                'price_range' => '30,000 - 70,000 VND',
                'image' => 'restaurants/banh_duc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Tét',
                'description' => 'Chuyên về bánh tét và các món ăn miền Nam',
                'address' => '67 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.8,
                'price_range' => '45,000 - 100,000 VND',
                'image' => 'restaurants/banh_tet.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Chưng',
                'description' => 'Chuyên về bánh chưng và các món ăn truyền thống',
                'address' => '234 Võ Văn Tần, Phường 5, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.7,
                'price_range' => '40,000 - 90,000 VND',
                'image' => 'restaurants/banh_chung.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Giò',
                'description' => 'Chuyên về bánh giò và các món ăn sáng',
                'address' => '156 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.5,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_gio.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bò',
                'description' => 'Chuyên về bánh bò và các món bánh ngọt',
                'address' => '78 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.6,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_bo.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bông Lan',
                'description' => 'Chuyên về bánh bông lan và các loại bánh ngọt',
                'address' => '23 Lê Lợi, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7720,
                'longitude' => 106.6983,
                'rating' => 3.4,
                'price_range' => '15,000 - 40,000 VND',
                'image' => 'restaurants/banh_bong_lan.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Kem',
                'description' => 'Chuyên về bánh kem và các loại bánh sinh nhật',
                'address' => '45 Nguyễn Thị Minh Khai, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.8,
                'price_range' => '100,000 - 300,000 VND',
                'image' => 'restaurants/banh_kem.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Dẻo',
                'description' => 'Chuyên về bánh dẻo và các món bánh truyền thống',
                'address' => '34 Nguyễn Thị Minh Khai, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.7,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_deo.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Pía',
                'description' => 'Chuyên về bánh pía và các món bánh miền Tây',
                'address' => '89 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.6,
                'price_range' => '35,000 - 90,000 VND',
                'image' => 'restaurants/banh_pia.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bò Bông',
                'description' => 'Chuyên về bánh bò bông và các món bánh ngọt',
                'address' => '123 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM',
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'rating' => 3.5,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_bo_bong.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bò Nướng',
                'description' => 'Chuyên về bánh bò nướng và các món bánh truyền thống',
                'address' => '67 Nguyễn Huệ, Bến Nghé, Quận 1, TP.HCM',
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'rating' => 3.8,
                'price_range' => '30,000 - 70,000 VND',
                'image' => 'restaurants/banh_bo_nuong.jpg',
            ]
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
