<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KhanhHoaHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'InterContinental Nha Trang',
                'description' => 'Khách sạn 5 sao cao cấp với view biển tuyệt đẹp tại Nha Trang',
                'address' => '32-34 Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/intercontinental_nha_trang_1.jpg', 'hotels/intercontinental_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@intercontinental-nha-trang.com',
                'phone' => '0258 3887 777',
                'website' => 'https://www.intercontinental.com/nha-trang',
            ],
            [
                'name' => 'Sheraton Nha Trang Hotel & Spa',
                'description' => 'Khách sạn 5 sao với spa cao cấp và view biển đẹp',
                'address' => '26-28 Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/sheraton_nha_trang_1.jpg', 'hotels/sheraton_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@sheraton-nha-trang.com',
                'phone' => '0258 3888 888',
                'website' => 'https://www.sheraton-nha-trang.com',
            ],
            [
                'name' => 'Vinpearl Resort Nha Trang',
                'description' => 'Resort 5 sao với bãi biển riêng và dịch vụ cao cấp',
                'address' => 'Đảo Hòn Tre, Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/vinpearl_resort_nha_trang_1.jpg', 'hotels/vinpearl_resort_nha_trang_2.jpg']),
                'latitude' => 12.2333,
                'longitude' => 109.2000,
                'email' => 'reservations@vinpearl-nha-trang.com',
                'phone' => '0258 3889 999',
                'website' => 'https://www.vinpearl.com/nha-trang',
            ],
            [
                'name' => 'Novotel Nha Trang',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ tốt',
                'address' => '50 Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/novotel_nha_trang_1.jpg', 'hotels/novotel_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@novotel-nha-trang.com',
                'phone' => '0258 3886 666',
                'website' => 'https://www.novotel-nha-trang.com',
            ],
            [
                'name' => 'Mia Resort Nha Trang',
                'description' => 'Resort 4 sao với thiết kế hiện đại và bãi biển đẹp',
                'address' => 'Bãi biển Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/mia_resort_nha_trang_1.jpg', 'hotels/mia_resort_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@mia-nha-trang.com',
                'phone' => '0258 3885 555',
                'website' => 'https://www.mia-nha-trang.com',
            ],
            [
                'name' => 'Six Senses Ninh Van Bay',
                'description' => 'Resort 5 sao cao cấp với villa riêng biệt và view vịnh đẹp',
                'address' => 'Vịnh Ninh Vân, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/six_senses_ninh_van_1.jpg', 'hotels/six_senses_ninh_van_2.jpg']),
                'latitude' => 12.5000,
                'longitude' => 109.1667,
                'email' => 'reservations@sixsenses-ninhvan.com',
                'phone' => '0258 3884 444',
                'website' => 'https://www.sixsenses-ninhvan.com',
            ],
            [
                'name' => 'Amanoi Resort',
                'description' => 'Resort 5 sao cao cấp với không gian riêng tư và dịch vụ đẳng cấp',
                'address' => 'Vịnh Vân Phong, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/amanoi_resort_1.jpg', 'hotels/amanoi_resort_2.jpg']),
                'latitude' => 12.5000,
                'longitude' => 109.1667,
                'email' => 'reservations@amanoi.com',
                'phone' => '0258 3883 333',
                'website' => 'https://www.amanoi.com',
            ],
            [
                'name' => 'An Lam Retreats Ninh Van Bay',
                'description' => 'Resort 4 sao với thiết kế độc đáo và không gian yên tĩnh',
                'address' => 'Vịnh Ninh Vân, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/an_lam_ninh_van_1.jpg', 'hotels/an_lam_ninh_van_2.jpg']),
                'latitude' => 12.5000,
                'longitude' => 109.1667,
                'email' => 'reservations@anlam-ninhvan.com',
                'phone' => '0258 3882 222',
                'website' => 'https://www.anlam-ninhvan.com',
            ],
            [
                'name' => 'Nha Trang Beach Hotel',
                'description' => 'Khách sạn 3 sao với view biển và giá cả hợp lý',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_beach_1.jpg', 'hotels/nha_trang_beach_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-beach.com',
                'phone' => '0258 3881 111',
                'website' => 'https://www.nhatrang-beach.com',
            ],
            [
                'name' => 'Golden Peak Hotel Nha Trang',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và dịch vụ tốt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/golden_peak_nha_trang_1.jpg', 'hotels/golden_peak_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@goldenpeak-nhatrang.com',
                'phone' => '0258 3880 000',
                'website' => 'https://www.goldenpeak-nhatrang.com',
            ],
            [
                'name' => 'Liberty Central Nha Trang',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/liberty_central_nha_trang_1.jpg', 'hotels/liberty_central_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@liberty-nhatrang.com',
                'phone' => '0258 3879 999',
                'website' => 'https://www.liberty-nhatrang.com',
            ],
            [
                'name' => 'Rosaka Nha Trang Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế Nhật Bản và dịch vụ tốt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/rosaka_nha_trang_1.jpg', 'hotels/rosaka_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@rosaka-nhatrang.com',
                'phone' => '0258 3878 888',
                'website' => 'https://www.rosaka-nhatrang.com',
            ],
            [
                'name' => 'Nha Trang Lodge Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện và giá cả hợp lý',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_lodge_1.jpg', 'hotels/nha_trang_lodge_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-lodge.com',
                'phone' => '0258 3877 777',
                'website' => 'https://www.nhatrang-lodge.com',
            ],
            [
                'name' => 'Asia Paradise Hotel Nha Trang',
                'description' => 'Khách sạn 3 sao với view biển và không gian thoáng đãng',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/asia_paradise_nha_trang_1.jpg', 'hotels/asia_paradise_nha_trang_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@asiaparadise-nhatrang.com',
                'phone' => '0258 3876 666',
                'website' => 'https://www.asiaparadise-nhatrang.com',
            ],
            [
                'name' => 'Nha Trang Palace Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng và dịch vụ cao cấp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_palace_1.jpg', 'hotels/nha_trang_palace_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-palace.com',
                'phone' => '0258 3875 555',
                'website' => 'https://www.nhatrang-palace.com',
            ],
            [
                'name' => 'Nha Trang Bay Hotel',
                'description' => 'Khách sạn 3 sao với view vịnh Nha Trang đẹp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_bay_1.jpg', 'hotels/nha_trang_bay_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-bay.com',
                'phone' => '0258 3874 444',
                'website' => 'https://www.nhatrang-bay.com',
            ],
            [
                'name' => 'Nha Trang Ocean Hotel',
                'description' => 'Khách sạn 3 sao với view biển và không gian thoáng đãng',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_ocean_1.jpg', 'hotels/nha_trang_ocean_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-ocean.com',
                'phone' => '0258 3873 333',
                'website' => 'https://www.nhatrang-ocean.com',
            ],
            [
                'name' => 'Nha Trang View Hotel',
                'description' => 'Khách sạn 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_view_1.jpg', 'hotels/nha_trang_view_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-view.com',
                'phone' => '0258 3872 222',
                'website' => 'https://www.nhatrang-view.com',
            ],
            [
                'name' => 'Nha Trang Central Hotel',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm và dịch vụ tốt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_central_1.jpg', 'hotels/nha_trang_central_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-central.com',
                'phone' => '0258 3871 111',
                'website' => 'https://www.nhatrang-central.com',
            ],
            [
                'name' => 'Nha Trang Garden Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_garden_1.jpg', 'hotels/nha_trang_garden_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-garden.com',
                'phone' => '0258 3870 000',
                'website' => 'https://www.nhatrang-garden.com',
            ],
            [
                'name' => 'Nha Trang Plaza Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm mua sắm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_plaza_1.jpg', 'hotels/nha_trang_plaza_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-plaza.com',
                'phone' => '0258 3869 999',
                'website' => 'https://www.nhatrang-plaza.com',
            ],
            [
                'name' => 'Nha Trang Royal Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và dịch vụ cao cấp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_royal_1.jpg', 'hotels/nha_trang_royal_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-royal.com',
                'phone' => '0258 3868 888',
                'website' => 'https://www.nhatrang-royal.com',
            ],
            [
                'name' => 'Nha Trang Sky Hotel',
                'description' => 'Khách sạn 4 sao với view toàn cảnh thành phố từ trên cao',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_sky_1.jpg', 'hotels/nha_trang_sky_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-sky.com',
                'phone' => '0258 3867 777',
                'website' => 'https://www.nhatrang-sky.com',
            ],
            [
                'name' => 'Nha Trang Tower Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và view đẹp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_tower_1.jpg', 'hotels/nha_trang_tower_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-tower.com',
                'phone' => '0258 3866 666',
                'website' => 'https://www.nhatrang-tower.com',
            ],
            [
                'name' => 'Nha Trang View Hotel 2',
                'description' => 'Khách sạn 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_view_2_1.jpg', 'hotels/nha_trang_view_2_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-view2.com',
                'phone' => '0258 3865 555',
                'website' => 'https://www.nhatrang-view2.com',
            ],
            [
                'name' => 'Nha Trang Central Hotel 2',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm và dịch vụ tốt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_central_2_1.jpg', 'hotels/nha_trang_central_2_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-central2.com',
                'phone' => '0258 3864 444',
                'website' => 'https://www.nhatrang-central2.com',
            ],
            [
                'name' => 'Nha Trang Garden Hotel 2',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_garden_2_1.jpg', 'hotels/nha_trang_garden_2_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-garden2.com',
                'phone' => '0258 3863 333',
                'website' => 'https://www.nhatrang-garden2.com',
            ],
            [
                'name' => 'Nha Trang Plaza Hotel 2',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm mua sắm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_plaza_2_1.jpg', 'hotels/nha_trang_plaza_2_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-plaza2.com',
                'phone' => '0258 3862 222',
                'website' => 'https://www.nhatrang-plaza2.com',
            ],
            [
                'name' => 'Nha Trang Royal Hotel 2',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và dịch vụ cao cấp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_royal_2_1.jpg', 'hotels/nha_trang_royal_2_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-royal2.com',
                'phone' => '0258 3861 111',
                'website' => 'https://www.nhatrang-royal2.com',
            ],
            [
                'name' => 'Nha Trang Sky Hotel 2',
                'description' => 'Khách sạn 4 sao với view toàn cảnh thành phố từ trên cao',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'images' => json_encode(['hotels/nha_trang_sky_2_1.jpg', 'hotels/nha_trang_sky_2_2.jpg']),
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'email' => 'reservations@nhatrang-sky2.com',
                'phone' => '0258 3860 000',
                'website' => 'https://www.nhatrang-sky2.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
