<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KienGiangRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Hải Sản Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi ngon với view biển đẹp',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2333,
                'longitude' => 103.9500,
                'rating' => 4.5,
                'price_range' => '200,000 - 800,000 VND',
                'image' => 'restaurants/hai_san_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Nướng Phú Quốc',
                'description' => 'Nhà hàng chuyên các món nướng hải sản và thịt tươi ngon',
                'address' => 'Đường Trần Hưng Đạo, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2100,
                'longitude' => 103.9700,
                'rating' => 4.3,
                'price_range' => '150,000 - 500,000 VND',
                'image' => 'restaurants/nuong_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm và các món ăn miền Nam',
                'address' => 'Đường Nguyễn Trung Trực, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0167,
                'longitude' => 105.0833,
                'rating' => 4.2,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/com_tam_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi ngon với view biển Hà Tiên',
                'address' => 'Bãi biển Hà Tiên, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3833,
                'longitude' => 104.4833,
                'rating' => 4.4,
                'price_range' => '180,000 - 600,000 VND',
                'image' => 'restaurants/hai_san_ha_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Hải Sản Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ lẩu hải sản tươi ngon',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2300,
                'longitude' => 103.9520,
                'rating' => 4.3,
                'price_range' => '250,000 - 700,000 VND',
                'image' => 'restaurants/lau_hai_san_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Nước Lèo Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ bún nước lèo và các món ăn địa phương',
                'address' => 'Đường Nguyễn Huệ, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0180,
                'longitude' => 105.0850,
                'rating' => 4.1,
                'price_range' => '40,000 - 120,000 VND',
                'image' => 'restaurants/bun_nuoc_leo_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Gỏi Cá Trích Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ gỏi cá trích và các món ăn đặc sản',
                'address' => 'Đường Trần Hưng Đạo, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2120,
                'longitude' => 103.9680,
                'rating' => 4.4,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/goi_ca_trich_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Niêu Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ cơm niêu và các món ăn truyền thống',
                'address' => 'Đường Bạch Đằng, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3850,
                'longitude' => 104.4850,
                'rating' => 4.2,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/com_nieu_ha_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng BBQ Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ BBQ hải sản và thịt tươi ngon',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2200,
                'longitude' => 103.9600,
                'rating' => 4.3,
                'price_range' => '200,000 - 600,000 VND',
                'image' => 'restaurants/bbq_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Cá Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ bún cá và các món ăn từ cá tươi',
                'address' => 'Đường Lê Lợi, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0200,
                'longitude' => 105.0820,
                'rating' => 4.0,
                'price_range' => '45,000 - 130,000 VND',
                'image' => 'restaurants/bun_ca_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Nướng Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ hải sản nướng tươi ngon',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2280,
                'longitude' => 103.9540,
                'rating' => 4.4,
                'price_range' => '180,000 - 500,000 VND',
                'image' => 'restaurants/hai_san_nuong_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Gà Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ cơm gà và các món ăn từ gà',
                'address' => 'Đường Phan Chu Trinh, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3870,
                'longitude' => 104.4830,
                'rating' => 4.1,
                'price_range' => '70,000 - 160,000 VND',
                'image' => 'restaurants/com_ga_ha_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Dê Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ lẩu dê và các món ăn từ dê',
                'address' => 'Đường Trần Hưng Đạo, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2140,
                'longitude' => 103.9660,
                'rating' => 4.2,
                'price_range' => '200,000 - 400,000 VND',
                'image' => 'restaurants/lau_de_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ bún bò và các món ăn Huế',
                'address' => 'Đường Trần Phú, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0220,
                'longitude' => 105.0840,
                'rating' => 4.0,
                'price_range' => '50,000 - 140,000 VND',
                'image' => 'restaurants/bun_bo_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Tươi Sống Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi sống và sashimi',
                'address' => 'Bãi Khem, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2167,
                'longitude' => 103.9667,
                'rating' => 4.5,
                'price_range' => '300,000 - 1,000,000 VND',
                'image' => 'restaurants/hai_san_tuoi_song_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Sườn Nướng Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm sườn nướng và các món ăn miền Nam',
                'address' => 'Đường Bạch Đằng, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3890,
                'longitude' => 104.4810,
                'rating' => 4.1,
                'price_range' => '60,000 - 150,000 VND',
                'image' => 'restaurants/com_tam_suon_nuong_ha_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Cua Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ lẩu cua và các món ăn từ cua',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2240,
                'longitude' => 103.9560,
                'rating' => 4.3,
                'price_range' => '250,000 - 600,000 VND',
                'image' => 'restaurants/lau_cua_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Riêu Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ bún riêu và các món ăn truyền thống',
                'address' => 'Đường Nguyễn Trung Trực, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0240,
                'longitude' => 105.0860,
                'rating' => 4.0,
                'price_range' => '45,000 - 120,000 VND',
                'image' => 'restaurants/bun_rieu_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Nướng Muối Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ hải sản nướng muối đặc biệt',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2180,
                'longitude' => 103.9620,
                'rating' => 4.4,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/hai_san_nuong_muoi_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Niêu Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ cơm niêu và các món ăn truyền thống',
                'address' => 'Đường Lê Lợi, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0260,
                'longitude' => 105.0800,
                'rating' => 4.1,
                'price_range' => '55,000 - 140,000 VND',
                'image' => 'restaurants/com_nieu_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Hải Sản Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ lẩu hải sản tươi ngon',
                'address' => 'Bãi biển Hà Tiên, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3910,
                'longitude' => 104.4790,
                'rating' => 4.2,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/lau_hai_san_ha_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Chả Cá Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ bún chả cá và các món ăn từ cá',
                'address' => 'Đường Trần Hưng Đạo, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2160,
                'longitude' => 103.9640,
                'rating' => 4.3,
                'price_range' => '80,000 - 180,000 VND',
                'image' => 'restaurants/bun_cha_ca_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Gà Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ cơm gà và các món ăn từ gà',
                'address' => 'Đường Nguyễn Huệ, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0280,
                'longitude' => 105.0820,
                'rating' => 4.0,
                'price_range' => '65,000 - 150,000 VND',
                'image' => 'restaurants/com_ga_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Nướng Lá Chuối Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ hải sản nướng lá chuối đặc biệt',
                'address' => 'Đường Phan Chu Trinh, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3930,
                'longitude' => 104.4770,
                'rating' => 4.3,
                'price_range' => '180,000 - 450,000 VND',
                'image' => 'restaurants/hai_san_nuong_la_chuoi_ha_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Bò Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ lẩu bò và các món ăn từ bò',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2260,
                'longitude' => 103.9520,
                'rating' => 4.2,
                'price_range' => '220,000 - 500,000 VND',
                'image' => 'restaurants/lau_bo_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Mắm Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ bún mắm và các món ăn đặc sản miền Tây',
                'address' => 'Đường Trần Phú, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0300,
                'longitude' => 105.0800,
                'rating' => 4.1,
                'price_range' => '50,000 - 130,000 VND',
                'image' => 'restaurants/bun_mam_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Nướng Than Hoa Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ hải sản nướng than hoa tươi ngon',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2220,
                'longitude' => 103.9580,
                'rating' => 4.4,
                'price_range' => '200,000 - 550,000 VND',
                'image' => 'restaurants/hai_san_nuong_than_hoa_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Sườn Bì Chả Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm sườn bì chả và các món ăn miền Nam',
                'address' => 'Đường Bạch Đằng, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3950,
                'longitude' => 104.4750,
                'rating' => 4.0,
                'price_range' => '70,000 - 160,000 VND',
                'image' => 'restaurants/com_tam_suon_bi_cha_ha_tien.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Gà Phú Quốc',
                'description' => 'Nhà hàng chuyên phục vụ lẩu gà và các món ăn từ gà',
                'address' => 'Đường Trần Hưng Đạo, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2180,
                'longitude' => 103.9600,
                'rating' => 4.1,
                'price_range' => '180,000 - 350,000 VND',
                'image' => 'restaurants/lau_ga_phu_quoc.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Cá Lóc Rạch Giá',
                'description' => 'Nhà hàng chuyên phục vụ bún cá lóc và các món ăn từ cá lóc',
                'address' => 'Đường Nguyễn Trung Trực, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0320,
                'longitude' => 105.0780,
                'rating' => 4.2,
                'price_range' => '55,000 - 140,000 VND',
                'image' => 'restaurants/bun_ca_loc_rach_gia.jpg',
            ],
            [
                'name' => 'Nhà hàng Hải Sản Nướng Giấy Bạc Hà Tiên',
                'description' => 'Nhà hàng chuyên phục vụ hải sản nướng giấy bạc đặc biệt',
                'address' => 'Bãi biển Hà Tiên, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3970,
                'longitude' => 104.4730,
                'rating' => 4.3,
                'price_range' => '190,000 - 480,000 VND',
                'image' => 'restaurants/hai_san_nuong_giay_bac_ha_tien.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
