<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KienGiangCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        // Kiểm tra và tạo location Kiên Giang nếu chưa có
        $kienGiangLocationId = DB::table('locations')->where('name', 'Kiên Giang')->value('id');

        if (!$kienGiangLocationId) {
            $kienGiangLocationId = DB::table('locations')->insertGetId([
                'name' => 'Kiên Giang',
                'description' => 'Tỉnh Kiên Giang - vùng đất của đảo ngọc Phú Quốc và nhiều điểm du lịch hấp dẫn',
                'latitude' => 10.0167,
                'longitude' => 105.0833,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Bãi Trường Phú Quốc',
                'description' => 'Bãi biển dài nhất Phú Quốc với cát trắng mịn và nước biển trong xanh',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2333,
                'longitude' => 103.9500,
                'image' => 'checkin/bai_truong_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_truong_phu_quoc_1.jpg', 'checkin/bai_truong_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển đẹp nhất Phú Quốc',
                'transport_options' => json_encode(['car', 'motorbike', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Khem Phú Quốc',
                'description' => 'Bãi biển hoang sơ với view núi và không gian yên tĩnh',
                'address' => 'Bãi Khem, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2167,
                'longitude' => 103.9667,
                'image' => 'checkin/bai_khem_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_khem_phu_quoc_1.jpg', 'checkin/bai_khem_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển hoang sơ tuyệt đẹp',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Ông Lang Phú Quốc',
                'description' => 'Bãi biển nhỏ xinh với view hoàng hôn tuyệt đẹp',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2200,
                'longitude' => 103.9600,
                'image' => 'checkin/bai_ong_lang_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_ong_lang_phu_quoc_1.jpg', 'checkin/bai_ong_lang_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển lãng mạn cho cặp đôi',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Sao Phú Quốc',
                'description' => 'Bãi biển hình lưỡi liềm với cát trắng mịn như bột',
                'address' => 'Bãi Sao, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2100,
                'longitude' => 103.9700,
                'image' => 'checkin/bai_sao_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_sao_phu_quoc_1.jpg', 'checkin/bai_sao_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển đẹp như tranh vẽ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Dài Phú Quốc',
                'description' => 'Bãi biển dài với view núi và không gian rộng rãi',
                'address' => 'Bãi Dài, Xã Gành Dầu, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2000,
                'longitude' => 103.9800,
                'image' => 'checkin/bai_dai_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_dai_phu_quoc_1.jpg', 'checkin/bai_dai_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển dài nhất đảo ngọc',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Hà Tiên',
                'description' => 'Bãi biển đẹp với view núi và không gian yên tĩnh',
                'address' => 'Bãi biển Hà Tiên, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3833,
                'longitude' => 104.4833,
                'image' => 'checkin/bai_bien_ha_tien.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_ha_tien_1.jpg', 'checkin/bai_bien_ha_tien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển đẹp của Hà Tiên',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Đá Dựng Hà Tiên',
                'description' => 'Núi đá vôi với view toàn cảnh vịnh Hà Tiên',
                'address' => 'Núi Đá Dựng, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3850,
                'longitude' => 104.4850,
                'image' => 'checkin/nui_da_dung_ha_tien.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/nui_da_dung_ha_tien_1.jpg', 'checkin/nui_da_dung_ha_tien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Điểm ngắm cảnh đẹp nhất Hà Tiên',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Hang Hà Tiên',
                'description' => 'Ngôi chùa cổ trong hang đá với kiến trúc độc đáo',
                'address' => 'Chùa Hang, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3870,
                'longitude' => 104.4830,
                'image' => 'checkin/chua_hang_ha_tien.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_hang_ha_tien_1.jpg', 'checkin/chua_hang_ha_tien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Di tích lịch sử văn hóa quan trọng',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Mũi Nai Hà Tiên',
                'description' => 'Mũi đất nhô ra biển với view hoàng hôn tuyệt đẹp',
                'address' => 'Mũi Nai, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3890,
                'longitude' => 104.4810,
                'image' => 'checkin/mui_nai_ha_tien.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/mui_nai_ha_tien_1.jpg', 'checkin/mui_nai_ha_tien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Điểm ngắm hoàng hôn đẹp nhất',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Đêm Phú Quốc',
                'description' => 'Chợ đêm sôi động với nhiều món ăn đặc sản',
                'address' => 'Đường Trần Hưng Đạo, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2100,
                'longitude' => 103.9700,
                'image' => 'checkin/cho_dem_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '17:00', 'close' => '23:00']]),
                'images' => json_encode(['checkin/cho_dem_phu_quoc_1.jpg', 'checkin/cho_dem_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Thiên đường ẩm thực về đêm',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Cảng An Thới Phú Quốc',
                'description' => 'Cảng biển với view đảo và thuyền đánh cá',
                'address' => 'Cảng An Thới, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2167,
                'longitude' => 103.9667,
                'image' => 'checkin/cang_an_thoi_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cang_an_thoi_phu_quoc_1.jpg', 'checkin/cang_an_thoi_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Cảng biển sầm uất',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Sư Muôn Rạch Giá',
                'description' => 'Ngôi chùa cổ với kiến trúc Khmer độc đáo',
                'address' => 'Chùa Sư Muôn, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0167,
                'longitude' => 105.0833,
                'image' => 'checkin/chua_su_muon_rach_gia.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_su_muon_rach_gia_1.jpg', 'checkin/chua_su_muon_rach_gia_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Di tích văn hóa Khmer',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Tàu Rạch Giá',
                'description' => 'Bến tàu với view sông và thuyền bè tấp nập',
                'address' => 'Bến Tàu Rạch Giá, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0180,
                'longitude' => 105.0850,
                'image' => 'checkin/ben_tau_rach_gia.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/ben_tau_rach_gia_1.jpg', 'checkin/ben_tau_rach_gia_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Cửa ngõ giao thương',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Hà Tiên',
                'description' => 'Công viên xanh mát với nhiều cây cối và không gian giải trí',
                'address' => 'Công viên Hà Tiên, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3850,
                'longitude' => 104.4850,
                'image' => 'checkin/cong_vien_ha_tien.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cong_vien_ha_tien_1.jpg', 'checkin/cong_vien_ha_tien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Không gian xanh giữa lòng thành phố',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Tre Phú Quốc',
                'description' => 'Đảo nhỏ với bãi biển hoang sơ và view tuyệt đẹp',
                'address' => 'Đảo Hòn Tre, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2200,
                'longitude' => 103.9600,
                'image' => 'checkin/dao_hon_tre_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 100000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_tre_phu_quoc_1.jpg', 'checkin/dao_hon_tre_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Đảo ngọc nhỏ xinh',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Suối Tranh Phú Quốc',
                'description' => 'Suối nước ngọt với thác nước đẹp và không gian mát mẻ',
                'address' => 'Suối Tranh, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2180,
                'longitude' => 103.9620,
                'image' => 'checkin/suoi_tranh_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/suoi_tranh_phu_quoc_1.jpg', 'checkin/suoi_tranh_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Suối nước ngọt mát mẻ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Chúa Hà Tiên',
                'description' => 'Núi đá vôi với view toàn cảnh vịnh Hà Tiên',
                'address' => 'Núi Chúa, TP. Hà Tiên, Tỉnh Kiên Giang',
                'latitude' => 10.3870,
                'longitude' => 104.4830,
                'image' => 'checkin/nui_chua_ha_tien.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/nui_chua_ha_tien_1.jpg', 'checkin/nui_chua_ha_tien_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Điểm ngắm cảnh cao nhất',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Rạch Giá',
                'description' => 'Chợ truyền thống với nhiều sản vật địa phương',
                'address' => 'Chợ Rạch Giá, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0200,
                'longitude' => 105.0820,
                'image' => 'checkin/cho_rach_gia.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cho_rach_gia_1.jpg', 'checkin/cho_rach_gia_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Trung tâm thương mại sầm uất',
                'transport_options' => json_encode(['car', 'motorbike', 'bus', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Dứa Phú Quốc',
                'description' => 'Bãi biển nhỏ với cát trắng và nước biển trong xanh',
                'address' => 'Bãi Dứa, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2140,
                'longitude' => 103.9680,
                'image' => 'checkin/bai_dua_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_dua_phu_quoc_1.jpg', 'checkin/bai_dua_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển yên tĩnh cho gia đình',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Mây Rút',
                'description' => 'Đảo nhỏ với bãi biển hoang sơ và view tuyệt đẹp',
                'address' => 'Đảo Hòn Mây Rút, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2160,
                'longitude' => 103.9640,
                'image' => 'checkin/dao_hon_may_rut_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 80000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_may_rut_phu_quoc_1.jpg', 'checkin/dao_hon_may_rut_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Đảo hoang sơ tuyệt đẹp',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Suối Đá Bàn Phú Quốc',
                'description' => 'Suối nước ngọt với đá bàn tự nhiên và không gian mát mẻ',
                'address' => 'Suối Đá Bàn, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2220,
                'longitude' => 103.9580,
                'image' => 'checkin/suoi_da_ban_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/suoi_da_ban_phu_quoc_1.jpg', 'checkin/suoi_da_ban_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Suối đá bàn độc đáo',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Vòng Phú Quốc',
                'description' => 'Bãi biển hình vòng cung với cát trắng mịn',
                'address' => 'Bãi Vòng, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2120,
                'longitude' => 103.9660,
                'image' => 'checkin/bai_vong_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_vong_phu_quoc_1.jpg', 'checkin/bai_vong_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển hình vòng cung đẹp',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Tam Bảo Rạch Giá',
                'description' => 'Ngôi chùa cổ với kiến trúc đẹp và không gian thanh tịnh',
                'address' => 'Chùa Tam Bảo, TP. Rạch Giá, Tỉnh Kiên Giang',
                'latitude' => 10.0240,
                'longitude' => 105.0860,
                'image' => 'checkin/chua_tam_bao_rach_gia.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_tam_bao_rach_gia_1.jpg', 'checkin/chua_tam_bao_rach_gia_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Di tích văn hóa tâm linh',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Gành Dầu Phú Quốc',
                'description' => 'Bãi biển phía Bắc với view Campuchia và không gian yên tĩnh',
                'address' => 'Bãi Gành Dầu, Xã Gành Dầu, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2000,
                'longitude' => 103.9800,
                'image' => 'checkin/bai_ganh_dau_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_ganh_dau_phu_quoc_1.jpg', 'checkin/bai_ganh_dau_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển phía Bắc đảo ngọc',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Thơm Phú Quốc',
                'description' => 'Đảo lớn với nhiều bãi biển đẹp và resort cao cấp',
                'address' => 'Đảo Hòn Thơm, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2260,
                'longitude' => 103.9520,
                'image' => 'checkin/dao_hon_thom_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 150000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_thom_phu_quoc_1.jpg', 'checkin/dao_hon_thom_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Đảo resort cao cấp',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Suối Tiên Phú Quốc',
                'description' => 'Suối nước ngọt với thác nước đẹp và không gian mát mẻ',
                'address' => 'Suối Tiên, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2240,
                'longitude' => 103.9560,
                'image' => 'checkin/suoi_tien_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 60000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/suoi_tien_phu_quoc_1.jpg', 'checkin/suoi_tien_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Suối tiên mát mẻ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi Cửa Cạn Phú Quốc',
                'description' => 'Bãi biển nhỏ với cát trắng và nước biển trong xanh',
                'address' => 'Bãi Cửa Cạn, Xã Cửa Cạn, TP. Phú Quốc, Tỉnh Kiên Giang',
                'latitude' => 10.2280,
                'longitude' => 103.9540,
                'image' => 'checkin/bai_cua_can_phu_quoc.jpg',
                'location_id' => $kienGiangLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_cua_can_phu_quoc_1.jpg', 'checkin/bai_cua_can_phu_quoc_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bãi biển yên tĩnh cho gia đình',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
