<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KienGiangHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'JW Marriott Phu Quoc Emerald Bay Resort & Spa',
                'description' => 'Resort 5 sao cao cấp với thiết kế độc đáo và dịch vụ sang trọng',
                'address' => 'Bãi Khem, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/jw_marriott_phu_quoc_1.jpg', 'hotels/jw_marriott_phu_quoc_2.jpg']),
                'latitude' => 10.2167,
                'longitude' => 103.9667,
                'email' => 'reservations@jwmarriott-phuquoc.com',
                'phone' => '0297 3779 999',
                'website' => 'https://www.marriott.com/phuquoc',
            ],
            [
                'name' => 'Vinpearl Resort & Spa Phu Quoc',
                'description' => 'Resort 5 sao với view biển tuyệt đẹp và dịch vụ cao cấp',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/vinpearl_phu_quoc_1.jpg', 'hotels/vinpearl_phu_quoc_2.jpg']),
                'latitude' => 10.2333,
                'longitude' => 103.9500,
                'email' => 'reservations@vinpearl-phuquoc.com',
                'phone' => '0297 3777 777',
                'website' => 'https://www.vinpearl.com/phu-quoc',
            ],
            [
                'name' => 'InterContinental Phu Quoc Long Beach Resort',
                'description' => 'Resort 5 sao quốc tế với view biển dài và dịch vụ đẳng cấp',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/intercontinental_phu_quoc_1.jpg', 'hotels/intercontinental_phu_quoc_2.jpg']),
                'latitude' => 10.2400,
                'longitude' => 103.9450,
                'email' => 'reservations@intercontinental-phuquoc.com',
                'phone' => '0297 3778 888',
                'website' => 'https://www.intercontinental.com/phu-quoc',
            ],
            [
                'name' => 'Novotel Phu Quoc Resort',
                'description' => 'Resort 4 sao với thiết kế hiện đại và dịch vụ chất lượng',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/novotel_phu_quoc_1.jpg', 'hotels/novotel_phu_quoc_2.jpg']),
                'latitude' => 10.2350,
                'longitude' => 103.9480,
                'email' => 'reservations@novotel-phuquoc.com',
                'phone' => '0297 3776 666',
                'website' => 'https://www.novotel.com/phu-quoc',
            ],
            [
                'name' => 'Salinda Resort Phu Quoc Island',
                'description' => 'Resort 4 sao với thiết kế tối giản và dịch vụ ấm cúng',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/salinda_phu_quoc_1.jpg', 'hotels/salinda_phu_quoc_2.jpg']),
                'latitude' => 10.2300,
                'longitude' => 103.9520,
                'email' => 'reservations@salinda-phuquoc.com',
                'phone' => '0297 3775 555',
                'website' => 'https://www.salindaresort.com',
            ],
            [
                'name' => 'La Veranda Resort Phu Quoc',
                'description' => 'Resort 4 sao với kiến trúc Pháp cổ điển và dịch vụ sang trọng',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/la_veranda_phu_quoc_1.jpg', 'hotels/la_veranda_phu_quoc_2.jpg']),
                'latitude' => 10.2280,
                'longitude' => 103.9540,
                'email' => 'reservations@laveranda-phuquoc.com',
                'phone' => '0297 3774 444',
                'website' => 'https://www.laverandaresorts.com',
            ],
            [
                'name' => 'Mango Bay Resort',
                'description' => 'Resort 3 sao với thiết kế bền vững và không gian yên tĩnh',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/mango_bay_phu_quoc_1.jpg', 'hotels/mango_bay_phu_quoc_2.jpg']),
                'latitude' => 10.2200,
                'longitude' => 103.9600,
                'email' => 'reservations@mangobay-phuquoc.com',
                'phone' => '0297 3773 333',
                'website' => 'https://www.mangobayphuquoc.com',
            ],
            [
                'name' => 'Peppercorn Beach Resort',
                'description' => 'Resort 3 sao với view biển đẹp và dịch vụ thân thiện',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/peppercorn_phu_quoc_1.jpg', 'hotels/peppercorn_phu_quoc_2.jpg']),
                'latitude' => 10.2250,
                'longitude' => 103.9560,
                'email' => 'reservations@peppercorn-phuquoc.com',
                'phone' => '0297 3772 222',
                'website' => 'https://www.peppercornbeach.com',
            ],
            [
                'name' => 'Bamboo Cottages & Restaurant',
                'description' => 'Resort 3 sao với nhà gỗ tre và không gian tự nhiên',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/bamboo_cottages_phu_quoc_1.jpg', 'hotels/bamboo_cottages_phu_quoc_2.jpg']),
                'latitude' => 10.2180,
                'longitude' => 103.9620,
                'email' => 'reservations@bamboo-phuquoc.com',
                'phone' => '0297 3771 111',
                'website' => 'https://www.bamboocottages.com',
            ],
            [
                'name' => 'Phu Quoc Ocean Pearl Hotel',
                'description' => 'Khách sạn 4 sao với view biển và dịch vụ hiện đại',
                'address' => 'Đường Trần Hưng Đạo, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/ocean_pearl_phu_quoc_1.jpg', 'hotels/ocean_pearl_phu_quoc_2.jpg']),
                'latitude' => 10.2100,
                'longitude' => 103.9700,
                'email' => 'reservations@oceanpearl-phuquoc.com',
                'phone' => '0297 3770 000',
                'website' => 'https://www.oceanpearlhotel.com',
            ],
            [
                'name' => 'Rạch Giá Hotel',
                'description' => 'Khách sạn 3 sao tại trung tâm thành phố Rạch Giá',
                'address' => 'Đường Nguyễn Trung Trực, TP. Rạch Giá, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/rach_gia_hotel_1.jpg', 'hotels/rach_gia_hotel_2.jpg']),
                'latitude' => 10.0167,
                'longitude' => 105.0833,
                'email' => 'reservations@rachgia-hotel.com',
                'phone' => '0297 3868 888',
                'website' => 'https://www.rachgiahotel.com',
            ],
            [
                'name' => 'Hà Tiên Beach Resort',
                'description' => 'Resort 3 sao với view biển Hà Tiên và dịch vụ ấm cúng',
                'address' => 'Bãi biển Hà Tiên, TP. Hà Tiên, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/ha_tien_beach_resort_1.jpg', 'hotels/ha_tien_beach_resort_2.jpg']),
                'latitude' => 10.3833,
                'longitude' => 104.4833,
                'email' => 'reservations@hatienbeach-resort.com',
                'phone' => '0297 3855 555',
                'website' => 'https://www.hatienbeachresort.com',
            ],
            [
                'name' => 'Phú Quốc Eden Resort',
                'description' => 'Resort 4 sao với thiết kế hiện đại và dịch vụ cao cấp',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/eden_phu_quoc_1.jpg', 'hotels/eden_phu_quoc_2.jpg']),
                'latitude' => 10.2320,
                'longitude' => 103.9500,
                'email' => 'reservations@eden-phuquoc.com',
                'phone' => '0297 3769 999',
                'website' => 'https://www.edenresortphuquoc.com',
            ],
            [
                'name' => 'Seashells Phu Quoc Hotel & Spa',
                'description' => 'Khách sạn 4 sao với spa và dịch vụ wellness',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/seashells_phu_quoc_1.jpg', 'hotels/seashells_phu_quoc_2.jpg']),
                'latitude' => 10.2340,
                'longitude' => 103.9480,
                'email' => 'reservations@seashells-phuquoc.com',
                'phone' => '0297 3768 888',
                'website' => 'https://www.seashellsphuquoc.com',
            ],
            [
                'name' => 'Phu Quoc Bamboo Village Resort',
                'description' => 'Resort 3 sao với nhà gỗ tre và không gian tự nhiên',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/bamboo_village_phu_quoc_1.jpg', 'hotels/bamboo_village_phu_quoc_2.jpg']),
                'latitude' => 10.2160,
                'longitude' => 103.9640,
                'email' => 'reservations@bamboovillage-phuquoc.com',
                'phone' => '0297 3767 777',
                'website' => 'https://www.bamboovillagephuquoc.com',
            ],
            [
                'name' => 'Rạch Giá Central Hotel',
                'description' => 'Khách sạn 3 sao tại trung tâm thành phố Rạch Giá',
                'address' => 'Đường Nguyễn Huệ, TP. Rạch Giá, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/rach_gia_central_1.jpg', 'hotels/rach_gia_central_2.jpg']),
                'latitude' => 10.0180,
                'longitude' => 105.0850,
                'email' => 'reservations@rachgiacentral-hotel.com',
                'phone' => '0297 3867 777',
                'website' => 'https://www.rachgiacentralhotel.com',
            ],
            [
                'name' => 'Hà Tiên Riverside Hotel',
                'description' => 'Khách sạn 3 sao với view sông và dịch vụ thân thiện',
                'address' => 'Đường Bạch Đằng, TP. Hà Tiên, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/ha_tien_riverside_1.jpg', 'hotels/ha_tien_riverside_2.jpg']),
                'latitude' => 10.3850,
                'longitude' => 104.4850,
                'email' => 'reservations@hatienriverside-hotel.com',
                'phone' => '0297 3854 444',
                'website' => 'https://www.hatienriversidehotel.com',
            ],
            [
                'name' => 'Phú Quốc Sunset Resort',
                'description' => 'Resort 3 sao với view hoàng hôn tuyệt đẹp',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/sunset_phu_quoc_1.jpg', 'hotels/sunset_phu_quoc_2.jpg']),
                'latitude' => 10.2220,
                'longitude' => 103.9580,
                'email' => 'reservations@sunset-phuquoc.com',
                'phone' => '0297 3766 666',
                'website' => 'https://www.sunsetphuquoc.com',
            ],
            [
                'name' => 'Phú Quốc Garden Resort',
                'description' => 'Resort 3 sao với vườn cây xanh mát và không gian yên tĩnh',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/garden_phu_quoc_1.jpg', 'hotels/garden_phu_quoc_2.jpg']),
                'latitude' => 10.2260,
                'longitude' => 103.9520,
                'email' => 'reservations@garden-phuquoc.com',
                'phone' => '0297 3765 555',
                'website' => 'https://www.gardenphuquoc.com',
            ],
            [
                'name' => 'Rạch Giá Plaza Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện tại trung tâm',
                'address' => 'Đường Lê Lợi, TP. Rạch Giá, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/rach_gia_plaza_1.jpg', 'hotels/rach_gia_plaza_2.jpg']),
                'latitude' => 10.0200,
                'longitude' => 105.0820,
                'email' => 'reservations@rachgiaplaza-hotel.com',
                'phone' => '0297 3866 666',
                'website' => 'https://www.rachgiaplazahotel.com',
            ],
            [
                'name' => 'Hà Tiên Mountain View Hotel',
                'description' => 'Khách sạn 3 sao với view núi và dịch vụ ấm cúng',
                'address' => 'Đường Phan Chu Trinh, TP. Hà Tiên, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/ha_tien_mountain_1.jpg', 'hotels/ha_tien_mountain_2.jpg']),
                'latitude' => 10.3870,
                'longitude' => 104.4830,
                'email' => 'reservations@hatienmountain-hotel.com',
                'phone' => '0297 3853 333',
                'website' => 'https://www.hatienmountainhotel.com',
            ],
            [
                'name' => 'Phú Quốc Sea View Resort',
                'description' => 'Resort 3 sao với view biển đẹp và dịch vụ thân thiện',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/seaview_phu_quoc_1.jpg', 'hotels/seaview_phu_quoc_2.jpg']),
                'latitude' => 10.2280,
                'longitude' => 103.9540,
                'email' => 'reservations@seaview-phuquoc.com',
                'phone' => '0297 3764 444',
                'website' => 'https://www.seaviewphuquoc.com',
            ],
            [
                'name' => 'Phú Quốc Paradise Resort',
                'description' => 'Resort 4 sao với thiết kế sang trọng và dịch vụ cao cấp',
                'address' => 'Bãi Khem, Xã An Thới, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/paradise_phu_quoc_1.jpg', 'hotels/paradise_phu_quoc_2.jpg']),
                'latitude' => 10.2140,
                'longitude' => 103.9680,
                'email' => 'reservations@paradise-phuquoc.com',
                'phone' => '0297 3763 333',
                'website' => 'https://www.paradisephuquoc.com',
            ],
            [
                'name' => 'Rạch Giá Business Hotel',
                'description' => 'Khách sạn 3 sao phù hợp cho khách công tác',
                'address' => 'Đường Trần Phú, TP. Rạch Giá, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/rach_gia_business_1.jpg', 'hotels/rach_gia_business_2.jpg']),
                'latitude' => 10.0220,
                'longitude' => 105.0840,
                'email' => 'reservations@rachgiabusiness-hotel.com',
                'phone' => '0297 3865 555',
                'website' => 'https://www.rachgiabusinesshotel.com',
            ],
            [
                'name' => 'Hà Tiên Bay Hotel',
                'description' => 'Khách sạn 3 sao với view vịnh Hà Tiên đẹp',
                'address' => 'Đường Bạch Đằng, TP. Hà Tiên, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/ha_tien_bay_1.jpg', 'hotels/ha_tien_bay_2.jpg']),
                'latitude' => 10.3890,
                'longitude' => 104.4810,
                'email' => 'reservations@hatienbay-hotel.com',
                'phone' => '0297 3852 222',
                'website' => 'https://www.hatienbayhotel.com',
            ],
            [
                'name' => 'Phú Quốc Eco Resort',
                'description' => 'Resort 3 sao với thiết kế thân thiện môi trường',
                'address' => 'Bãi Ông Lang, Xã Cửa Dương, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/eco_phu_quoc_1.jpg', 'hotels/eco_phu_quoc_2.jpg']),
                'latitude' => 10.2200,
                'longitude' => 103.9600,
                'email' => 'reservations@eco-phuquoc.com',
                'phone' => '0297 3762 222',
                'website' => 'https://www.ecophuquoc.com',
            ],
            [
                'name' => 'Phú Quốc Family Resort',
                'description' => 'Resort 3 sao phù hợp cho gia đình với nhiều hoạt động',
                'address' => 'Bãi Trường, Xã Dương Tơ, TP. Phú Quốc, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/family_phu_quoc_1.jpg', 'hotels/family_phu_quoc_2.jpg']),
                'latitude' => 10.2240,
                'longitude' => 103.9560,
                'email' => 'reservations@family-phuquoc.com',
                'phone' => '0297 3761 111',
                'website' => 'https://www.familyphuquoc.com',
            ],
            [
                'name' => 'Rạch Giá Comfort Hotel',
                'description' => 'Khách sạn 3 sao với dịch vụ thoải mái và thân thiện',
                'address' => 'Đường Nguyễn Trung Trực, TP. Rạch Giá, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/rach_gia_comfort_1.jpg', 'hotels/rach_gia_comfort_2.jpg']),
                'latitude' => 10.0240,
                'longitude' => 105.0860,
                'email' => 'reservations@rachgiacomfort-hotel.com',
                'phone' => '0297 3864 444',
                'website' => 'https://www.rachgiacomforthotel.com',
            ],
            [
                'name' => 'Hà Tiên Comfort Inn',
                'description' => 'Khách sạn 3 sao với dịch vụ ấm cúng và thân thiện',
                'address' => 'Đường Phan Chu Trinh, TP. Hà Tiên, Tỉnh Kiên Giang',
                'images' => json_encode(['hotels/ha_tien_comfort_1.jpg', 'hotels/ha_tien_comfort_2.jpg']),
                'latitude' => 10.3910,
                'longitude' => 104.4790,
                'email' => 'reservations@hatiencomfort-inn.com',
                'phone' => '0297 3851 111',
                'website' => 'https://www.hatiencomfortinn.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
