<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SaPaCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        // Kiểm tra và tạo location Sa Pa nếu chưa có
        $saPaLocationId = DB::table('locations')->where('name', 'Sa Pa')->value('id');

        if (!$saPaLocationId) {
            $saPaLocationId = DB::table('locations')->insertGetId([
                'name' => 'Sa Pa',
                'description' => 'Thị xã Sa Pa - điểm du lịch núi nổi tiếng với khí hậu mát mẻ và văn hóa dân tộc đặc sắc',
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Núi Fansipan',
                'description' => 'Đỉnh núi cao nhất Đông Dương với view toàn cảnh núi non hùng vĩ',
                'address' => 'Núi Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'image' => 'checkin/nui_fansipan_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 800000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/nui_fansipan_sapa_1.jpg', 'checkin/nui_fansipan_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Nóc nhà Đông Dương',
                'transport_options' => json_encode(['car', 'motorbike', 'cable_car']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Cát Cát',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống và thác nước đẹp',
                'address' => 'Bản Cát Cát, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3340,
                'longitude' => 103.8460,
                'image' => 'checkin/ban_cat_cat_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_cat_cat_sapa_1.jpg', 'checkin/ban_cat_cat_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc nổi tiếng',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Bạc',
                'description' => 'Thác nước đẹp với view núi và không gian mát mẻ',
                'address' => 'Thác Bạc, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3320,
                'longitude' => 103.8480,
                'image' => 'checkin/thac_bac_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_bac_sapa_1.jpg', 'checkin/thac_bac_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thác nước đẹp nhất Sa Pa',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Mây',
                'description' => 'Cầu treo với view núi và không gian lãng mạn',
                'address' => 'Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3300,
                'longitude' => 103.8500,
                'image' => 'checkin/cau_may_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/cau_may_sapa_1.jpg', 'checkin/cau_may_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cầu treo lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Tả Van',
                'description' => 'Bản làng dân tộc Giáy với văn hóa truyền thống và ruộng bậc thang',
                'address' => 'Bản Tả Van, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3280,
                'longitude' => 103.8520,
                'image' => 'checkin/ban_ta_van_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_ta_van_sapa_1.jpg', 'checkin/ban_ta_van_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng ruộng bậc thang',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đèo Ô Quy Hồ',
                'description' => 'Đèo núi với view toàn cảnh núi non hùng vĩ',
                'address' => 'Đèo Ô Quy Hồ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3260,
                'longitude' => 103.8540,
                'image' => 'checkin/deo_o_quy_ho_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/deo_o_quy_ho_sapa_1.jpg', 'checkin/deo_o_quy_ho_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đèo núi đẹp nhất Tây Bắc',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Lao Chải',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống',
                'address' => 'Bản Lao Chải, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3240,
                'longitude' => 103.8560,
                'image' => 'checkin/ban_lao_chai_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_lao_chai_sapa_1.jpg', 'checkin/ban_lao_chai_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc H\'Mông',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Tình Yêu',
                'description' => 'Thác nước lãng mạn với view núi và không gian yên tĩnh',
                'address' => 'Thác Tình Yêu, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3220,
                'longitude' => 103.8580,
                'image' => 'checkin/thac_tinh_yeu_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_tinh_yeu_sapa_1.jpg', 'checkin/thac_tinh_yeu_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thác nước lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Kính Rồng Mây',
                'description' => 'Cầu kính với view núi và không gian độc đáo',
                'address' => 'Cầu Kính Rồng Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3200,
                'longitude' => 103.8600,
                'image' => 'checkin/cau_kinh_rong_may_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 150000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/cau_kinh_rong_may_sapa_1.jpg', 'checkin/cau_kinh_rong_may_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cầu kính độc đáo',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Sín Chải',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống',
                'address' => 'Bản Sín Chải, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3180,
                'longitude' => 103.8620,
                'image' => 'checkin/ban_sin_chai_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_sin_chai_sapa_1.jpg', 'checkin/ban_sin_chai_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc H\'Mông',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đỉnh Hàm Rồng',
                'description' => 'Đỉnh núi với view toàn cảnh Sa Pa và không gian yên tĩnh',
                'address' => 'Đỉnh Hàm Rồng, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3160,
                'longitude' => 103.8640,
                'image' => 'checkin/dinh_ham_rong_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 60000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dinh_ham_rong_sapa_1.jpg', 'checkin/dinh_ham_rong_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đỉnh núi đẹp nhất Sa Pa',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Y Linh Hồ',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống',
                'address' => 'Bản Y Linh Hồ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3140,
                'longitude' => 103.8660,
                'image' => 'checkin/ban_y_linh_ho_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_y_linh_ho_sapa_1.jpg', 'checkin/ban_y_linh_ho_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc H\'Mông',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Tác Tình',
                'description' => 'Thác nước với view núi và không gian mát mẻ',
                'address' => 'Thác Tác Tình, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3120,
                'longitude' => 103.8680,
                'image' => 'checkin/thac_tac_tinh_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_tac_tinh_sapa_1.jpg', 'checkin/thac_tac_tinh_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thác nước mát mẻ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Tình Yêu',
                'description' => 'Cầu treo lãng mạn với view núi và không gian yên tĩnh',
                'address' => 'Cầu Tình Yêu, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3100,
                'longitude' => 103.8700,
                'image' => 'checkin/cau_tinh_yeu_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/cau_tinh_yeu_sapa_1.jpg', 'checkin/cau_tinh_yeu_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cầu treo lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Tả Phìn',
                'description' => 'Bản làng dân tộc Dao với văn hóa truyền thống',
                'address' => 'Bản Tả Phìn, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3080,
                'longitude' => 103.8720,
                'image' => 'checkin/ban_ta_phin_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_ta_phin_sapa_1.jpg', 'checkin/ban_ta_phin_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc Dao',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đỉnh Núi Hàm Rồng',
                'description' => 'Đỉnh núi với view toàn cảnh Sa Pa và không gian yên tĩnh',
                'address' => 'Đỉnh Núi Hàm Rồng, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3060,
                'longitude' => 103.8740,
                'image' => 'checkin/dinh_nui_ham_rong_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dinh_nui_ham_rong_sapa_1.jpg', 'checkin/dinh_nui_ham_rong_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đỉnh núi đẹp nhất',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Sử Pán',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống',
                'address' => 'Bản Sử Pán, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3040,
                'longitude' => 103.8760,
                'image' => 'checkin/ban_su_pan_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_su_pan_sapa_1.jpg', 'checkin/ban_su_pan_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc H\'Mông',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Bạc 2',
                'description' => 'Thác nước với view núi và không gian mát mẻ',
                'address' => 'Thác Bạc 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3020,
                'longitude' => 103.8780,
                'image' => 'checkin/thac_bac_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_bac_2_sapa_1.jpg', 'checkin/thac_bac_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thác nước mát mẻ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Mây 2',
                'description' => 'Cầu treo với view núi và không gian lãng mạn',
                'address' => 'Cầu Mây 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3000,
                'longitude' => 103.8800,
                'image' => 'checkin/cau_may_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/cau_may_2_sapa_1.jpg', 'checkin/cau_may_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cầu treo lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Tả Van 2',
                'description' => 'Bản làng dân tộc Giáy với văn hóa truyền thống',
                'address' => 'Bản Tả Van 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2980,
                'longitude' => 103.8820,
                'image' => 'checkin/ban_ta_van_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_ta_van_2_sapa_1.jpg', 'checkin/ban_ta_van_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc Giáy',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đèo Ô Quy Hồ 2',
                'description' => 'Đèo núi với view toàn cảnh núi non hùng vĩ',
                'address' => 'Đèo Ô Quy Hồ 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2960,
                'longitude' => 103.8840,
                'image' => 'checkin/deo_o_quy_ho_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/deo_o_quy_ho_2_sapa_1.jpg', 'checkin/deo_o_quy_ho_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đèo núi đẹp nhất',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Lao Chải 2',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống',
                'address' => 'Bản Lao Chải 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2940,
                'longitude' => 103.8860,
                'image' => 'checkin/ban_lao_chai_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_lao_chai_2_sapa_1.jpg', 'checkin/ban_lao_chai_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc H\'Mông',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Tình Yêu 2',
                'description' => 'Thác nước lãng mạn với view núi và không gian yên tĩnh',
                'address' => 'Thác Tình Yêu 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2920,
                'longitude' => 103.8880,
                'image' => 'checkin/thac_tinh_yeu_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_tinh_yeu_2_sapa_1.jpg', 'checkin/thac_tinh_yeu_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thác nước lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Kính Rồng Mây 2',
                'description' => 'Cầu kính với view núi và không gian độc đáo',
                'address' => 'Cầu Kính Rồng Mây 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2900,
                'longitude' => 103.8900,
                'image' => 'checkin/cau_kinh_rong_may_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 120000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/cau_kinh_rong_may_2_sapa_1.jpg', 'checkin/cau_kinh_rong_may_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cầu kính độc đáo',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Sín Chải 2',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống',
                'address' => 'Bản Sín Chải 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2880,
                'longitude' => 103.8920,
                'image' => 'checkin/ban_sin_chai_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_sin_chai_2_sapa_1.jpg', 'checkin/ban_sin_chai_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc H\'Mông',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đỉnh Hàm Rồng 2',
                'description' => 'Đỉnh núi với view toàn cảnh Sa Pa và không gian yên tĩnh',
                'address' => 'Đỉnh Hàm Rồng 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2860,
                'longitude' => 103.8940,
                'image' => 'checkin/dinh_ham_rong_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 45000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dinh_ham_rong_2_sapa_1.jpg', 'checkin/dinh_ham_rong_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đỉnh núi đẹp nhất',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bản Y Linh Hồ 2',
                'description' => 'Bản làng dân tộc H\'Mông với văn hóa truyền thống',
                'address' => 'Bản Y Linh Hồ 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2840,
                'longitude' => 103.8960,
                'image' => 'checkin/ban_y_linh_ho_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ban_y_linh_ho_2_sapa_1.jpg', 'checkin/ban_y_linh_ho_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bản làng dân tộc H\'Mông',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Thác Tác Tình 2',
                'description' => 'Thác nước với view núi và không gian mát mẻ',
                'address' => 'Thác Tác Tình 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2820,
                'longitude' => 103.8980,
                'image' => 'checkin/thac_tac_tinh_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thac_tac_tinh_2_sapa_1.jpg', 'checkin/thac_tac_tinh_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Thác nước mát mẻ',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Tình Yêu 2',
                'description' => 'Cầu treo lãng mạn với view núi và không gian yên tĩnh',
                'address' => 'Cầu Tình Yêu 2, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2800,
                'longitude' => 103.9000,
                'image' => 'checkin/cau_tinh_yeu_2_sapa.jpg',
                'location_id' => $saPaLocationId,
                'price' => 10000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/cau_tinh_yeu_2_sapa_1.jpg', 'checkin/cau_tinh_yeu_2_sapa_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cầu treo lãng mạn',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
