<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CanThoHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'Victoria Can Tho Resort',
                'description' => 'Resort 4 sao cao cấp với view sông Hậu tuyệt đẹp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/victoria_can_tho_1.jpg', 'hotels/victoria_can_tho_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@victoria-cantho.com',
                'phone' => '0292 3810 111',
                'website' => 'https://www.victoriahotels.asia/cantho',
            ],
            [
                'name' => 'Muong Thanh Can Tho Hotel',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ tốt',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/muong_thanh_can_tho_1.jpg', 'hotels/muong_thanh_can_tho_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@muong-thanh-cantho.com',
                'phone' => '0292 3810 222',
                'website' => 'https://www.muong-thanh-cantho.com',
            ],
            [
                'name' => 'Can Tho Central Hotel',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm thuận tiện',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_central_1.jpg', 'hotels/can_tho_central_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-central.com',
                'phone' => '0292 3810 333',
                'website' => 'https://www.cantho-central.com',
            ],
            [
                'name' => 'Can Tho Riverside Hotel',
                'description' => 'Khách sạn 3 sao với view sông Hậu đẹp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_riverside_1.jpg', 'hotels/can_tho_riverside_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-riverside.com',
                'phone' => '0292 3810 444',
                'website' => 'https://www.cantho-riverside.com',
            ],
            [
                'name' => 'Can Tho Garden Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_garden_1.jpg', 'hotels/can_tho_garden_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-garden.com',
                'phone' => '0292 3810 555',
                'website' => 'https://www.cantho-garden.com',
            ],
            [
                'name' => 'Can Tho Plaza Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm mua sắm',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_plaza_1.jpg', 'hotels/can_tho_plaza_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-plaza.com',
                'phone' => '0292 3810 666',
                'website' => 'https://www.cantho-plaza.com',
            ],
            [
                'name' => 'Can Tho Royal Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và dịch vụ cao cấp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_royal_1.jpg', 'hotels/can_tho_royal_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-royal.com',
                'phone' => '0292 3810 777',
                'website' => 'https://www.cantho-royal.com',
            ],
            [
                'name' => 'Can Tho Sky Hotel',
                'description' => 'Khách sạn 4 sao với view toàn cảnh thành phố từ trên cao',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_sky_1.jpg', 'hotels/can_tho_sky_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-sky.com',
                'phone' => '0292 3810 888',
                'website' => 'https://www.cantho-sky.com',
            ],
            [
                'name' => 'Can Tho Tower Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và view đẹp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_tower_1.jpg', 'hotels/can_tho_tower_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-tower.com',
                'phone' => '0292 3810 999',
                'website' => 'https://www.cantho-tower.com',
            ],
            [
                'name' => 'Can Tho View Hotel',
                'description' => 'Khách sạn 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_view_1.jpg', 'hotels/can_tho_view_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-view.com',
                'phone' => '0292 3809 111',
                'website' => 'https://www.cantho-view.com',
            ],
            [
                'name' => 'Can Tho Central Plaza Hotel',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_central_plaza_1.jpg', 'hotels/can_tho_central_plaza_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-central-plaza.com',
                'phone' => '0292 3809 222',
                'website' => 'https://www.cantho-central-plaza.com',
            ],
            [
                'name' => 'Can Tho Golden Hotel',
                'description' => 'Khách sạn 3 sao với dịch vụ tốt và giá cả hợp lý',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_golden_1.jpg', 'hotels/can_tho_golden_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-golden.com',
                'phone' => '0292 3809 333',
                'website' => 'https://www.cantho-golden.com',
            ],
            [
                'name' => 'Can Tho Pearl Resort',
                'description' => 'Resort 4 sao với view sông và dịch vụ cao cấp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_pearl_1.jpg', 'hotels/can_tho_pearl_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-pearl.com',
                'phone' => '0292 3809 444',
                'website' => 'https://www.cantho-pearl.com',
            ],
            [
                'name' => 'Can Tho Diamond Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và dịch vụ cao cấp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_diamond_1.jpg', 'hotels/can_tho_diamond_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-diamond.com',
                'phone' => '0292 3809 555',
                'website' => 'https://www.cantho-diamond.com',
            ],
            [
                'name' => 'Can Tho Ocean Resort',
                'description' => 'Resort 3 sao với view sông và không gian thoáng đãng',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_ocean_1.jpg', 'hotels/can_tho_ocean_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-ocean.com',
                'phone' => '0292 3809 666',
                'website' => 'https://www.cantho-ocean.com',
            ],
            [
                'name' => 'Can Tho Emerald Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_emerald_1.jpg', 'hotels/can_tho_emerald_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-emerald.com',
                'phone' => '0292 3809 777',
                'website' => 'https://www.cantho-emerald.com',
            ],
            [
                'name' => 'Can Tho Crystal Resort',
                'description' => 'Resort 3 sao với view sông trong xanh như pha lê',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_crystal_1.jpg', 'hotels/can_tho_crystal_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-crystal.com',
                'phone' => '0292 3809 888',
                'website' => 'https://www.cantho-crystal.com',
            ],
            [
                'name' => 'Can Tho Sapphire Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng như ngọc bích',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_sapphire_1.jpg', 'hotels/can_tho_sapphire_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-sapphire.com',
                'phone' => '0292 3809 999',
                'website' => 'https://www.cantho-sapphire.com',
            ],
            [
                'name' => 'Can Tho Ruby Resort',
                'description' => 'Resort 4 sao với thiết kế sang trọng như ngọc ruby',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_ruby_1.jpg', 'hotels/can_tho_ruby_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-ruby.com',
                'phone' => '0292 3808 111',
                'website' => 'https://www.cantho-ruby.com',
            ],
            [
                'name' => 'Can Tho Highland Palace',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và view sông đẹp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_highland_palace_1.jpg', 'hotels/can_tho_highland_palace_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-highland-palace.com',
                'phone' => '0292 3808 222',
                'website' => 'https://www.cantho-highland-palace.com',
            ],
            [
                'name' => 'Can Tho Valley Palace',
                'description' => 'Resort 4 sao với thiết kế sang trọng và view sông đẹp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_valley_palace_1.jpg', 'hotels/can_tho_valley_palace_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-valley-palace.com',
                'phone' => '0292 3808 333',
                'website' => 'https://www.cantho-valley-palace.com',
            ],
            [
                'name' => 'Can Tho Mountain View Resort',
                'description' => 'Resort 3 sao với view sông đẹp và không gian thoáng đãng',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_mountain_view_resort_1.jpg', 'hotels/can_tho_mountain_view_resort_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-mountain-view-resort.com',
                'phone' => '0292 3808 444',
                'website' => 'https://www.cantho-mountain-view-resort.com',
            ],
            [
                'name' => 'Can Tho Garden Resort',
                'description' => 'Resort 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_garden_resort_1.jpg', 'hotels/can_tho_garden_resort_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-garden-resort.com',
                'phone' => '0292 3808 555',
                'website' => 'https://www.cantho-garden-resort.com',
            ],
            [
                'name' => 'Can Tho Sky Resort',
                'description' => 'Resort 4 sao với view toàn cảnh từ trên cao',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_sky_resort_1.jpg', 'hotels/can_tho_sky_resort_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-sky-resort.com',
                'phone' => '0292 3808 666',
                'website' => 'https://www.cantho-sky-resort.com',
            ],
            [
                'name' => 'Can Tho Tower Resort',
                'description' => 'Resort 4 sao với thiết kế hiện đại và view đẹp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_tower_resort_1.jpg', 'hotels/can_tho_tower_resort_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-tower-resort.com',
                'phone' => '0292 3808 777',
                'website' => 'https://www.cantho-tower-resort.com',
            ],
            [
                'name' => 'Can Tho View Resort',
                'description' => 'Resort 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_view_resort_1.jpg', 'hotels/can_tho_view_resort_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-view-resort.com',
                'phone' => '0292 3808 888',
                'website' => 'https://www.cantho-view-resort.com',
            ],
            [
                'name' => 'Can Tho Central Resort',
                'description' => 'Resort 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_central_resort_1.jpg', 'hotels/can_tho_central_resort_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-central-resort.com',
                'phone' => '0292 3808 999',
                'website' => 'https://www.cantho-central-resort.com',
            ],
            [
                'name' => 'Can Tho Highland Resort 2',
                'description' => 'Resort 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_highland_2_1.jpg', 'hotels/can_tho_highland_2_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-highland-2.com',
                'phone' => '0292 3807 111',
                'website' => 'https://www.cantho-highland-2.com',
            ],
            [
                'name' => 'Can Tho Valley Resort 2',
                'description' => 'Resort 4 sao với view sông đẹp',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'images' => json_encode(['hotels/can_tho_valley_2_1.jpg', 'hotels/can_tho_valley_2_2.jpg']),
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'email' => 'reservations@cantho-valley-2.com',
                'phone' => '0292 3807 222',
                'website' => 'https://www.cantho-valley-2.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
