<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CanThoRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Cá Lóc Nướng Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cá lóc nướng trui và các món ăn đặc sản miền Tây',
                'address' => 'Đường 30/4, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'rating' => 4.5,
                'price_range' => '150,000 - 500,000 VND',
                'image' => 'restaurants/ca_loc_nuong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Mắm Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ lẩu mắm và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Linh, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0430,
                'longitude' => 105.7480,
                'rating' => 4.3,
                'price_range' => '200,000 - 600,000 VND',
                'image' => 'restaurants/lau_mam_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Nước Lèo Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bún nước lèo và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Trãi, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0410,
                'longitude' => 105.7500,
                'rating' => 4.4,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/bun_nuoc_leo_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm và các món ăn đặc sản miền Tây',
                'address' => 'Đường Lý Tự Trọng, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0390,
                'longitude' => 105.7520,
                'rating' => 4.2,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/com_tam_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Xèo Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bánh xèo và các món ăn đặc sản miền Tây',
                'address' => 'Đường Hòa Bình, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0370,
                'longitude' => 105.7540,
                'rating' => 4.3,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/banh_xeo_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Tai Tượng Chiên Xù Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cá tai tượng chiên xù và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Cừ, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0350,
                'longitude' => 105.7560,
                'rating' => 4.4,
                'price_range' => '180,000 - 500,000 VND',
                'image' => 'restaurants/ca_tai_tuong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Cua Đồng Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ lẩu cua đồng và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Linh, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0330,
                'longitude' => 105.7580,
                'rating' => 4.5,
                'price_range' => '250,000 - 700,000 VND',
                'image' => 'restaurants/lau_cua_dong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Cá Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bún cá và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Trãi, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0310,
                'longitude' => 105.7600,
                'rating' => 4.3,
                'price_range' => '70,000 - 200,000 VND',
                'image' => 'restaurants/bun_ca_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Gà Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cơm gà và các món ăn đặc sản miền Tây',
                'address' => 'Đường Lý Tự Trọng, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0290,
                'longitude' => 105.7620,
                'rating' => 4.2,
                'price_range' => '90,000 - 250,000 VND',
                'image' => 'restaurants/com_ga_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cống Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bánh cống và các món ăn đặc sản miền Tây',
                'address' => 'Đường Hòa Bình, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0270,
                'longitude' => 105.7640,
                'rating' => 4.4,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_cong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Lăng Nướng Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cá lăng nướng và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Cừ, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0250,
                'longitude' => 105.7660,
                'rating' => 4.5,
                'price_range' => '200,000 - 600,000 VND',
                'image' => 'restaurants/ca_lang_nuong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Bò Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ lẩu bò và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Linh, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0230,
                'longitude' => 105.7680,
                'rating' => 4.3,
                'price_range' => '300,000 - 800,000 VND',
                'image' => 'restaurants/lau_bo_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bún bò và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Trãi, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0210,
                'longitude' => 105.7700,
                'rating' => 4.2,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/bun_bo_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Sườn Nướng Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm sườn nướng và các món ăn đặc sản miền Tây',
                'address' => 'Đường Lý Tự Trọng, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0190,
                'longitude' => 105.7720,
                'rating' => 4.4,
                'price_range' => '100,000 - 250,000 VND',
                'image' => 'restaurants/com_tam_suon_nuong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Tét Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bánh tét và các món ăn đặc sản miền Tây',
                'address' => 'Đường Hòa Bình, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0170,
                'longitude' => 105.7740,
                'rating' => 4.3,
                'price_range' => '40,000 - 120,000 VND',
                'image' => 'restaurants/banh_tet_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Bớp Nướng Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cá bớp nướng và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Cừ, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0150,
                'longitude' => 105.7760,
                'rating' => 4.5,
                'price_range' => '250,000 - 700,000 VND',
                'image' => 'restaurants/ca_bop_nuong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Gà Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ lẩu gà và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Linh, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 10.0130,
                'longitude' => 105.7780,
                'rating' => 4.3,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/lau_ga_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Riêu Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bún riêu và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Trãi, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 10.0110,
                'longitude' => 105.7800,
                'rating' => 4.2,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/bun_rieu_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Gà Xối Mỡ Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cơm gà xối mỡ và các món ăn đặc sản miền Tây',
                'address' => 'Đường Lý Tự Trọng, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 10.0090,
                'longitude' => 105.7820,
                'rating' => 4.4,
                'price_range' => '120,000 - 300,000 VND',
                'image' => 'restaurants/com_ga_xoi_mo_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Pía Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bánh pía và các món ăn đặc sản miền Tây',
                'address' => 'Đường Hòa Bình, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 10.0070,
                'longitude' => 105.7840,
                'rating' => 4.3,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_pia_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Trê Nướng Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cá trê nướng và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Cừ, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 10.0050,
                'longitude' => 105.7860,
                'rating' => 4.5,
                'price_range' => '180,000 - 500,000 VND',
                'image' => 'restaurants/ca_tre_nuong_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Cá Lăng Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ lẩu cá lăng và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Linh, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 10.0030,
                'longitude' => 105.7880,
                'rating' => 4.4,
                'price_range' => '300,000 - 800,000 VND',
                'image' => 'restaurants/lau_ca_lang_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Mắm Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bún mắm và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Trãi, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 10.0010,
                'longitude' => 105.7900,
                'rating' => 4.3,
                'price_range' => '70,000 - 200,000 VND',
                'image' => 'restaurants/bun_mam_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Chả Cá Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm chả cá và các món ăn đặc sản miền Tây',
                'address' => 'Đường Lý Tự Trọng, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 9.9990,
                'longitude' => 105.7920,
                'rating' => 4.4,
                'price_range' => '110,000 - 280,000 VND',
                'image' => 'restaurants/com_tam_cha_ca_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Tét Cốm Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bánh tét cốm và các món ăn đặc sản miền Tây',
                'address' => 'Đường Hòa Bình, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 9.9970,
                'longitude' => 105.7940,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_tet_com_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Bớp Hấp Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cá bớp hấp và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Cừ, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 9.9950,
                'longitude' => 105.7960,
                'rating' => 4.5,
                'price_range' => '280,000 - 750,000 VND',
                'image' => 'restaurants/ca_bop_hap_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Cá Bớp Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ lẩu cá bớp và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Linh, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 9.9930,
                'longitude' => 105.7980,
                'rating' => 4.4,
                'price_range' => '350,000 - 900,000 VND',
                'image' => 'restaurants/lau_ca_bop_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Cá Lóc Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bún cá lóc và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Trãi, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 9.9910,
                'longitude' => 105.8000,
                'rating' => 4.3,
                'price_range' => '80,000 - 220,000 VND',
                'image' => 'restaurants/bun_ca_loc_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Sườn Bò Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm sườn bò và các món ăn đặc sản miền Tây',
                'address' => 'Đường Lý Tự Trọng, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 9.9890,
                'longitude' => 105.8020,
                'rating' => 4.4,
                'price_range' => '130,000 - 320,000 VND',
                'image' => 'restaurants/com_tam_suon_bo_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Tét Thịt Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ bánh tét thịt và các món ăn đặc sản miền Tây',
                'address' => 'Đường Hòa Bình, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 9.9870,
                'longitude' => 105.8040,
                'rating' => 4.3,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/banh_tet_thit_can_tho.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Trê Chiên Cần Thơ',
                'description' => 'Nhà hàng chuyên phục vụ cá trê chiên và các món ăn đặc sản miền Tây',
                'address' => 'Đường Nguyễn Văn Cừ, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 9.9850,
                'longitude' => 105.8060,
                'rating' => 4.5,
                'price_range' => '200,000 - 550,000 VND',
                'image' => 'restaurants/ca_tre_chien_can_tho.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
