<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CanThoCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        // Kiểm tra và tạo location Cần Thơ nếu chưa có
        $canThoLocationId = DB::table('locations')->where('name', 'Cần Thơ')->value('id');

        if (!$canThoLocationId) {
            $canThoLocationId = DB::table('locations')->insertGetId([
                'name' => 'Cần Thơ',
                'description' => 'Thành phố Cần Thơ - thủ phủ miền Tây với văn hóa sông nước và ẩm thực đặc sắc',
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Chợ Nổi Cái Răng',
                'description' => 'Chợ nổi nổi tiếng với các ghe thuyền buôn bán trái cây và đặc sản miền Tây',
                'address' => 'Chợ Nổi Cái Răng, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0452,
                'longitude' => 105.7469,
                'image' => 'checkin/cho_noi_cai_rang_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '11:00']]),
                'images' => json_encode(['checkin/cho_noi_cai_rang_can_tho_1.jpg', 'checkin/cho_noi_cai_rang_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chợ nổi lớn nhất miền Tây',
                'transport_options' => json_encode(['car', 'motorbike', 'boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Ninh Kiều',
                'description' => 'Bến sông đẹp với view sông Hậu và không gian lãng mạn',
                'address' => 'Bến Ninh Kiều, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0430,
                'longitude' => 105.7480,
                'image' => 'checkin/ben_ninh_kieu_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/ben_ninh_kieu_can_tho_1.jpg', 'checkin/ben_ninh_kieu_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Trái tim của thành phố Cần Thơ',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Cò Bằng Lăng',
                'description' => 'Vườn cò với hàng nghìn con cò trắng và không gian thiên nhiên hoang dã',
                'address' => 'Vườn Cò Bằng Lăng, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 10.0410,
                'longitude' => 105.7500,
                'image' => 'checkin/vuon_co_bang_lang_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/vuon_co_bang_lang_can_tho_1.jpg', 'checkin/vuon_co_bang_lang_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn cò đẹp nhất miền Tây',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Du Lịch Mỹ Khánh',
                'description' => 'Làng du lịch với văn hóa miền Tây và các hoạt động dân gian',
                'address' => 'Làng Du Lịch Mỹ Khánh, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 10.0390,
                'longitude' => 105.7520,
                'image' => 'checkin/lang_du_lich_my_khanh_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 80000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_du_lich_my_khanh_can_tho_1.jpg', 'checkin/lang_du_lich_my_khanh_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Làng du lịch văn hóa miền Tây',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Ông',
                'description' => 'Ngôi chùa cổ với kiến trúc độc đáo và không gian tâm linh',
                'address' => 'Chùa Ông, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0370,
                'longitude' => 105.7540,
                'image' => 'checkin/chua_ong_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_ong_can_tho_1.jpg', 'checkin/chua_ong_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Ngôi chùa cổ nổi tiếng',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Trái Cây Cái Mơn',
                'description' => 'Vườn trái cây với nhiều loại trái cây miền Tây tươi ngon',
                'address' => 'Vườn Trái Cây Cái Mơn, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0350,
                'longitude' => 105.7560,
                'image' => 'checkin/vuon_trai_cay_cai_mon_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_trai_cay_cai_mon_can_tho_1.jpg', 'checkin/vuon_trai_cay_cai_mon_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn trái cây miền Tây',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Tàu Du Lịch Cần Thơ',
                'description' => 'Bến tàu du lịch với các tour khám phá sông nước miền Tây',
                'address' => 'Bến Tàu Du Lịch, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0330,
                'longitude' => 105.7580,
                'image' => 'checkin/ben_tau_du_lich_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 150000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ben_tau_du_lich_can_tho_1.jpg', 'checkin/ben_tau_du_lich_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bến tàu du lịch sông nước',
                'transport_options' => json_encode(['car', 'motorbike', 'boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Tân An',
                'description' => 'Chợ truyền thống với các sản phẩm đặc sản miền Tây',
                'address' => 'Chợ Tân An, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0310,
                'longitude' => 105.7600,
                'image' => 'checkin/cho_tan_an_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cho_tan_an_can_tho_1.jpg', 'checkin/cho_tan_an_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chợ truyền thống miền Tây',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Lan Cần Thơ',
                'description' => 'Vườn lan với nhiều loài lan đẹp và không gian thanh lịch',
                'address' => 'Vườn Lan Cần Thơ, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0290,
                'longitude' => 105.7620,
                'image' => 'checkin/vuon_lan_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_lan_can_tho_1.jpg', 'checkin/vuon_lan_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn lan đẹp nhất miền Tây',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Phà Cần Thơ',
                'description' => 'Bến phà với view sông Hậu và không gian sông nước',
                'address' => 'Bến Phà Cần Thơ, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0270,
                'longitude' => 105.7640,
                'image' => 'checkin/ben_pha_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/ben_pha_can_tho_1.jpg', 'checkin/ben_pha_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bến phà sông Hậu',
                'transport_options' => json_encode(['car', 'motorbike', 'ferry']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Trái Cây Bình Thủy',
                'description' => 'Vườn trái cây với nhiều loại trái cây miền Tây tươi ngon',
                'address' => 'Vườn Trái Cây Bình Thủy, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0250,
                'longitude' => 105.7660,
                'image' => 'checkin/vuon_trai_cay_binh_thuy_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_trai_cay_binh_thuy_can_tho_1.jpg', 'checkin/vuon_trai_cay_binh_thuy_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn trái cây Bình Thủy',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Pothisomron',
                'description' => 'Ngôi chùa Khmer với kiến trúc độc đáo và không gian tâm linh',
                'address' => 'Chùa Pothisomron, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0230,
                'longitude' => 105.7680,
                'image' => 'checkin/chua_pothisomron_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_pothisomron_can_tho_1.jpg', 'checkin/chua_pothisomron_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chùa Khmer nổi tiếng',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Cò Bằng Lăng 2',
                'description' => 'Vườn cò với hàng nghìn con cò trắng và không gian thiên nhiên hoang dã',
                'address' => 'Vườn Cò Bằng Lăng 2, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 10.0210,
                'longitude' => 105.7700,
                'image' => 'checkin/vuon_co_bang_lang_2_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 45000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/vuon_co_bang_lang_2_can_tho_1.jpg', 'checkin/vuon_co_bang_lang_2_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn cò thiên nhiên',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Du Lịch Mỹ Khánh 2',
                'description' => 'Làng du lịch với văn hóa miền Tây và các hoạt động dân gian',
                'address' => 'Làng Du Lịch Mỹ Khánh 2, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 10.0190,
                'longitude' => 105.7720,
                'image' => 'checkin/lang_du_lich_my_khanh_2_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 70000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_du_lich_my_khanh_2_can_tho_1.jpg', 'checkin/lang_du_lich_my_khanh_2_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Làng du lịch văn hóa',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Long Quang',
                'description' => 'Ngôi chùa cổ với kiến trúc độc đáo và không gian tâm linh',
                'address' => 'Chùa Long Quang, Quận Ninh Kiều, TP. Cần Thơ',
                'latitude' => 10.0170,
                'longitude' => 105.7740,
                'image' => 'checkin/chua_long_quang_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_long_quang_can_tho_1.jpg', 'checkin/chua_long_quang_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chùa cổ Long Quang',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Trái Cây Ô Môn',
                'description' => 'Vườn trái cây với nhiều loại trái cây miền Tây tươi ngon',
                'address' => 'Vườn Trái Cây Ô Môn, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 10.0150,
                'longitude' => 105.7760,
                'image' => 'checkin/vuon_trai_cay_o_mon_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_trai_cay_o_mon_can_tho_1.jpg', 'checkin/vuon_trai_cay_o_mon_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn trái cây Ô Môn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Tàu Du Lịch Cái Răng',
                'description' => 'Bến tàu du lịch với các tour khám phá sông nước miền Tây',
                'address' => 'Bến Tàu Du Lịch Cái Răng, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0130,
                'longitude' => 105.7780,
                'image' => 'checkin/ben_tau_du_lich_cai_rang_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 120000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ben_tau_du_lich_cai_rang_can_tho_1.jpg', 'checkin/ben_tau_du_lich_cai_rang_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bến tàu du lịch Cái Răng',
                'transport_options' => json_encode(['car', 'motorbike', 'boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Cái Răng',
                'description' => 'Chợ truyền thống với các sản phẩm đặc sản miền Tây',
                'address' => 'Chợ Cái Răng, Quận Cái Răng, TP. Cần Thơ',
                'latitude' => 10.0110,
                'longitude' => 105.7800,
                'image' => 'checkin/cho_cai_rang_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cho_cai_rang_can_tho_1.jpg', 'checkin/cho_cai_rang_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chợ truyền thống Cái Răng',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Lan Bình Thủy',
                'description' => 'Vườn lan với nhiều loài lan đẹp và không gian thanh lịch',
                'address' => 'Vườn Lan Bình Thủy, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0090,
                'longitude' => 105.7820,
                'image' => 'checkin/vuon_lan_binh_thuy_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_lan_binh_thuy_can_tho_1.jpg', 'checkin/vuon_lan_binh_thuy_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn lan Bình Thủy',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Phà Bình Thủy',
                'description' => 'Bến phà với view sông Hậu và không gian sông nước',
                'address' => 'Bến Phà Bình Thủy, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0070,
                'longitude' => 105.7840,
                'image' => 'checkin/ben_pha_binh_thuy_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/ben_pha_binh_thuy_can_tho_1.jpg', 'checkin/ben_pha_binh_thuy_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bến phà Bình Thủy',
                'transport_options' => json_encode(['car', 'motorbike', 'ferry']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Trái Cây Thốt Nốt',
                'description' => 'Vườn trái cây với nhiều loại trái cây miền Tây tươi ngon',
                'address' => 'Vườn Trái Cây Thốt Nốt, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 10.0050,
                'longitude' => 105.7860,
                'image' => 'checkin/vuon_trai_cay_thot_not_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_trai_cay_thot_not_can_tho_1.jpg', 'checkin/vuon_trai_cay_thot_not_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn trái cây Thốt Nốt',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Bình Thủy',
                'description' => 'Ngôi chùa cổ với kiến trúc độc đáo và không gian tâm linh',
                'address' => 'Chùa Bình Thủy, Quận Bình Thủy, TP. Cần Thơ',
                'latitude' => 10.0030,
                'longitude' => 105.7880,
                'image' => 'checkin/chua_binh_thuy_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_binh_thuy_can_tho_1.jpg', 'checkin/chua_binh_thuy_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chùa cổ Bình Thủy',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Cò Ô Môn',
                'description' => 'Vườn cò với hàng nghìn con cò trắng và không gian thiên nhiên hoang dã',
                'address' => 'Vườn Cò Ô Môn, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 10.0010,
                'longitude' => 105.7900,
                'image' => 'checkin/vuon_co_o_mon_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/vuon_co_o_mon_can_tho_1.jpg', 'checkin/vuon_co_o_mon_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn cò Ô Môn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Du Lịch Phong Điền',
                'description' => 'Làng du lịch với văn hóa miền Tây và các hoạt động dân gian',
                'address' => 'Làng Du Lịch Phong Điền, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 9.9990,
                'longitude' => 105.7920,
                'image' => 'checkin/lang_du_lich_phong_dien_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 60000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_du_lich_phong_dien_can_tho_1.jpg', 'checkin/lang_du_lich_phong_dien_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Làng du lịch Phong Điền',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Thốt Nốt',
                'description' => 'Ngôi chùa cổ với kiến trúc độc đáo và không gian tâm linh',
                'address' => 'Chùa Thốt Nốt, Quận Thốt Nốt, TP. Cần Thơ',
                'latitude' => 9.9970,
                'longitude' => 105.7940,
                'image' => 'checkin/chua_thot_not_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_thot_not_can_tho_1.jpg', 'checkin/chua_thot_not_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chùa cổ Thốt Nốt',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Trái Cây Phong Điền',
                'description' => 'Vườn trái cây với nhiều loại trái cây miền Tây tươi ngon',
                'address' => 'Vườn Trái Cây Phong Điền, Quận Phong Điền, TP. Cần Thơ',
                'latitude' => 9.9950,
                'longitude' => 105.7960,
                'image' => 'checkin/vuon_trai_cay_phong_dien_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_trai_cay_phong_dien_can_tho_1.jpg', 'checkin/vuon_trai_cay_phong_dien_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn trái cây Phong Điền',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Tàu Du Lịch Ô Môn',
                'description' => 'Bến tàu du lịch với các tour khám phá sông nước miền Tây',
                'address' => 'Bến Tàu Du Lịch Ô Môn, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 9.9930,
                'longitude' => 105.7980,
                'image' => 'checkin/ben_tau_du_lich_o_mon_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 100000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/ben_tau_du_lich_o_mon_can_tho_1.jpg', 'checkin/ben_tau_du_lich_o_mon_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bến tàu du lịch Ô Môn',
                'transport_options' => json_encode(['car', 'motorbike', 'boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Ô Môn',
                'description' => 'Chợ truyền thống với các sản phẩm đặc sản miền Tây',
                'address' => 'Chợ Ô Môn, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 9.9910,
                'longitude' => 105.8000,
                'image' => 'checkin/cho_o_mon_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cho_o_mon_can_tho_1.jpg', 'checkin/cho_o_mon_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Chợ truyền thống Ô Môn',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Lan Ô Môn',
                'description' => 'Vườn lan với nhiều loài lan đẹp và không gian thanh lịch',
                'address' => 'Vườn Lan Ô Môn, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 9.9890,
                'longitude' => 105.8020,
                'image' => 'checkin/vuon_lan_o_mon_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_lan_o_mon_can_tho_1.jpg', 'checkin/vuon_lan_o_mon_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Vườn lan Ô Môn',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Bến Phà Ô Môn',
                'description' => 'Bến phà với view sông Hậu và không gian sông nước',
                'address' => 'Bến Phà Ô Môn, Quận Ô Môn, TP. Cần Thơ',
                'latitude' => 9.9870,
                'longitude' => 105.8040,
                'image' => 'checkin/ben_pha_o_mon_can_tho.jpg',
                'location_id' => $canThoLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '05:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/ben_pha_o_mon_can_tho_1.jpg', 'checkin/ben_pha_o_mon_can_tho_2.jpg']),
                'region' => 'Nam',
                'caption' => 'Bến phà Ô Môn',
                'transport_options' => json_encode(['car', 'motorbike', 'ferry']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
