<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CheckInPlacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('checkin_places')->insert([
            [
                'name' => 'Cầu Vàng Bà Nà Hills',
                'description' => 'Cây cầu nổi tiếng với bàn tay đá khổng lồ tại Đà Nẵng.',
                'address' => 'Bà Nà Hills, Hòa Vang, Đà Nẵng',
                'latitude' => 16.0021,
                'longitude' => 108.0655,
                'image' => 'checkin/golden_bridge.jpg',
                'location_id' => 1,
                'price' => 700000.00,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '22:00']]),
                'images' => json_encode([
                    'checkin/golden_bridge_1.jpg',
                    'checkin/golden_bridge_2.jpg',
                    'checkin/golden_bridge_3.jpg',
                    'checkin/golden_bridge_4.jpg',
                    'checkin/golden_bridge_5.jpg'
                ]),
                'region' => 'Trung',
                'caption' => 'Cầu Vàng nổi bật với kiến trúc độc đáo tại Đà Nẵng.',
                'transport_options' => json_encode(['bus', 'taxi']),
                'status' => 'active',
                'created_at' => now()->subDays(50),
                'updated_at' => now()->subDays(10),
            ],
            [
                'name' => 'Nhà Thờ Đức Bà Sài Gòn',
                'description' => 'Biểu tượng kiến trúc cổ kính giữa lòng Sài Gòn.',
                'address' => '01 Công Xã Paris, Quận 1, TP.HCM',
                'latitude' => 10.7798,
                'longitude' => 106.6992,
                'image' => 'checkin/notre_dame.jpg',
                'location_id' => 2,
                'price' => 0.00,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode([
                    'checkin/notre_dame_1.jpg',
                    'checkin/notre_dame_2.jpg'
                ]),
                'region' => 'Nam',
                'caption' => 'Kiến trúc cổ kính từ thời Pháp thuộc.',
                'transport_options' => json_encode(['bus', 'walk']),
                'status' => 'active',
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(5),
            ],
            [
                'name' => 'Vịnh Hạ Long',
                'description' => 'Di sản thiên nhiên thế giới với hàng nghìn hòn đảo đá vôi.',
                'address' => 'Hạ Long, Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'image' => 'checkin/halong_bay.jpg',
                'location_id' => 3,
                'price' => 290000.00,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode([
                    'checkin/halong_bay_1.jpg',
                    'checkin/halong_bay_2.jpg'
                ]),
                'region' => 'Bắc',
                'caption' => 'Vẻ đẹp hùng vĩ của thiên nhiên Việt Nam.',
                'transport_options' => json_encode(['bus', 'boat']),
                'status' => 'active',
                'created_at' => now()->subDays(70),
                'updated_at' => now()->subDays(20),
            ],
            [
                'name' => 'Phố Cổ Hội An',
                'description' => 'Thành phố cổ kính với những kiến trúc độc đáo, đèn lồng rực rỡ.',
                'address' => 'Phố cổ Hội An, Quảng Nam',
                'latitude' => 15.8794,
                'longitude' => 108.3361,
                'image' => 'checkin/hoi_an.jpg',
                'location_id' => 4,
                'price' => 120000.00,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '22:00']]),
                'images' => json_encode([
                    'checkin/hoi_an_1.jpg',
                    'checkin/hoi_an_2.jpg'
                ]),
                'region' => 'Trung',
                'caption' => 'Nét cổ kính và lãng mạn của Hội An.',
                'transport_options' => json_encode(['walking', 'bicycle']),
                'status' => 'active',
                'created_at' => now()->subDays(40),
                'updated_at' => now()->subDays(8),
            ],
            [
                'name' => 'Thác Bản Giốc',
                'description' => 'Thác nước hùng vĩ nằm giữa biên giới Việt - Trung.',
                'address' => 'Đàm Thủy, Trùng Khánh, Cao Bằng',
                'latitude' => 22.8661,
                'longitude' => 106.7214,
                'image' => 'checkin/ban_gioc.jpg',
                'location_id' => 2,
                'price' => 45000.00,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode([
                    'checkin/ban_gioc_1.jpg',
                    'checkin/ban_gioc_2.jpg'
                ]),
                'region' => 'Bắc',
                'caption' => 'Sức hút của ngọn thác biên giới.',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
                'created_at' => now()->subDays(60),
                'updated_at' => now()->subDays(15),
            ],
            [
                'name' => 'Phú Quốc',
                'description' => 'Đảo ngọc với những bãi biển hoang sơ và ẩm thực hải sản phong phú.',
                'address' => 'Phú Quốc, Kiên Giang',
                'latitude' => 10.2227,
                'longitude' => 103.9575,
                'image' => 'checkin/phu_quoc.jpg',
                'location_id' => 1,
                'price' => 0.00,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode([
                    'checkin/phu_quoc_1.jpg',
                    'checkin/phu_quoc_2.jpg'
                ]),
                'region' => 'Nam',
                'caption' => 'Thiên đường biển đảo phía Nam.',
                'transport_options' => json_encode(['airplane', 'taxi']),
                'status' => 'active',
                'created_at' => now()->subDays(25),
                'updated_at' => now()->subDays(3),
            ],
            [
                'name' => 'Chợ Bến Thành',
                'description' => 'Ngôi chợ lịch sử và biểu tượng văn hóa của TP.HCM.',
                'address' => 'Lê Lợi, Bến Thành, Quận 1, TP.HCM',
                'latitude' => 10.7725,
                'longitude' => 106.6980,
                'image' => 'checkin/ben_thanh.jpg',
                'location_id' => 3,
                'price' => 0.00,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode([
                    'checkin/ben_thanh_1.jpg',
                    'checkin/ben_thanh_2.jpg'
                ]),
                'region' => 'Nam',
                'caption' => 'Nơi giao thoa văn hóa và ẩm thực Sài Gòn.',
                'transport_options' => json_encode(['bus', 'walk']),
                'status' => 'active',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(1),
            ],
            [
                'name' => 'Đà Lạt - Thành phố ngàn hoa',
                'description' => 'Thành phố cao nguyên với khí hậu mát mẻ và cảnh quan thơ mộng.',
                'address' => 'Đà Lạt, Lâm Đồng',
                'latitude' => 11.9404,
                'longitude' => 108.4459,
                'image' => 'checkin/da_lat.jpg',
                'location_id' => 2,
                'price' => 0.00,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode([
                    'checkin/da_lat_1.jpg',
                    'checkin/da_lat_2.jpg'
                ]),
                'region' => 'Nam',
                'caption' => 'Điểm đến lý tưởng cho những người yêu thiên nhiên và lãng mạn.',
                'transport_options' => json_encode(['bus', 'car', 'motorbike']),
                'status' => 'active',
                'created_at' => now()->subDays(45),
                'updated_at' => now()->subDays(7),
            ],
            [
                'name' => 'Cung điện Hoàng Thành Huế',
                'description' => 'Di tích lịch sử, kinh đô của triều Nguyễn xưa.',
                'address' => 'Thành phố Huế, Thừa Thiên Huế',
                'latitude' => 16.4674,
                'longitude' => 107.5768,
                'image' => 'checkin/hue_imperial.jpg',
                'location_id' => 1,
                'price' => 150000.00,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:30']]),
                'images' => json_encode([
                    'checkin/hue_imperial_1.jpg',
                    'checkin/hue_imperial_2.jpg'
                ]),
                'region' => 'Trung',
                'caption' => 'Tìm về lịch sử và kiến trúc cổ xưa.',
                'transport_options' => json_encode(['taxi', 'cyclo']),
                'status' => 'active',
                'created_at' => now()->subDays(55),
                'updated_at' => now()->subDays(12),
            ],
            [
                'name' => 'Hang Sơn Đoòng',
                'description' => 'Hang động lớn nhất thế giới, một kỳ quan thiên nhiên ẩn mình.',
                'address' => 'Vườn Quốc gia Phong Nha – Kẻ Bàng, Quảng Bình',
                'latitude' => 17.5192,
                'longitude' => 106.2750,
                'image' => 'checkin/son_doong.jpg',
                'location_id' => 3,
                'price' => 60000000.00,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode([
                    'checkin/son_doong_1.jpg',
                    'checkin/son_doong_2.jpg'
                ]),
                'region' => 'Trung',
                'caption' => 'Cuộc phiêu lưu vào lòng đất.',
                'transport_options' => json_encode(['trekking', 'special_tour']),
                'status' => 'active',
                'created_at' => now()->subDays(90),
                'updated_at' => now()->subDays(25),
            ],
            [
                'name' => 'Mũi Né',
                'description' => 'Thiên đường của những đồi cát bay và làng chài truyền thống.',
                'address' => 'Mũi Né, Phan Thiết, Bình Thuận',
                'latitude' => 10.9632,
                'longitude' => 108.2435,
                'image' => 'checkin/mui_ne.jpg',
                'location_id' => 1,
                'price' => 0.00,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode([
                    'checkin/mui_ne_1.jpg',
                    'checkin/mui_ne_2.jpg'
                ]),
                'region' => 'Nam',
                'caption' => 'Trải nghiệm du lịch biển và cát.',
                'transport_options' => json_encode(['bus', 'car']),
                'status' => 'active',
                'created_at' => now()->subDays(35),
                'updated_at' => now()->subDays(6),
            ],
            [
                'name' => 'Sa Pa',
                'description' => 'Thị trấn mờ sương với ruộng bậc thang và văn hóa bản địa độc đáo.',
                'address' => 'Sa Pa, Lào Cai',
                'latitude' => 22.3458,
                'longitude' => 103.8407,
                'image' => 'checkin/sapa.jpg',
                'location_id' => 3,
                'price' => 0.00,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode([
                    'checkin/sapa_1.jpg',
                    'checkin/sapa_2.jpg'
                ]),
                'region' => 'Bắc',
                'caption' => 'Khám phá văn hóa vùng cao và cảnh sắc hùng vĩ.',
                'transport_options' => json_encode(['train', 'bus']),
                'status' => 'active',
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'Fansipan - Nóc nhà Đông Dương',
                'description' => 'Đỉnh núi cao nhất Việt Nam, thử thách cho những ai yêu thích leo núi.',
                'address' => 'Sơn La, Lai Châu, Lào Cai',
                'latitude' => 22.3000,
                'longitude' => 103.7800,
                'image' => 'checkin/fansipan.jpg',
                'location_id' => 2,
                'price' => 750000.00,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:30', 'close' => '17:00']]),
                'images' => json_encode([
                    'checkin/fansipan_1.jpg',
                    'checkin/fansipan_2.jpg'
                ]),
                'region' => 'Bắc',
                'caption' => 'Chinh phục đỉnh cao của Việt Nam.',
                'transport_options' => json_encode(['cable_car']),
                'status' => 'active',
                'created_at' => now()->subDays(28),
                'updated_at' => now()->subDays(4),
            ],
            [
                'name' => 'Đồng bằng sông Cửu Long',
                'description' => 'Vùng đất trù phú với hệ thống sông ngòi chằng chịt, trái cây quanh năm.',
                'address' => 'Miền Tây Nam Bộ, Việt Nam',
                'latitude' => 10.0333,
                'longitude' => 105.7700,
                'image' => 'checkin/mekong_delta.jpg',
                'location_id' => 1,
                'price' => 0.00,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode([
                    'checkin/mekong_delta_1.jpg',
                    'checkin/mekong_delta_2.jpg'
                ]),
                'region' => 'Nam',
                'caption' => 'Khám phá cuộc sống sông nước và vườn trái cây.',
                'transport_options' => json_encode(['boat', 'car']),
                'status' => 'active',
                'created_at' => now()->subDays(28),
                'updated_at' => now()->subDays(4),
            ],
        ]);
    }
}