<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaNangRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Hải Sản Biển Đông',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi ngon với view biển đẹp',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'rating' => 4.5,
                'price_range' => '200,000 - 800,000 VND',
                'image' => 'restaurants/bien_dong_seafood.jpg',
            ],
            [
                'name' => 'Nhà hàng Mì Quảng Đà Nẵng',
                'description' => 'Nhà hàng nổi tiếng với món mì Quảng truyền thống Đà Nẵng',
                'address' => '123 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/mi_quang_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Chả Cá Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bún chả cá - đặc sản Đà Nẵng',
                'address' => '45 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.4,
                'price_range' => '60,000 - 180,000 VND',
                'image' => 'restaurants/bun_cha_ca_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Cao Lầu Hội An',
                'description' => 'Nhà hàng phục vụ món cao lầu - đặc sản Hội An tại Đà Nẵng',
                'address' => '78 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/cao_lau_hoi_an.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Xèo Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh xèo với nhiều loại nhân khác nhau',
                'address' => '156 Phan Châu Trinh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '40,000 - 120,000 VND',
                'image' => 'restaurants/banh_xeo_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Huế Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bún bò Huế với nước dùng đậm đà',
                'address' => '89 Yên Bái, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.3,
                'price_range' => '70,000 - 150,000 VND',
                'image' => 'restaurants/bun_bo_hue_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Đà Nẵng',
                'description' => 'Nhà hàng phục vụ phở với nước dùng ngọt thanh và thịt tươi',
                'address' => '234 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '50,000 - 120,000 VND',
                'image' => 'restaurants/pho_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm với các món ăn kèm đa dạng',
                'address' => '67 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '60,000 - 150,000 VND',
                'image' => 'restaurants/com_tam_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh mì với nhiều loại nhân và nước sốt đặc biệt',
                'address' => '145 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '20,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Chè Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ các loại chè truyền thống và hiện đại',
                'address' => '178 Phan Châu Trinh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/che_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh bèo với nước mắm đặc biệt',
                'address' => '256 Yên Bái, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_beo_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh bột lọc với nhân tôm thịt tươi ngon',
                'address' => '89 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh nậm với lá chuối thơm',
                'address' => '134 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_nam_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Ít Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh ít với nhân đậu xanh và dừa',
                'address' => '167 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/banh_it_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bò Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh bò với hương vị đặc trưng',
                'address' => '298 Phan Châu Trinh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '10,000 - 40,000 VND',
                'image' => 'restaurants/banh_bo_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Đúc Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh đúc với nước mắm và rau sống',
                'address' => '45 Yên Bái, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_duc_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn với nhân thịt và nấm',
                'address' => '123 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '40,000 - 100,000 VND',
                'image' => 'restaurants/banh_cuon_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Khọt Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh khọt với tôm tươi và nước mắm',
                'address' => '78 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.3,
                'price_range' => '35,000 - 90,000 VND',
                'image' => 'restaurants/banh_khot_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Căn Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh căn với trứng cút và nước mắm',
                'address' => '156 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_can_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Chén Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh bèo chén với nước mắm đặc biệt',
                'address' => '234 Phan Châu Trinh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_beo_chen_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Lọc Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh lọc với nhân tôm thịt',
                'address' => '67 Yên Bái, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_loc_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Lá Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh nậm lá với nhân thịt và đậu xanh',
                'address' => '145 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_nam_la_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Trần Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh bột lọc trần với nước mắm',
                'address' => '178 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_tran_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Nậm Lọc Đà Nẵng',
                'description' => 'Nhà hàng phục vụ combo bánh bèo, nậm, lọc truyền thống',
                'address' => '256 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_beo_nam_loc_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng với nước sốt đặc biệt',
                'address' => '89 Phan Châu Trinh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh mì chả cá với chả cá tươi ngon',
                'address' => '134 Yên Bái, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '30,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì pate với pate tự làm',
                'address' => '167 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_pate_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Xíu Mại Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh mì xíu mại với nước dùng đậm đà',
                'address' => '298 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_mi_xiu_mai_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nguội Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nguội với rau sống',
                'address' => '45 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_mi_thit_nguoi_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Lụa Đà Nẵng',
                'description' => 'Nhà hàng phục vụ bánh mì chả lụa với chả lụa tự làm',
                'address' => '123 Phan Châu Trinh, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.1,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_cha_lua_danang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Xá Xíu Đà Nẵng',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt xá xíu với nước sốt đặc biệt',
                'address' => '78 Yên Bái, Quận Hải Châu, TP. Đà Nẵng',
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_xa_xiu_danang.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
