<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DaNangHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'InterContinental Danang Sun Peninsula Resort',
                'description' => 'Khu nghỉ dưỡng 5 sao cao cấp với view biển tuyệt đẹp tại bán đảo Sơn Trà',
                'address' => 'Bán đảo Sơn Trà, Quận Sơn Trà, TP. Đà Nẵng',
                'images' => json_encode(['hotels/intercontinental_danang_1.jpg', 'hotels/intercontinental_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@intercontinental-danang.com',
                'phone' => '0236 3938 888',
                'website' => 'https://www.intercontinental.com/danang',
            ],
            [
                'name' => 'Fusion Maia Danang',
                'description' => 'Resort spa all-inclusive với các villa riêng biệt và spa trị liệu',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/fusion_maia_1.jpg', 'hotels/fusion_maia_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@fusionmaia.com',
                'phone' => '0236 3967 999',
                'website' => 'https://www.fusionmaiadanang.com',
            ],
            [
                'name' => 'Hyatt Regency Danang Resort & Spa',
                'description' => 'Resort 5 sao với bãi biển riêng và spa cao cấp',
                'address' => 'Đường Trần Duy Hưng, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/hyatt_regency_1.jpg', 'hotels/hyatt_regency_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@hyattregency-danang.com',
                'phone' => '0236 3981 234',
                'website' => 'https://www.hyatt.com/danang',
            ],
            [
                'name' => 'Pullman Danang Beach Resort',
                'description' => 'Resort 5 sao với thiết kế hiện đại và dịch vụ cao cấp',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/pullman_danang_1.jpg', 'hotels/pullman_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@pullman-danang.com',
                'phone' => '0236 3958 888',
                'website' => 'https://www.pullman-danang.com',
            ],
            [
                'name' => 'Novotel Danang Premier Han River',
                'description' => 'Khách sạn 4 sao với view sông Hàn tuyệt đẹp tại trung tâm thành phố',
                'address' => '36 Bạch Đằng, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/novotel_danang_1.jpg', 'hotels/novotel_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@novotel-danang.com',
                'phone' => '0236 3922 999',
                'website' => 'https://www.novotel-danang.com',
            ],
            [
                'name' => 'Sheraton Grand Danang Resort',
                'description' => 'Resort 5 sao với bãi biển riêng và golf course',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/sheraton_danang_1.jpg', 'hotels/sheraton_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@sheraton-danang.com',
                'phone' => '0236 3988 888',
                'website' => 'https://www.sheraton-danang.com',
            ],
            [
                'name' => 'Crowne Plaza Danang',
                'description' => 'Khách sạn 4 sao với vị trí thuận tiện gần sân bay và trung tâm',
                'address' => 'Đường Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/crowne_plaza_1.jpg', 'hotels/crowne_plaza_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@crowneplaza-danang.com',
                'phone' => '0236 3925 888',
                'website' => 'https://www.crowneplaza-danang.com',
            ],
            [
                'name' => 'Furama Resort Danang',
                'description' => 'Resort 5 sao với bãi biển đẹp và dịch vụ spa cao cấp',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/furama_danang_1.jpg', 'hotels/furama_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@furama-danang.com',
                'phone' => '0236 3847 333',
                'website' => 'https://www.furama.com/danang',
            ],
            [
                'name' => 'Melia Danang Beach Resort',
                'description' => 'Resort 5 sao với thiết kế hiện đại và bãi biển riêng',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/melia_danang_1.jpg', 'hotels/melia_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@melia-danang.com',
                'phone' => '0236 3922 888',
                'website' => 'https://www.melia-danang.com',
            ],
            [
                'name' => 'Golden Bay Hotel Danang',
                'description' => 'Khách sạn 4 sao với view sông Hàn và trung tâm thành phố',
                'address' => '1 Lê Đình Dương, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/golden_bay_1.jpg', 'hotels/golden_bay_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@goldenbay-danang.com',
                'phone' => '0236 3925 999',
                'website' => 'https://www.goldenbay-danang.com',
            ],
            [
                'name' => 'A La Carte Da Nang Beach',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và bãi biển đẹp',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/alacarte_danang_1.jpg', 'hotels/alacarte_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@alacarte-danang.com',
                'phone' => '0236 3922 777',
                'website' => 'https://www.alacarte-danang.com',
            ],
            [
                'name' => 'Grand Tourane Hotel Danang',
                'description' => 'Khách sạn 4 sao với vị trí thuận tiện gần sân bay',
                'address' => '252 Võ Nguyên Giáp, Quận Sơn Trà, TP. Đà Nẵng',
                'images' => json_encode(['hotels/grand_tourane_1.jpg', 'hotels/grand_tourane_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@grandtourane-danang.com',
                'phone' => '0236 3922 666',
                'website' => 'https://www.grandtourane-danang.com',
            ],
            [
                'name' => 'Brilliant Hotel Danang',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và dịch vụ tốt',
                'address' => '162 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/brilliant_danang_1.jpg', 'hotels/brilliant_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@brilliant-danang.com',
                'phone' => '0236 3922 555',
                'website' => 'https://www.brilliant-danang.com',
            ],
            [
                'name' => 'Bamboo Green Central Hotel',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm và giá cả hợp lý',
                'address' => '158 Phan Châu Trinh, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/bamboo_green_1.jpg', 'hotels/bamboo_green_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@bamboogreen-danang.com',
                'phone' => '0236 3922 444',
                'website' => 'https://www.bamboogreen-danang.com',
            ],
            [
                'name' => 'Sanouva Danang Hotel',
                'description' => 'Khách sạn 3 sao với thiết kế đẹp và dịch vụ tốt',
                'address' => '68 Yên Bái, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/sanouva_danang_1.jpg', 'hotels/sanouva_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@sanouva-danang.com',
                'phone' => '0236 3922 333',
                'website' => 'https://www.sanouva-danang.com',
            ],
            [
                'name' => 'Stella Maris Beach Danang',
                'description' => 'Resort 4 sao với bãi biển đẹp và không gian yên tĩnh',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/stella_maris_1.jpg', 'hotels/stella_maris_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@stellamaris-danang.com',
                'phone' => '0236 3922 222',
                'website' => 'https://www.stellamaris-danang.com',
            ],
            [
                'name' => 'Ocean Villas Danang',
                'description' => 'Villa resort cao cấp với bãi biển riêng và không gian riêng tư',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/ocean_villas_1.jpg', 'hotels/ocean_villas_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@oceanvillas-danang.com',
                'phone' => '0236 3922 111',
                'website' => 'https://www.oceanvillas-danang.com',
            ],
            [
                'name' => 'Danang Golden Bay Hotel',
                'description' => 'Khách sạn 4 sao với view sông Hàn và trung tâm thành phố',
                'address' => '1 Lê Đình Dương, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/danang_golden_1.jpg', 'hotels/danang_golden_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@dananggoldenbay.com',
                'phone' => '0236 3925 000',
                'website' => 'https://www.dananggoldenbay.com',
            ],
            [
                'name' => 'Seaside Hotel Danang',
                'description' => 'Khách sạn 3 sao với view biển và giá cả hợp lý',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/seaside_danang_1.jpg', 'hotels/seaside_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@seaside-danang.com',
                'phone' => '0236 3922 000',
                'website' => 'https://www.seaside-danang.com',
            ],
            [
                'name' => 'Danang Riverside Hotel',
                'description' => 'Khách sạn 3 sao với view sông Hàn và vị trí thuận tiện',
                'address' => '18 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/riverside_danang_1.jpg', 'hotels/riverside_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@riverside-danang.com',
                'phone' => '0236 3921 999',
                'website' => 'https://www.riverside-danang.com',
            ],
            [
                'name' => 'Central Hotel Danang',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm và dịch vụ tốt',
                'address' => '123 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/central_danang_1.jpg', 'hotels/central_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@central-danang.com',
                'phone' => '0236 3921 888',
                'website' => 'https://www.central-danang.com',
            ],
            [
                'name' => 'Danang Beach Hotel',
                'description' => 'Khách sạn 3 sao với bãi biển đẹp và không gian thoáng đãng',
                'address' => 'Đường Võ Nguyên Giáp, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'images' => json_encode(['hotels/beach_danang_1.jpg', 'hotels/beach_danang_2.jpg']),
                'latitude' => 16.0583,
                'longitude' => 108.2417,
                'email' => 'reservations@beach-danang.com',
                'phone' => '0236 3921 777',
                'website' => 'https://www.beach-danang.com',
            ],
            [
                'name' => 'Danang City Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm',
                'address' => '45 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/city_danang_1.jpg', 'hotels/city_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@city-danang.com',
                'phone' => '0236 3921 666',
                'website' => 'https://www.city-danang.com',
            ],
            [
                'name' => 'Danang Garden Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => '78 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/garden_danang_1.jpg', 'hotels/garden_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@garden-danang.com',
                'phone' => '0236 3921 555',
                'website' => 'https://www.garden-danang.com',
            ],
            [
                'name' => 'Danang Palace Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng và dịch vụ cao cấp',
                'address' => '215 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/palace_danang_1.jpg', 'hotels/palace_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@palace-danang.com',
                'phone' => '0236 3921 444',
                'website' => 'https://www.palace-danang.com',
            ],
            [
                'name' => 'Danang Plaza Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện gần trung tâm mua sắm',
                'address' => '91 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/plaza_danang_1.jpg', 'hotels/plaza_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@plaza-danang.com',
                'phone' => '0236 3921 333',
                'website' => 'https://www.plaza-danang.com',
            ],
            [
                'name' => 'Danang Royal Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và dịch vụ cao cấp',
                'address' => '185 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/royal_danang_1.jpg', 'hotels/royal_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@royal-danang.com',
                'phone' => '0236 3921 222',
                'website' => 'https://www.royal-danang.com',
            ],
            [
                'name' => 'Danang Sky Hotel',
                'description' => 'Khách sạn 4 sao với view toàn cảnh thành phố từ trên cao',
                'address' => '123 Lê Duẩn, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/sky_danang_1.jpg', 'hotels/sky_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@sky-danang.com',
                'phone' => '0236 3921 111',
                'website' => 'https://www.sky-danang.com',
            ],
            [
                'name' => 'Danang Tower Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và view đẹp',
                'address' => '78 Trần Phú, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/tower_danang_1.jpg', 'hotels/tower_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@tower-danang.com',
                'phone' => '0236 3921 000',
                'website' => 'https://www.tower-danang.com',
            ],
            [
                'name' => 'Danang View Hotel',
                'description' => 'Khách sạn 3 sao với view đẹp và giá cả hợp lý',
                'address' => '45 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
                'images' => json_encode(['hotels/view_danang_1.jpg', 'hotels/view_danang_2.jpg']),
                'latitude' => 16.0544,
                'longitude' => 108.2022,
                'email' => 'reservations@view-danang.com',
                'phone' => '0236 3920 999',
                'website' => 'https://www.view-danang.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
