<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaiPhongCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        $haiPhongLocationId = DB::table('locations')->where('name', 'Hải Phòng')->value('id');
        
        if (!$haiPhongLocationId) {
            $haiPhongLocationId = DB::table('locations')->insertGetId([
                'name' => 'Hải Phòng',
                'description' => 'Thành phố Hải Phòng - thành phố cảng lớn nhất miền Bắc với văn hóa biển phong phú',
                'latitude' => 20.8449,
                'longitude' => 106.6881,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Bãi biển Đồ Sơn',
                'description' => 'Bãi biển nổi tiếng với cát trắng mịn và nước biển trong xanh',
                'address' => 'Phường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'image' => 'checkin/bai_bien_do_son.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_do_son_1.jpg', 'checkin/bai_bien_do_son_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bãi biển đẹp nhất Hải Phòng',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Núi Voi',
                'description' => 'Ngọn núi cao nhất Hải Phòng với view toàn cảnh thành phố',
                'address' => 'Xã An Lão, Huyện An Lão, TP. Hải Phòng',
                'latitude' => 20.8167,
                'longitude' => 106.5500,
                'image' => 'checkin/nui_voi.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/nui_voi_1.jpg', 'checkin/nui_voi_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đỉnh núi cao nhất Hải Phòng',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Cát Bà',
                'description' => 'Đảo lớn nhất vịnh Hạ Long với cảnh quan thiên nhiên hoang dã',
                'address' => 'Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.8000,
                'longitude' => 106.9833,
                'image' => 'checkin/dao_cat_ba.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_cat_ba_1.jpg', 'checkin/dao_cat_ba_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo ngọc vịnh Hạ Long',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Vườn Quốc Gia Cát Bà',
                'description' => 'Khu bảo tồn thiên nhiên với hệ sinh thái rừng ngập mặn độc đáo',
                'address' => 'Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/vuon_quoc_gia_cat_ba.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vuon_quoc_gia_cat_ba_1.jpg', 'checkin/vuon_quoc_gia_cat_ba_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Khu bảo tồn sinh quyển thế giới',
                'transport_options' => json_encode(['ferry', 'speedboat', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Cát Cò',
                'description' => 'Bãi biển đẹp với cát trắng và nước biển trong xanh',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/bai_bien_cat_co.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_cat_co_1.jpg', 'checkin/bai_bien_cat_co_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bãi biển hoang sơ đẹp',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đền Nghè',
                'description' => 'Di tích lịch sử văn hóa quan trọng của Hải Phòng',
                'address' => 'Phường An Biên, Quận Lê Chân, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/den_nghe.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 10000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/den_nghe_1.jpg', 'checkin/den_nghe_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Di tích lịch sử văn hóa',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Dư Hàng',
                'description' => 'Ngôi chùa cổ với kiến trúc độc đáo và lịch sử lâu đời',
                'address' => 'Phường Dư Hàng, Quận Lê Chân, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/chua_du_hang.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_du_hang_1.jpg', 'checkin/chua_du_hang_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Ngôi chùa cổ linh thiêng',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Hải Phòng',
                'description' => 'Bảo tàng trưng bày lịch sử và văn hóa của thành phố Hải Phòng',
                'address' => '65 Điện Biên Phủ, Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/bao_tang_hai_phong.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_hai_phong_1.jpg', 'checkin/bao_tang_hai_phong_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bảo tàng lịch sử thành phố',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Văn Lang',
                'description' => 'Công viên lớn với không gian xanh và các hoạt động giải trí',
                'address' => 'Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/cong_vien_van_lang.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cong_vien_van_lang_1.jpg', 'checkin/cong_vien_van_lang_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Công viên xanh mát',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Cát Bà',
                'description' => 'Bãi biển đẹp với cát trắng và nước biển trong xanh',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/bai_bien_cat_ba.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_cat_ba_1.jpg', 'checkin/bai_bien_cat_ba_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bãi biển hoang sơ',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Sáng - Hang Tối',
                'description' => 'Hệ thống hang động đẹp với thạch nhũ độc đáo',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/hang_sang_hang_toi.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/hang_sang_hang_toi_1.jpg', 'checkin/hang_sang_hang_toi_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động kỳ thú',
                'transport_options' => json_encode(['ferry', 'speedboat', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Dấu',
                'description' => 'Đảo nhỏ với cảnh quan thiên nhiên hoang dã và bãi biển đẹp',
                'address' => 'Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/dao_hon_dau.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_dau_1.jpg', 'checkin/dao_hon_dau_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo hoang sơ đẹp',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Đồ Sơn 2',
                'description' => 'Bãi biển thứ hai của Đồ Sơn với cảnh quan đẹp',
                'address' => 'Phường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'image' => 'checkin/bai_bien_do_son_2.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_do_son_2_1.jpg', 'checkin/bai_bien_do_son_2_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Bính',
                'description' => 'Cây cầu biểu tượng của Hải Phòng với kiến trúc độc đáo',
                'address' => 'Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/cau_binh.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/cau_binh_1.jpg', 'checkin/cau_binh_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cây cầu biểu tượng',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Sắt',
                'description' => 'Khu chợ truyền thống với kiến trúc Pháp cổ điển',
                'address' => 'Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/cho_sat.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cho_sat_1.jpg', 'checkin/cho_sat_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Chợ truyền thống',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Nhà hát Lớn Hải Phòng',
                'description' => 'Nhà hát với kiến trúc Pháp cổ điển và các buổi biểu diễn nghệ thuật',
                'address' => 'Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/nha_hat_lon_hai_phong.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 100000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '19:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/nha_hat_lon_hai_phong_1.jpg', 'checkin/nha_hat_lon_hai_phong_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Nhà hát nghệ thuật',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Cát Bà 2',
                'description' => 'Bãi biển thứ hai của Cát Bà với cảnh quan đẹp',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/bai_bien_cat_ba_2.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_cat_ba_2_1.jpg', 'checkin/bai_bien_cat_ba_2_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Dấu 2',
                'description' => 'Đảo nhỏ thứ hai với cảnh quan thiên nhiên hoang dã',
                'address' => 'Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/dao_hon_dau_2.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_dau_2_1.jpg', 'checkin/dao_hon_dau_2_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo hoang sơ',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Sáng - Hang Tối 2',
                'description' => 'Hệ thống hang động thứ hai với thạch nhũ độc đáo',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/hang_sang_hang_toi_2.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/hang_sang_hang_toi_2_1.jpg', 'checkin/hang_sang_hang_toi_2_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động kỳ thú',
                'transport_options' => json_encode(['ferry', 'speedboat', 'hiking']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Đồ Sơn 3',
                'description' => 'Bãi biển thứ ba của Đồ Sơn với cảnh quan đẹp',
                'address' => 'Phường Vạn Sơn, Quận Đồ Sơn, TP. Hải Phòng',
                'latitude' => 20.7167,
                'longitude' => 106.7500,
                'image' => 'checkin/bai_bien_do_son_3.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_do_son_3_1.jpg', 'checkin/bai_bien_do_son_3_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Cầu Bính 2',
                'description' => 'Cây cầu thứ hai của Hải Phòng với kiến trúc độc đáo',
                'address' => 'Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/cau_binh_2.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/cau_binh_2_1.jpg', 'checkin/cau_binh_2_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Cây cầu biểu tượng',
                'transport_options' => json_encode(['car', 'motorbike', 'walking']),
                'status' => 'active',
            ],
            [
                'name' => 'Chợ Sắt 2',
                'description' => 'Khu chợ truyền thống thứ hai với kiến trúc Pháp cổ điển',
                'address' => 'Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/cho_sat_2.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/cho_sat_2_1.jpg', 'checkin/cho_sat_2_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Chợ truyền thống',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Nhà hát Lớn Hải Phòng 2',
                'description' => 'Nhà hát thứ hai với kiến trúc Pháp cổ điển',
                'address' => 'Quận Hồng Bàng, TP. Hải Phòng',
                'latitude' => 20.8667,
                'longitude' => 106.6833,
                'image' => 'checkin/nha_hat_lon_hai_phong_2.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 100000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '19:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/nha_hat_lon_hai_phong_2_1.jpg', 'checkin/nha_hat_lon_hai_phong_2_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Nhà hát nghệ thuật',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Cát Bà 3',
                'description' => 'Bãi biển thứ ba của Cát Bà với cảnh quan đẹp',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/bai_bien_cat_ba_3.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_cat_ba_3_1.jpg', 'checkin/bai_bien_cat_ba_3_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Dấu 3',
                'description' => 'Đảo nhỏ thứ ba với cảnh quan thiên nhiên hoang dã',
                'address' => 'Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/dao_hon_dau_3.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_dau_3_1.jpg', 'checkin/dao_hon_dau_3_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo hoang sơ',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Sáng - Hang Tối 3',
                'description' => 'Hệ thống hang động thứ ba với thạch nhũ độc đáo',
                'address' => 'Đảo Cát Bà, Huyện Cát Hải, TP. Hải Phòng',
                'latitude' => 20.7833,
                'longitude' => 106.9667,
                'image' => 'checkin/hang_sang_hang_toi_3.jpg',
                'location_id' => $haiPhongLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/hang_sang_hang_toi_3_1.jpg', 'checkin/hang_sang_hang_toi_3_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động kỳ thú',
                'transport_options' => json_encode(['ferry', 'speedboat', 'hiking']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
