<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaLongRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Hải Sản Vịnh Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi ngon với view vịnh Hạ Long',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.5,
                'price_range' => '200,000 - 800,000 VND',
                'image' => 'restaurants/hai_san_vinh_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn với nhân thịt và nấm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.3,
                'price_range' => '40,000 - 100,000 VND',
                'image' => 'restaurants/banh_cuon_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Hạ Long',
                'description' => 'Nhà hàng phục vụ phở với nước dùng ngọt thanh và thịt tươi',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '50,000 - 120,000 VND',
                'image' => 'restaurants/pho_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh mì với nhiều loại nhân và nước sốt đặc biệt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '20,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Chè Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ các loại chè truyền thống và hiện đại',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/che_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh bèo với nước mắm đặc biệt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_beo_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh bột lọc với nhân tôm thịt tươi ngon',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh nậm với lá chuối thơm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_nam_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Ít Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh ít với nhân đậu xanh và dừa',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/banh_it_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bò Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh bò với hương vị đặc trưng',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '10,000 - 40,000 VND',
                'image' => 'restaurants/banh_bo_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Đúc Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh đúc với nước mắm và rau sống',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_duc_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Khọt Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh khọt với tôm tươi và nước mắm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.3,
                'price_range' => '35,000 - 90,000 VND',
                'image' => 'restaurants/banh_khot_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Căn Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh căn với trứng cút và nước mắm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_can_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Chén Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh bèo chén với nước mắm đặc biệt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_beo_chen_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Lọc Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh lọc với nhân tôm thịt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_loc_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Lá Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh nậm lá với nhân thịt và đậu xanh',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_nam_la_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Trần Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh bột lọc trần với nước mắm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_tran_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Nậm Lọc Hạ Long',
                'description' => 'Nhà hàng phục vụ combo bánh bèo, nậm, lọc truyền thống',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_beo_nam_loc_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng với nước sốt đặc biệt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh mì chả cá với chả cá tươi ngon',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '30,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì pate với pate tự làm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_pate_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Xíu Mại Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh mì xíu mại với nước dùng đậm đà',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_mi_xiu_mai_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nguội Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nguội với rau sống',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_mi_thit_nguoi_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Lụa Hạ Long',
                'description' => 'Nhà hàng phục vụ bánh mì chả lụa với chả lụa tự làm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_cha_lua_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Xá Xíu Hạ Long',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt xá xíu với nước sốt đặc biệt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_xa_xiu_ha_long.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Hạ Long 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng với nước sốt đặc biệt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_ha_long_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Hạ Long 2',
                'description' => 'Nhà hàng phục vụ bánh mì chả cá với chả cá tươi ngon',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '30,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_ha_long_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Hạ Long 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì pate với pate tự làm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_pate_ha_long_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Xíu Mại Hạ Long 2',
                'description' => 'Nhà hàng phục vụ bánh mì xíu mại với nước dùng đậm đà',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_mi_xiu_mai_ha_long_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nguội Hạ Long 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nguội với rau sống',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_mi_thit_nguoi_ha_long_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Lụa Hạ Long 2',
                'description' => 'Nhà hàng phục vụ bánh mì chả lụa với chả lụa tự làm',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.1,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_cha_lua_ha_long_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Xá Xíu Hạ Long 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt xá xíu với nước sốt đặc biệt',
                'address' => 'Đường Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_xa_xiu_ha_long_2.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
