<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaLongCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        // Kiểm tra và tạo location Hạ Long nếu chưa có
        $haLongLocationId = DB::table('locations')->where('name', 'Hạ Long')->value('id');

        if (!$haLongLocationId) {
            $haLongLocationId = DB::table('locations')->insertGetId([
                'name' => 'Hạ Long',
                'description' => 'Thành phố Hạ Long - thành phố vịnh với cảnh quan thiên nhiên kỳ vĩ và di sản thế giới',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Vịnh Hạ Long',
                'description' => 'Vịnh biển nổi tiếng với hàng nghìn đảo đá vôi và hang động kỳ vĩ',
                'address' => 'Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9101,
                'longitude' => 107.1839,
                'image' => 'checkin/vinh_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 300000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/vinh_ha_long_1.jpg', 'checkin/vinh_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Di sản thiên nhiên thế giới',
                'transport_options' => json_encode(['car', 'motorbike', 'boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Sửng Sốt',
                'description' => 'Hang động lớn nhất vịnh Hạ Long với nhũ đá đẹp mắt',
                'address' => 'Hang Sửng Sốt, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9080,
                'longitude' => 107.1850,
                'image' => 'checkin/hang_sung_sot_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_sung_sot_ha_long_1.jpg', 'checkin/hang_sung_sot_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động đẹp nhất vịnh',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Titop',
                'description' => 'Đảo đẹp với bãi biển cát trắng và view toàn cảnh vịnh',
                'address' => 'Đảo Titop, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9060,
                'longitude' => 107.1870,
                'image' => 'checkin/dao_titop_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_titop_ha_long_1.jpg', 'checkin/dao_titop_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo đẹp nhất vịnh Hạ Long',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Đầu Gỗ',
                'description' => 'Hang động với nhũ đá hình đầu gỗ và không gian rộng lớn',
                'address' => 'Hang Đầu Gỗ, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9040,
                'longitude' => 107.1890,
                'image' => 'checkin/hang_dau_go_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_dau_go_ha_long_1.jpg', 'checkin/hang_dau_go_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động nổi tiếng',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Chài Cửa Vạn',
                'description' => 'Làng chài truyền thống với văn hóa biển và nhà nổi độc đáo',
                'address' => 'Làng Chài Cửa Vạn, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9020,
                'longitude' => 107.1910,
                'image' => 'checkin/lang_chai_cua_van_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_chai_cua_van_ha_long_1.jpg', 'checkin/lang_chai_cua_van_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng chài truyền thống',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Soi Sim',
                'description' => 'Đảo nhỏ với bãi biển đẹp và không gian yên tĩnh',
                'address' => 'Đảo Soi Sim, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.9000,
                'longitude' => 107.1930,
                'image' => 'checkin/dao_soi_sim_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_soi_sim_ha_long_1.jpg', 'checkin/dao_soi_sim_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo yên tĩnh',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Trống',
                'description' => 'Hang động với âm thanh như tiếng trống và nhũ đá đẹp',
                'address' => 'Hang Trống, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8980,
                'longitude' => 107.1950,
                'image' => 'checkin/hang_trong_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_trong_ha_long_1.jpg', 'checkin/hang_trong_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động âm thanh',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Mèo Cún',
                'description' => 'Đảo nhỏ với hình dáng như mèo cún và view đẹp',
                'address' => 'Đảo Mèo Cún, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8960,
                'longitude' => 107.1970,
                'image' => 'checkin/dao_meo_cun_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_meo_cun_ha_long_1.jpg', 'checkin/dao_meo_cun_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo hình mèo cún',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Luồn',
                'description' => 'Hang động với đường hầm xuyên qua đảo và không gian độc đáo',
                'address' => 'Hang Luồn, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8940,
                'longitude' => 107.1990,
                'image' => 'checkin/hang_luon_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 45000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_luon_ha_long_1.jpg', 'checkin/hang_luon_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động xuyên đảo',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Chài Ba Hang',
                'description' => 'Làng chài với văn hóa biển và nhà nổi truyền thống',
                'address' => 'Làng Chài Ba Hang, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8920,
                'longitude' => 107.2010,
                'image' => 'checkin/lang_chai_ba_hang_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_chai_ba_hang_ha_long_1.jpg', 'checkin/lang_chai_ba_hang_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng chài Ba Hang',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Gà Chọi',
                'description' => 'Đảo với hình dáng như gà chọi và view đẹp',
                'address' => 'Đảo Hòn Gà Chọi, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8900,
                'longitude' => 107.2030,
                'image' => 'checkin/dao_hon_ga_choi_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_ga_choi_ha_long_1.jpg', 'checkin/dao_hon_ga_choi_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo hình gà chọi',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Thiên Cung',
                'description' => 'Hang động với nhũ đá đẹp như thiên cung',
                'address' => 'Hang Thiên Cung, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8880,
                'longitude' => 107.2050,
                'image' => 'checkin/hang_thien_cung_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 55000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_thien_cung_ha_long_1.jpg', 'checkin/hang_thien_cung_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động thiên cung',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Mây Rơi',
                'description' => 'Đảo với view mây rơi và không gian lãng mạn',
                'address' => 'Đảo Hòn Mây Rơi, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8860,
                'longitude' => 107.2070,
                'image' => 'checkin/dao_hon_may_roi_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_may_roi_ha_long_1.jpg', 'checkin/dao_hon_may_roi_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo mây rơi',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Bồ Nâu',
                'description' => 'Hang động với nhũ đá hình bồ nâu và không gian độc đáo',
                'address' => 'Hang Bồ Nâu, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8840,
                'longitude' => 107.2090,
                'image' => 'checkin/hang_bo_nau_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_bo_nau_ha_long_1.jpg', 'checkin/hang_bo_nau_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động bồ nâu',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Chài Vung Viêng',
                'description' => 'Làng chài với văn hóa biển và nhà nổi truyền thống',
                'address' => 'Làng Chài Vung Viêng, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8820,
                'longitude' => 107.2110,
                'image' => 'checkin/lang_chai_vung_vieng_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_chai_vung_vieng_ha_long_1.jpg', 'checkin/lang_chai_vung_vieng_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng chài Vung Viêng',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Trống Mái',
                'description' => 'Đảo với hình dáng như trống mái và view đẹp',
                'address' => 'Đảo Hòn Trống Mái, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8800,
                'longitude' => 107.2130,
                'image' => 'checkin/dao_hon_trong_mai_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_trong_mai_ha_long_1.jpg', 'checkin/dao_hon_trong_mai_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo trống mái',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Sửng Sốt 2',
                'description' => 'Hang động với nhũ đá đẹp mắt và không gian rộng lớn',
                'address' => 'Hang Sửng Sốt 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8780,
                'longitude' => 107.2150,
                'image' => 'checkin/hang_sung_sot_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 45000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_sung_sot_2_ha_long_1.jpg', 'checkin/hang_sung_sot_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động đẹp',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Titop 2',
                'description' => 'Đảo đẹp với bãi biển cát trắng và view toàn cảnh vịnh',
                'address' => 'Đảo Titop 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8760,
                'longitude' => 107.2170,
                'image' => 'checkin/dao_titop_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_titop_2_ha_long_1.jpg', 'checkin/dao_titop_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo đẹp',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Đầu Gỗ 2',
                'description' => 'Hang động với nhũ đá hình đầu gỗ và không gian rộng lớn',
                'address' => 'Hang Đầu Gỗ 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8740,
                'longitude' => 107.2190,
                'image' => 'checkin/hang_dau_go_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 35000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_dau_go_2_ha_long_1.jpg', 'checkin/hang_dau_go_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động nổi tiếng',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Chài Cửa Vạn 2',
                'description' => 'Làng chài truyền thống với văn hóa biển và nhà nổi độc đáo',
                'address' => 'Làng Chài Cửa Vạn 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8720,
                'longitude' => 107.2210,
                'image' => 'checkin/lang_chai_cua_van_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_chai_cua_van_2_ha_long_1.jpg', 'checkin/lang_chai_cua_van_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng chài truyền thống',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Soi Sim 2',
                'description' => 'Đảo nhỏ với bãi biển đẹp và không gian yên tĩnh',
                'address' => 'Đảo Soi Sim 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8700,
                'longitude' => 107.2230,
                'image' => 'checkin/dao_soi_sim_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_soi_sim_2_ha_long_1.jpg', 'checkin/dao_soi_sim_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo yên tĩnh',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Trống 2',
                'description' => 'Hang động với âm thanh như tiếng trống và nhũ đá đẹp',
                'address' => 'Hang Trống 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8680,
                'longitude' => 107.2250,
                'image' => 'checkin/hang_trong_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 30000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_trong_2_ha_long_1.jpg', 'checkin/hang_trong_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động âm thanh',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Mèo Cún 2',
                'description' => 'Đảo nhỏ với hình dáng như mèo cún và view đẹp',
                'address' => 'Đảo Mèo Cún 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8660,
                'longitude' => 107.2270,
                'image' => 'checkin/dao_meo_cun_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_meo_cun_2_ha_long_1.jpg', 'checkin/dao_meo_cun_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo hình mèo cún',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Luồn 2',
                'description' => 'Hang động với đường hầm xuyên qua đảo và không gian độc đáo',
                'address' => 'Hang Luồn 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8640,
                'longitude' => 107.2290,
                'image' => 'checkin/hang_luon_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 40000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_luon_2_ha_long_1.jpg', 'checkin/hang_luon_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động xuyên đảo',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Làng Chài Ba Hang 2',
                'description' => 'Làng chài với văn hóa biển và nhà nổi truyền thống',
                'address' => 'Làng Chài Ba Hang 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8620,
                'longitude' => 107.2310,
                'image' => 'checkin/lang_chai_ba_hang_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 20000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/lang_chai_ba_hang_2_ha_long_1.jpg', 'checkin/lang_chai_ba_hang_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Làng chài Ba Hang',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Gà Chọi 2',
                'description' => 'Đảo với hình dáng như gà chọi và view đẹp',
                'address' => 'Đảo Hòn Gà Chọi 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8600,
                'longitude' => 107.2330,
                'image' => 'checkin/dao_hon_ga_choi_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_ga_choi_2_ha_long_1.jpg', 'checkin/dao_hon_ga_choi_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo hình gà chọi',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Hang Thiên Cung 2',
                'description' => 'Hang động với nhũ đá đẹp như thiên cung',
                'address' => 'Hang Thiên Cung 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8580,
                'longitude' => 107.2350,
                'image' => 'checkin/hang_thien_cung_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 50000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '16:00']]),
                'images' => json_encode(['checkin/hang_thien_cung_2_ha_long_1.jpg', 'checkin/hang_thien_cung_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Hang động thiên cung',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Mây Rơi 2',
                'description' => 'Đảo với view mây rơi và không gian lãng mạn',
                'address' => 'Đảo Hòn Mây Rơi 2, Vịnh Hạ Long, TP. Hạ Long, Tỉnh Quảng Ninh',
                'latitude' => 20.8560,
                'longitude' => 107.2370,
                'image' => 'checkin/dao_hon_may_roi_2_ha_long.jpg',
                'location_id' => $haLongLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/dao_hon_may_roi_2_ha_long_1.jpg', 'checkin/dao_hon_may_roi_2_ha_long_2.jpg']),
                'region' => 'Bắc',
                'caption' => 'Đảo mây rơi',
                'transport_options' => json_encode(['boat']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
