<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HaNoiHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'Sofitel Legend Metropole Hanoi',
                'description' => 'Khách sạn 5 sao lịch sử với kiến trúc Pháp cổ điển tại trung tâm Hà Nội',
                'address' => '15 Ngo Quyen, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/sofitel_metropole_1.jpg', 'hotels/sofitel_metropole_2.jpg']),
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'email' => 'reservations@sofitel-legend-metropole-hanoi.com',
                'phone' => '024 3826 6919',
                'website' => 'https://www.sofitel-legend-metropole-hanoi.com',
            ],
            [
                'name' => 'InterContinental Hanoi Westlake',
                'description' => 'Khách sạn 5 sao với view Hồ Tây tuyệt đẹp',
                'address' => '5 Tu Hoa, Tay Ho, Hanoi',
                'images' => json_encode(['hotels/intercontinental_westlake_1.jpg', 'hotels/intercontinental_westlake_2.jpg']),
                'latitude' => 21.0500,
                'longitude' => 105.8167,
                'email' => 'reservations@ichanoi.com',
                'phone' => '024 6270 8888',
                'website' => 'https://www.intercontinental.com/hanoi',
            ],
            [
                'name' => 'Hilton Hanoi Opera',
                'description' => 'Khách sạn 5 sao gần Nhà hát Lớn với tiện nghi hiện đại',
                'address' => '1 Le Thanh Tong, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/hilton_opera_1.jpg', 'hotels/hilton_opera_2.jpg']),
                'latitude' => 21.0245,
                'longitude' => 105.8412,
                'email' => 'reservations@hiltonhanoi.com',
                'phone' => '024 3933 3888',
                'website' => 'https://www.hilton.com/hanoi',
            ],
            [
                'name' => 'JW Marriott Hotel Hanoi',
                'description' => 'Khách sạn 5 sao cao cấp tại khu vực Nam Từ Liêm',
                'address' => '8 Do Duc Duc, Nam Tu Liem, Hanoi',
                'images' => json_encode(['hotels/jw_marriott_1.jpg', 'hotels/jw_marriott_2.jpg']),
                'latitude' => 21.0167,
                'longitude' => 105.7833,
                'email' => 'reservations@jwmarriotthanoi.com',
                'phone' => '024 3833 5588',
                'website' => 'https://www.marriott.com/hanoi',
            ],
            [
                'name' => 'Sheraton Hanoi Hotel',
                'description' => 'Khách sạn 5 sao với view Hồ Tây và tiện nghi sang trọng',
                'address' => 'K5 Nghi Tam, 11 Xuan Dieu, Tay Ho, Hanoi',
                'images' => json_encode(['hotels/sheraton_hanoi_1.jpg', 'hotels/sheraton_hanoi_2.jpg']),
                'latitude' => 21.0500,
                'longitude' => 105.8167,
                'email' => 'reservations@sheratonhanoi.com',
                'phone' => '024 3719 9000',
                'website' => 'https://www.marriott.com/hanoi',
            ],
            [
                'name' => 'Melia Hanoi Hotel',
                'description' => 'Khách sạn 5 sao tại trung tâm thành phố với view toàn cảnh',
                'address' => '44B Ly Thuong Kiet, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/melia_hanoi_1.jpg', 'hotels/melia_hanoi_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@meliahanoi.com',
                'phone' => '024 3934 3343',
                'website' => 'https://www.melia.com/hanoi',
            ],
            [
                'name' => 'Pan Pacific Hanoi',
                'description' => 'Khách sạn 5 sao với kiến trúc hiện đại và dịch vụ cao cấp',
                'address' => '1 Thanh Nien, Ba Dinh, Hanoi',
                'images' => json_encode(['hotels/pan_pacific_1.jpg', 'hotels/pan_pacific_2.jpg']),
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'email' => 'reservations@panpacifichanoi.com',
                'phone' => '024 3823 3888',
                'website' => 'https://www.panpacific.com/hanoi',
            ],
            [
                'name' => 'Lotte Hotel Hanoi',
                'description' => 'Khách sạn 5 sao trong tòa nhà Lotte Center với view toàn cảnh',
                'address' => '54 Lieu Giai, Ba Dinh, Hanoi',
                'images' => json_encode(['hotels/lotte_hotel_1.jpg', 'hotels/lotte_hotel_2.jpg']),
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'email' => 'reservations@lottehotelhanoi.com',
                'phone' => '024 3333 1000',
                'website' => 'https://www.lottehotel.com/hanoi',
            ],
            [
                'name' => 'Grand Plaza Hanoi Hotel',
                'description' => 'Khách sạn 4 sao tại trung tâm với giá cả hợp lý',
                'address' => '117 Tran Duy Hung, Cau Giay, Hanoi',
                'images' => json_encode(['hotels/grand_plaza_1.jpg', 'hotels/grand_plaza_2.jpg']),
                'latitude' => 21.0408,
                'longitude' => 105.8000,
                'email' => 'reservations@grandplazahanoi.com',
                'phone' => '024 3784 5555',
                'website' => 'https://www.grandplazahanoi.com',
            ],
            [
                'name' => 'Fortuna Hotel Hanoi',
                'description' => 'Khách sạn 4 sao với vị trí thuận tiện gần sân bay',
                'address' => '6B Lang Ha, Ba Dinh, Hanoi',
                'images' => json_encode(['hotels/fortuna_hotel_1.jpg', 'hotels/fortuna_hotel_2.jpg']),
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'email' => 'reservations@fortunahanoi.com',
                'phone' => '024 3831 3333',
                'website' => 'https://www.fortunahanoi.com',
            ],
            [
                'name' => 'Hanoi Daewoo Hotel',
                'description' => 'Khách sạn 5 sao với kiến trúc độc đáo và dịch vụ sang trọng',
                'address' => '360 Kim Ma, Ba Dinh, Hanoi',
                'images' => json_encode(['hotels/daewoo_hotel_1.jpg', 'hotels/daewoo_hotel_2.jpg']),
                'latitude' => 21.0368,
                'longitude' => 105.8342,
                'email' => 'reservations@daewoohanoi.com',
                'phone' => '024 3831 5555',
                'website' => 'https://www.daewoohanoi.com',
            ],
            [
                'name' => 'Somerset Grand Hanoi',
                'description' => 'Khách sạn căn hộ 4 sao với tiện nghi tự nấu ăn',
                'address' => '49 Hai Ba Trung, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/somerset_grand_1.jpg', 'hotels/somerset_grand_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@somersetgrandhanoi.com',
                'phone' => '024 3934 2342',
                'website' => 'https://www.somerset.com/hanoi',
            ],
            [
                'name' => 'Hanoi Imperial Hotel',
                'description' => 'Khách sạn 4 sao với kiến trúc cổ điển tại phố cổ',
                'address' => '44 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/imperial_hotel_1.jpg', 'hotels/imperial_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@imperialhanoi.com',
                'phone' => '024 3933 3888',
                'website' => 'https://www.imperialhanoi.com',
            ],
            [
                'name' => 'Silk Path Hotel Hanoi',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và dịch vụ tốt',
                'address' => '195-197 Hang Gai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/silk_path_1.jpg', 'hotels/silk_path_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@silkpathhanoi.com',
                'phone' => '024 3936 2342',
                'website' => 'https://www.silkpathhotel.com',
            ],
            [
                'name' => 'Hanoi Pearl Hotel',
                'description' => 'Khách sạn 4 sao với view Hồ Hoàn Kiếm',
                'address' => '6 Bao Khanh, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/pearl_hotel_1.jpg', 'hotels/pearl_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoipearl.com',
                'phone' => '024 3934 2342',
                'website' => 'https://www.hanoipearl.com',
            ],
            [
                'name' => 'Golden Silk Boutique Hotel',
                'description' => 'Khách sạn boutique 3 sao với phong cách độc đáo',
                'address' => '39-41 Hang Gai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/golden_silk_1.jpg', 'hotels/golden_silk_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@goldensilkboutique.com',
                'phone' => '024 3935 2342',
                'website' => 'https://www.goldensilkboutique.com',
            ],
            [
                'name' => 'Hanoi La Siesta Hotel',
                'description' => 'Khách sạn boutique với thiết kế hiện đại và dịch vụ cá nhân',
                'address' => '94 Ma May, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/la_siesta_1.jpg', 'hotels/la_siesta_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@lasiestahanoi.com',
                'phone' => '024 3935 2342',
                'website' => 'https://www.lasiestahanoi.com',
            ],
            [
                'name' => 'Hanoi E Central Hotel',
                'description' => 'Khách sạn 3 sao với vị trí thuận tiện và giá cả hợp lý',
                'address' => '128 Tran Quang Khai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/e_central_1.jpg', 'hotels/e_central_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@ecentralhanoi.com',
                'phone' => '024 3936 2342',
                'website' => 'https://www.ecentralhanoi.com',
            ],
            [
                'name' => 'Hanoi Backpackers Hostel',
                'description' => 'Hostel dành cho du khách backpacker với không khí sôi động',
                'address' => '48 Ngo Huyen, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/backpackers_1.jpg', 'hotels/backpackers_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'info@hanoibackpackers.com',
                'phone' => '024 3828 5372',
                'website' => 'https://www.hanoibackpackers.com',
            ],
            [
                'name' => 'Hanoi Old Quarter Hotel',
                'description' => 'Khách sạn 3 sao tại phố cổ với giá cả phải chăng',
                'address' => '95 Hang Bac, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/old_quarter_1.jpg', 'hotels/old_quarter_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoiolquarter.com',
                'phone' => '024 3937 2342',
                'website' => 'https://www.hanoiolquarter.com',
            ],
            [
                'name' => 'Hanoi Garden Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => '3A Tong Dan, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/garden_hotel_1.jpg', 'hotels/garden_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoigarden.com',
                'phone' => '024 3938 2342',
                'website' => 'https://www.hanoigarden.com',
            ],
            [
                'name' => 'Hanoi View Hotel',
                'description' => 'Khách sạn 3 sao với view đẹp và tiện nghi cơ bản',
                'address' => '40 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/view_hotel_1.jpg', 'hotels/view_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoiview.com',
                'phone' => '024 3939 2342',
                'website' => 'https://www.hanoiview.com',
            ],
            [
                'name' => 'Hanoi Central Hotel',
                'description' => 'Khách sạn 3 sao tại trung tâm với dịch vụ tốt',
                'address' => '61 Hang Be, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/central_hotel_1.jpg', 'hotels/central_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoicentral.com',
                'phone' => '024 3940 2342',
                'website' => 'https://www.hanoicentral.com',
            ],
            [
                'name' => 'Hanoi Heritage Hotel',
                'description' => 'Khách sạn 4 sao với kiến trúc truyền thống',
                'address' => '95 Hang Bac, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/heritage_hotel_1.jpg', 'hotels/heritage_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoiheritage.com',
                'phone' => '024 3941 2342',
                'website' => 'https://www.hanoiheritage.com',
            ],
            [
                'name' => 'Hanoi Palace Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng',
                'address' => '108 Hang Trong, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/palace_hotel_1.jpg', 'hotels/palace_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoipalace.com',
                'phone' => '024 3942 2342',
                'website' => 'https://www.hanoipalace.com',
            ],
            [
                'name' => 'Hanoi Royal Hotel',
                'description' => 'Khách sạn 4 sao với dịch vụ hoàng gia',
                'address' => '18 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/royal_hotel_1.jpg', 'hotels/royal_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoiroyal.com',
                'phone' => '024 3943 2342',
                'website' => 'https://www.hanoiroyal.com',
            ],
            [
                'name' => 'Hanoi Luxury Hotel',
                'description' => 'Khách sạn 5 sao với tiện nghi cao cấp',
                'address' => '25 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/luxury_hotel_1.jpg', 'hotels/luxury_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoiluxury.com',
                'phone' => '024 3944 2342',
                'website' => 'https://www.hanoiluxury.com',
            ],
            [
                'name' => 'Hanoi Premium Hotel',
                'description' => 'Khách sạn 4 sao với dịch vụ premium',
                'address' => '32 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/premium_hotel_1.jpg', 'hotels/premium_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoipremium.com',
                'phone' => '024 3945 2342',
                'website' => 'https://www.hanoipremium.com',
            ],
            [
                'name' => 'Hanoi Elite Hotel',
                'description' => 'Khách sạn 4 sao dành cho giới thượng lưu',
                'address' => '39 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/elite_hotel_1.jpg', 'hotels/elite_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoielite.com',
                'phone' => '024 3946 2342',
                'website' => 'https://www.hanoielite.com',
            ],
            [
                'name' => 'Hanoi Classic Hotel',
                'description' => 'Khách sạn 3 sao với phong cách cổ điển',
                'address' => '46 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/classic_hotel_1.jpg', 'hotels/classic_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoiclassic.com',
                'phone' => '024 3947 2342',
                'website' => 'https://www.hanoiclassic.com',
            ],
            [
                'name' => 'Hanoi Modern Hotel',
                'description' => 'Khách sạn 3 sao với thiết kế hiện đại',
                'address' => '53 Hang Bai, Hoan Kiem, Hanoi',
                'images' => json_encode(['hotels/modern_hotel_1.jpg', 'hotels/modern_hotel_2.jpg']),
                'latitude' => 21.0285,
                'longitude' => 105.8542,
                'email' => 'reservations@hanoimodern.com',
                'phone' => '024 3948 2342',
                'website' => 'https://www.hanoimodern.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
