<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HCMHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'InterContinental Saigon',
                'description' => 'Khách sạn 5 sao cao cấp tại trung tâm TP.HCM với view tuyệt đẹp',
                'address' => 'Corner Hai Ba Trung St. & Le Duan Blvd, District 1, TP.HCM',
                'images' => json_encode(['hotels/intercontinental_1.jpg', 'hotels/intercontinental_2.jpg']),
                'latitude' => 10.7820,
                'longitude' => 106.7000,
                'email' => 'reservations@icsaigon.com',
                'phone' => '028 3520 9999',
                'website' => 'https://www.intercontinental.com/saigon',
            ],
            [
                'name' => 'Park Hyatt Saigon',
                'description' => 'Khách sạn sang trọng với kiến trúc Pháp cổ đẹp mắt',
                'address' => '2 Lam Son Square, District 1, TP.HCM',
                'images' => json_encode(['hotels/park_hyatt_1.jpg', 'hotels/park_hyatt_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'saigon.park@hyatt.com',
                'phone' => '028 3824 1234',
                'website' => 'https://www.hyatt.com/saigon',
            ],
            [
                'name' => 'Sheraton Saigon Hotel & Towers',
                'description' => 'Khách sạn 5 sao với view toàn cảnh thành phố',
                'address' => '88 Dong Khoi Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/sheraton_1.jpg', 'hotels/sheraton_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@sheratonsaigon.com',
                'phone' => '028 3827 2828',
                'website' => 'https://www.marriott.com/sgnsi',
            ],
            [
                'name' => 'Rex Hotel Saigon',
                'description' => 'Khách sạn lịch sử nổi tiếng với kiến trúc cổ điển',
                'address' => '141 Nguyen Hue Boulevard, District 1, TP.HCM',
                'images' => json_encode(['hotels/rex_1.jpg', 'hotels/rex_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@rexhotelsaigon.com',
                'phone' => '028 3829 2185',
                'website' => 'https://www.rexhotelsaigon.com',
            ],
            [
                'name' => 'Caravelle Saigon',
                'description' => 'Khách sạn cao cấp với view sông Sài Gòn',
                'address' => '19 Lam Son Square, District 1, TP.HCM',
                'images' => json_encode(['hotels/caravelle_1.jpg', 'hotels/caravelle_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@caravellehotel.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.caravellehotel.com',
            ],
            [
                'name' => 'Sofitel Saigon Plaza',
                'description' => 'Khách sạn 5 sao với dịch vụ spa và hồ bơi',
                'address' => '17 Le Duan Boulevard, District 1, TP.HCM',
                'images' => json_encode(['hotels/sofitel_1.jpg', 'hotels/sofitel_2.jpg']),
                'latitude' => 10.7820,
                'longitude' => 106.7000,
                'email' => 'reservations@sofitelsaigon.com',
                'phone' => '028 3824 1555',
                'website' => 'https://www.sofitel-saigon.com',
            ],
            [
                'name' => 'Grand Hotel Saigon',
                'description' => 'Khách sạn cổ điển với kiến trúc Pháp đẹp mắt',
                'address' => '8 Dong Khoi Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/grand_1.jpg', 'hotels/grand_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@grandhotelsaigon.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.grandhotelsaigon.com',
            ],
            [
                'name' => 'Majestic Saigon Hotel',
                'description' => 'Khách sạn lịch sử với view sông Sài Gòn tuyệt đẹp',
                'address' => '1 Dong Khoi Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/majestic_1.jpg', 'hotels/majestic_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@majesticsaigon.com',
                'phone' => '028 3829 5517',
                'website' => 'https://www.majesticsaigon.com',
            ],
            [
                'name' => 'Hotel Continental Saigon',
                'description' => 'Khách sạn cổ điển với lịch sử hơn 100 năm',
                'address' => '132-134 Dong Khoi Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/continental_1.jpg', 'hotels/continental_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@continentalhotel.com',
                'phone' => '028 3829 9201',
                'website' => 'https://www.continentalhotel.com',
            ],
            [
                'name' => 'Saigon Prince Hotel',
                'description' => 'Khách sạn 4 sao với vị trí thuận tiện',
                'address' => '63 Nguyen Hue Boulevard, District 1, TP.HCM',
                'images' => json_encode(['hotels/prince_1.jpg', 'hotels/prince_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@saigonprince.com',
                'phone' => '028 3828 2999',
                'website' => 'https://www.saigonprince.com',
            ],
            [
                'name' => 'Liberty Central Saigon Riverside Hotel',
                'description' => 'Khách sạn với view sông Sài Gòn đẹp mắt',
                'address' => '17 Ton Duc Thang Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/liberty_1.jpg', 'hotels/liberty_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@libertycentral.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.libertycentral.com',
            ],
            [
                'name' => 'Novotel Saigon Centre',
                'description' => 'Khách sạn hiện đại tại trung tâm thành phố',
                'address' => '167 Hai Ba Trung Street, District 3, TP.HCM',
                'images' => json_encode(['hotels/novotel_1.jpg', 'hotels/novotel_2.jpg']),
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'email' => 'reservations@novotelsaigon.com',
                'phone' => '028 3822 4866',
                'website' => 'https://www.novotel.com/saigon',
            ],
            [
                'name' => 'Pullman Saigon Centre',
                'description' => 'Khách sạn 5 sao với dịch vụ spa cao cấp',
                'address' => '148 Tran Hung Dao Boulevard, District 1, TP.HCM',
                'images' => json_encode(['hotels/pullman_1.jpg', 'hotels/pullman_2.jpg']),
                'latitude' => 10.7533,
                'longitude' => 106.6633,
                'email' => 'reservations@pullmansaigon.com',
                'phone' => '028 3838 8686',
                'website' => 'https://www.pullman-saigon.com',
            ],
            [
                'name' => 'Hotel Nikko Saigon',
                'description' => 'Khách sạn Nhật Bản với dịch vụ chuyên nghiệp',
                'address' => '235 Nguyen Van Cu Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/nikko_1.jpg', 'hotels/nikko_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@hotelnikkosaigon.com',
                'phone' => '028 3925 7777',
                'website' => 'https://www.hotelnikkosaigon.com',
            ],
            [
                'name' => 'Renaissance Riverside Hotel Saigon',
                'description' => 'Khách sạn với view sông Sài Gòn tuyệt đẹp',
                'address' => '8-15 Ton Duc Thang Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/renaissance_1.jpg', 'hotels/renaissance_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@renaissancesaigon.com',
                'phone' => '028 3822 0033',
                'website' => 'https://www.renaissance-saigon.com',
            ],
            [
                'name' => 'Hotel Equatorial Ho Chi Minh City',
                'description' => 'Khách sạn 5 sao với hồ bơi và spa',
                'address' => '242 Tran Binh Trong Street, District 5, TP.HCM',
                'images' => json_encode(['hotels/equatorial_1.jpg', 'hotels/equatorial_2.jpg']),
                'latitude' => 10.7533,
                'longitude' => 106.6633,
                'email' => 'reservations@equatorial.com',
                'phone' => '028 3839 7777',
                'website' => 'https://www.equatorial.com/saigon',
            ],
            [
                'name' => 'Saigon Hotel',
                'description' => 'Khách sạn cổ điển với kiến trúc Pháp',
                'address' => '41-47 Dong Du Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/saigon_hotel_1.jpg', 'hotels/saigon_hotel_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@saigonhotel.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.saigonhotel.com',
            ],
            [
                'name' => 'Hotel des Arts Saigon',
                'description' => 'Khách sạn nghệ thuật với thiết kế độc đáo',
                'address' => '76-78 Nguyen Thi Minh Khai Street, District 3, TP.HCM',
                'images' => json_encode(['hotels/arts_1.jpg', 'hotels/arts_2.jpg']),
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'email' => 'reservations@hoteldesarts.com',
                'phone' => '028 3989 8888',
                'website' => 'https://www.hoteldesarts.com',
            ],
            [
                'name' => 'Alagon Central Hotel & Spa',
                'description' => 'Khách sạn với spa và hồ bơi',
                'address' => '261-263 Phan Xich Long Street, Phu Nhuan District, TP.HCM',
                'images' => json_encode(['hotels/alagon_1.jpg', 'hotels/alagon_2.jpg']),
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'email' => 'info@alagonhotel.com',
                'phone' => '028 3997 9999',
                'website' => 'https://www.alagonhotel.com',
            ],
            [
                'name' => 'Silverland Central Hotel & Spa',
                'description' => 'Khách sạn với dịch vụ spa cao cấp',
                'address' => '14-16 Le Thanh Ton Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/silverland_1.jpg', 'hotels/silverland_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@silverlandhotel.com',
                'phone' => '028 3827 6688',
                'website' => 'https://www.silverlandhotel.com',
            ],
            [
                'name' => 'Hotel Continental Saigon',
                'description' => 'Khách sạn lịch sử với kiến trúc Pháp cổ',
                'address' => '132-134 Dong Khoi Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/continental_old_1.jpg', 'hotels/continental_old_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@continentalold.com',
                'phone' => '028 3829 9201',
                'website' => 'https://www.continentalold.com',
            ],
            [
                'name' => 'Saigon Centre Hotel',
                'description' => 'Khách sạn hiện đại tại trung tâm thương mại',
                'address' => '65 Le Loi Boulevard, District 1, TP.HCM',
                'images' => json_encode(['hotels/centre_1.jpg', 'hotels/centre_2.jpg']),
                'latitude' => 10.7720,
                'longitude' => 106.6983,
                'email' => 'reservations@saigoncentre.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.saigoncentre.com',
            ],
            [
                'name' => 'Hotel Majestic Saigon',
                'description' => 'Khách sạn với view sông Sài Gòn đẹp mắt',
                'address' => '1 Dong Khoi Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/majestic_new_1.jpg', 'hotels/majestic_new_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@majesticnew.com',
                'phone' => '028 3829 5517',
                'website' => 'https://www.majesticnew.com',
            ],
            [
                'name' => 'Saigon Riverside Hotel',
                'description' => 'Khách sạn với view sông Sài Gòn tuyệt đẹp',
                'address' => '18-19-20 Ton Duc Thang Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/riverside_1.jpg', 'hotels/riverside_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@saigonriverside.com',
                'phone' => '028 3822 0033',
                'website' => 'https://www.saigonriverside.com',
            ],
            [
                'name' => 'Hotel Grand Saigon',
                'description' => 'Khách sạn cao cấp với dịch vụ spa',
                'address' => '8 Dong Khoi Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/grand_new_1.jpg', 'hotels/grand_new_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'reservations@grandnew.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.grandnew.com',
            ],
            [
                'name' => 'Saigon Palace Hotel',
                'description' => 'Khách sạn với kiến trúc cổ điển đẹp mắt',
                'address' => '56-66 Nguyen Hue Boulevard, District 1, TP.HCM',
                'images' => json_encode(['hotels/palace_1.jpg', 'hotels/palace_2.jpg']),
                'latitude' => 10.7769,
                'longitude' => 106.7009,
                'email' => 'info@saigonpalace.com',
                'phone' => '028 3829 2860',
                'website' => 'https://www.saigonpalace.com',
            ],
            [
                'name' => 'Hotel Saigon Star',
                'description' => 'Khách sạn với view thành phố tuyệt đẹp',
                'address' => '204 Nguyen Thi Minh Khai Street, District 3, TP.HCM',
                'images' => json_encode(['hotels/star_1.jpg', 'hotels/star_2.jpg']),
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'email' => 'reservations@saigonstar.com',
                'phone' => '028 3930 9999',
                'website' => 'https://www.saigonstar.com',
            ],
            [
                'name' => 'Saigon Garden Hotel',
                'description' => 'Khách sạn với không gian xanh mát',
                'address' => '99 Nguyen Thi Minh Khai Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/garden_1.jpg', 'hotels/garden_2.jpg']),
                'latitude' => 10.7889,
                'longitude' => 106.6914,
                'email' => 'info@saigongarden.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.saigongarden.com',
            ],
            [
                'name' => 'Hotel Saigon Pearl',
                'description' => 'Khách sạn với dịch vụ cao cấp',
                'address' => '92A Nguyen Huu Canh Street, Binh Thanh District, TP.HCM',
                'images' => json_encode(['hotels/pearl_1.jpg', 'hotels/pearl_2.jpg']),
                'latitude' => 10.7951,
                'longitude' => 106.7219,
                'email' => 'reservations@saigonpearl.com',
                'phone' => '028 3997 8888',
                'website' => 'https://www.saigonpearl.com',
            ],
            [
                'name' => 'Saigon Diamond Hotel',
                'description' => 'Khách sạn với thiết kế hiện đại',
                'address' => '34 Le Duan Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/diamond_1.jpg', 'hotels/diamond_2.jpg']),
                'latitude' => 10.7820,
                'longitude' => 106.7000,
                'email' => 'info@saigondiamond.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.saigondiamond.com',
            ],
            [
                'name' => 'Hotel Saigon Emerald',
                'description' => 'Khách sạn với không gian sang trọng',
                'address' => '157 Pasteur Street, District 1, TP.HCM',
                'images' => json_encode(['hotels/emerald_1.jpg', 'hotels/emerald_2.jpg']),
                'latitude' => 10.7797,
                'longitude' => 106.7019,
                'email' => 'reservations@saigonemerald.com',
                'phone' => '028 3824 5555',
                'website' => 'https://www.saigonemerald.com',
            ]
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
