<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KhanhHoaRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Hải Sản Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ hải sản tươi ngon với view biển đẹp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.5,
                'price_range' => '200,000 - 800,000 VND',
                'image' => 'restaurants/hai_san_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Sứa Nha Trang',
                'description' => 'Nhà hàng nổi tiếng với món bún sứa truyền thống Nha Trang',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.4,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/bun_sua_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Căn Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh căn - đặc sản Nha Trang',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.3,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_can_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Xèo Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh xèo với nhiều loại nhân khác nhau',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '40,000 - 120,000 VND',
                'image' => 'restaurants/banh_xeo_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bún Bò Huế Nha Trang',
                'description' => 'Nhà hàng phục vụ bún bò Huế với nước dùng đậm đà',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.3,
                'price_range' => '70,000 - 150,000 VND',
                'image' => 'restaurants/bun_bo_hue_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Nha Trang',
                'description' => 'Nhà hàng phục vụ phở với nước dùng ngọt thanh và thịt tươi',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '50,000 - 120,000 VND',
                'image' => 'restaurants/pho_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm với các món ăn kèm đa dạng',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '60,000 - 150,000 VND',
                'image' => 'restaurants/com_tam_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh mì với nhiều loại nhân và nước sốt đặc biệt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '20,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Chè Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ các loại chè truyền thống và hiện đại',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/che_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh bèo với nước mắm đặc biệt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_beo_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh bột lọc với nhân tôm thịt tươi ngon',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh nậm với lá chuối thơm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_nam_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Ít Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh ít với nhân đậu xanh và dừa',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '15,000 - 50,000 VND',
                'image' => 'restaurants/banh_it_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bò Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh bò với hương vị đặc trưng',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '10,000 - 40,000 VND',
                'image' => 'restaurants/banh_bo_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Đúc Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh đúc với nước mắm và rau sống',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_duc_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Khọt Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh khọt với tôm tươi và nước mắm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.3,
                'price_range' => '35,000 - 90,000 VND',
                'image' => 'restaurants/banh_khot_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Căn Nha Trang 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh căn với trứng cút và nước mắm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_can_nha_trang_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Chén Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh bèo chén với nước mắm đặc biệt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_beo_chen_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Lọc Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh lọc với nhân tôm thịt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_loc_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Nậm Lá Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh nậm lá với nhân thịt và đậu xanh',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_nam_la_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bột Lọc Trần Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh bột lọc trần với nước mắm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_bot_loc_tran_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Bèo Nậm Lọc Nha Trang',
                'description' => 'Nhà hàng phục vụ combo bánh bèo, nậm, lọc truyền thống',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.3,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_beo_nam_loc_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng với nước sốt đặc biệt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh mì chả cá với chả cá tươi ngon',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '30,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì pate với pate tự làm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_pate_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Xíu Mại Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh mì xíu mại với nước dùng đậm đà',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_mi_xiu_mai_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nguội Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nguội với rau sống',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_mi_thit_nguoi_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Lụa Nha Trang',
                'description' => 'Nhà hàng phục vụ bánh mì chả lụa với chả lụa tự làm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_cha_lua_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Xá Xíu Nha Trang',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt xá xíu với nước sốt đặc biệt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_xa_xiu_nha_trang.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nướng Nha Trang 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nướng với nước sốt đặc biệt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_nuong_nha_trang_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Cá Nha Trang 2',
                'description' => 'Nhà hàng phục vụ bánh mì chả cá với chả cá tươi ngon',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '30,000 - 90,000 VND',
                'image' => 'restaurants/banh_mi_cha_ca_nha_trang_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Pate Nha Trang 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì pate với pate tự làm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '20,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_pate_nha_trang_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Xíu Mại Nha Trang 2',
                'description' => 'Nhà hàng phục vụ bánh mì xíu mại với nước dùng đậm đà',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 70,000 VND',
                'image' => 'restaurants/banh_mi_xiu_mai_nha_trang_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Nguội Nha Trang 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt nguội với rau sống',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.0,
                'price_range' => '20,000 - 50,000 VND',
                'image' => 'restaurants/banh_mi_thit_nguoi_nha_trang_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Chả Lụa Nha Trang 2',
                'description' => 'Nhà hàng phục vụ bánh mì chả lụa với chả lụa tự làm',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.1,
                'price_range' => '25,000 - 60,000 VND',
                'image' => 'restaurants/banh_mi_cha_lua_nha_trang_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Xá Xíu Nha Trang 2',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt xá xíu với nước sốt đặc biệt',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'rating' => 4.2,
                'price_range' => '30,000 - 80,000 VND',
                'image' => 'restaurants/banh_mi_thit_xa_xiu_nha_trang_2.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
