<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KhanhHoaCheckinPlacesSeeder extends Seeder
{
    public function run(): void
    {
        $khanhHoaLocationId = DB::table('locations')->where('name', 'Khánh Hòa')->value('id');
        
        if (!$khanhHoaLocationId) {
            $khanhHoaLocationId = DB::table('locations')->insertGetId([
                'name' => 'Khánh Hòa',
                'description' => 'Tỉnh Khánh Hòa - vùng đất với bãi biển Nha Trang nổi tiếng và văn hóa Chăm Pa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $checkinPlaces = [
            [
                'name' => 'Bãi biển Nha Trang',
                'description' => 'Bãi biển nổi tiếng với cát trắng mịn và nước biển trong xanh',
                'address' => 'Phường Lộc Thọ, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/bai_bien_nha_trang.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_nha_trang_1.jpg', 'checkin/bai_bien_nha_trang_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển đẹp nhất Việt Nam',
                'transport_options' => json_encode(['car', 'motorbike', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Tháp Bà Ponagar',
                'description' => 'Quần thể tháp Chăm cổ với kiến trúc độc đáo, di tích lịch sử quan trọng',
                'address' => 'Đường 2 Tháng 4, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2667,
                'longitude' => 109.1833,
                'image' => 'checkin/thap_ba_ponagar.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 25000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '07:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/thap_ba_ponagar_1.jpg', 'checkin/thap_ba_ponagar_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Di tích kiến trúc Chăm Pa cổ',
                'transport_options' => json_encode(['car', 'motorbike', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Tre',
                'description' => 'Đảo đẹp với bãi biển hoang sơ và cảnh quan thiên nhiên tuyệt đẹp',
                'address' => 'Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2333,
                'longitude' => 109.2000,
                'image' => 'checkin/dao_hon_tre.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_tre_1.jpg', 'checkin/dao_hon_tre_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Đảo ngọc vịnh Nha Trang',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Vinpearl Land Nha Trang',
                'description' => 'Khu vui chơi giải trí lớn với công viên nước và thủy cung',
                'address' => 'Đảo Hòn Tre, Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2333,
                'longitude' => 109.2000,
                'image' => 'checkin/vinpearl_land_nha_trang.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 800000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/vinpearl_land_nha_trang_1.jpg', 'checkin/vinpearl_land_nha_trang_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Thiên đường vui chơi giải trí',
                'transport_options' => json_encode(['ferry', 'cable_car']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Doc Let',
                'description' => 'Bãi biển hoang sơ với cát trắng mịn và nước biển trong xanh',
                'address' => 'Xã Ninh Hải, Huyện Ninh Hòa, Tỉnh Khánh Hòa',
                'latitude' => 12.5000,
                'longitude' => 109.1667,
                'image' => 'checkin/bai_bien_doc_let.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_doc_let_1.jpg', 'checkin/bai_bien_doc_let_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển hoang sơ đẹp',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Mun',
                'description' => 'Đảo với rạn san hô đẹp và là điểm lặn biển nổi tiếng',
                'address' => 'Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2000,
                'longitude' => 109.3000,
                'image' => 'checkin/dao_hon_mun.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_mun_1.jpg', 'checkin/dao_hon_mun_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Thiên đường lặn biển',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Long Sơn',
                'description' => 'Ngôi chùa cổ với tượng Phật trắng lớn và view toàn cảnh Nha Trang',
                'address' => 'Đường 23 Tháng 10, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/chua_long_son.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_long_son_1.jpg', 'checkin/chua_long_son_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Ngôi chùa linh thiêng',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Alexandre Yersin',
                'description' => 'Bảo tàng trưng bày về cuộc đời và công trình nghiên cứu của bác sĩ Yersin',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/bao_tang_alexandre_yersin.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_alexandre_yersin_1.jpg', 'checkin/bao_tang_alexandre_yersin_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bảo tàng lịch sử y học',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Yến Sào',
                'description' => 'Công viên với view biển đẹp và không gian xanh mát',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/cong_vien_yen_sao.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cong_vien_yen_sao_1.jpg', 'checkin/cong_vien_yen_sao_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Công viên xanh mát',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Nha Trang 2',
                'description' => 'Bãi biển thứ hai của Nha Trang với cảnh quan đẹp',
                'address' => 'Phường Vĩnh Hòa, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/bai_bien_nha_trang_2.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_nha_trang_2_1.jpg', 'checkin/bai_bien_nha_trang_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Tre 2',
                'description' => 'Đảo thứ hai với cảnh quan thiên nhiên hoang dã',
                'address' => 'Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2333,
                'longitude' => 109.2000,
                'image' => 'checkin/dao_hon_tre_2.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_tre_2_1.jpg', 'checkin/dao_hon_tre_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Đảo hoang sơ',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Doc Let 2',
                'description' => 'Bãi biển thứ hai của Doc Let với cảnh quan đẹp',
                'address' => 'Xã Ninh Hải, Huyện Ninh Hòa, Tỉnh Khánh Hòa',
                'latitude' => 12.5000,
                'longitude' => 109.1667,
                'image' => 'checkin/bai_bien_doc_let_2.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_doc_let_2_1.jpg', 'checkin/bai_bien_doc_let_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Mun 2',
                'description' => 'Đảo thứ hai với rạn san hô đẹp',
                'address' => 'Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2000,
                'longitude' => 109.3000,
                'image' => 'checkin/dao_hon_mun_2.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_mun_2_1.jpg', 'checkin/dao_hon_mun_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Thiên đường lặn biển',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Long Sơn 2',
                'description' => 'Ngôi chùa thứ hai với kiến trúc độc đáo',
                'address' => 'Đường 23 Tháng 10, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/chua_long_son_2.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_long_son_2_1.jpg', 'checkin/chua_long_son_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Ngôi chùa linh thiêng',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Alexandre Yersin 2',
                'description' => 'Bảo tàng thứ hai trưng bày về lịch sử y học',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/bao_tang_alexandre_yersin_2.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_alexandre_yersin_2_1.jpg', 'checkin/bao_tang_alexandre_yersin_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bảo tàng lịch sử y học',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Yến Sào 2',
                'description' => 'Công viên thứ hai với view biển đẹp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/cong_vien_yen_sao_2.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cong_vien_yen_sao_2_1.jpg', 'checkin/cong_vien_yen_sao_2_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Công viên xanh mát',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Nha Trang 3',
                'description' => 'Bãi biển thứ ba của Nha Trang với cảnh quan đẹp',
                'address' => 'Phường Vĩnh Hòa, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/bai_bien_nha_trang_3.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_nha_trang_3_1.jpg', 'checkin/bai_bien_nha_trang_3_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike', 'taxi']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Tre 3',
                'description' => 'Đảo thứ ba với cảnh quan thiên nhiên hoang dã',
                'address' => 'Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2333,
                'longitude' => 109.2000,
                'image' => 'checkin/dao_hon_tre_3.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_tre_3_1.jpg', 'checkin/dao_hon_tre_3_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Đảo hoang sơ',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Bãi biển Doc Let 3',
                'description' => 'Bãi biển thứ ba của Doc Let với cảnh quan đẹp',
                'address' => 'Xã Ninh Hải, Huyện Ninh Hòa, Tỉnh Khánh Hòa',
                'latitude' => 12.5000,
                'longitude' => 109.1667,
                'image' => 'checkin/bai_bien_doc_let_3.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/bai_bien_doc_let_3_1.jpg', 'checkin/bai_bien_doc_let_3_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bãi biển yên tĩnh',
                'transport_options' => json_encode(['car', 'motorbike']),
                'status' => 'active',
            ],
            [
                'name' => 'Đảo Hòn Mun 3',
                'description' => 'Đảo thứ ba với rạn san hô đẹp',
                'address' => 'Vịnh Nha Trang, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2000,
                'longitude' => 109.3000,
                'image' => 'checkin/dao_hon_mun_3.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '00:00', 'close' => '23:59']]),
                'images' => json_encode(['checkin/dao_hon_mun_3_1.jpg', 'checkin/dao_hon_mun_3_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Thiên đường lặn biển',
                'transport_options' => json_encode(['ferry', 'speedboat']),
                'status' => 'active',
            ],
            [
                'name' => 'Chùa Long Sơn 3',
                'description' => 'Ngôi chùa thứ ba với kiến trúc độc đáo',
                'address' => 'Đường 23 Tháng 10, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/chua_long_son_3.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '18:00']]),
                'images' => json_encode(['checkin/chua_long_son_3_1.jpg', 'checkin/chua_long_son_3_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Ngôi chùa linh thiêng',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Bảo tàng Alexandre Yersin 3',
                'description' => 'Bảo tàng thứ ba trưng bày về lịch sử y học',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/bao_tang_alexandre_yersin_3.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 15000,
                'is_free' => false,
                'operating_hours' => json_encode([['open' => '08:00', 'close' => '17:00']]),
                'images' => json_encode(['checkin/bao_tang_alexandre_yersin_3_1.jpg', 'checkin/bao_tang_alexandre_yersin_3_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Bảo tàng lịch sử y học',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
            [
                'name' => 'Công viên Yến Sào 3',
                'description' => 'Công viên thứ ba với view biển đẹp',
                'address' => 'Đường Trần Phú, TP. Nha Trang, Tỉnh Khánh Hòa',
                'latitude' => 12.2500,
                'longitude' => 109.0000,
                'image' => 'checkin/cong_vien_yen_sao_3.jpg',
                'location_id' => $khanhHoaLocationId,
                'price' => 0,
                'is_free' => true,
                'operating_hours' => json_encode([['open' => '06:00', 'close' => '22:00']]),
                'images' => json_encode(['checkin/cong_vien_yen_sao_3_1.jpg', 'checkin/cong_vien_yen_sao_3_2.jpg']),
                'region' => 'Nam Trung Bộ',
                'caption' => 'Công viên xanh mát',
                'transport_options' => json_encode(['walking', 'taxi', 'bus']),
                'status' => 'active',
            ],
        ];

        foreach ($checkinPlaces as $place) {
            $place['created_at'] = now();
            $place['updated_at'] = now();
            DB::table('checkin_places')->insert($place);
        }
    }
}
