<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SaPaRestaurantsSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Nhà hàng Thắng Cố Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ thắng cố và các món ăn đặc sản dân tộc',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'rating' => 4.5,
                'price_range' => '100,000 - 300,000 VND',
                'image' => 'restaurants/thang_co_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Lam Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ cơm lam và các món ăn đặc sản núi',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3340,
                'longitude' => 103.8460,
                'rating' => 4.3,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/com_lam_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Gà Đen Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu gà đen và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3320,
                'longitude' => 103.8480,
                'rating' => 4.4,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/lau_ga_den_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Hồi Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ cá hồi và các món ăn đặc sản núi',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3300,
                'longitude' => 103.8500,
                'rating' => 4.5,
                'price_range' => '150,000 - 400,000 VND',
                'image' => 'restaurants/ca_hoi_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3280,
                'longitude' => 103.8520,
                'rating' => 4.2,
                'price_range' => '50,000 - 150,000 VND',
                'image' => 'restaurants/banh_cuon_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Thịt Lợn Cắp Nách Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ thịt lợn cắp nách và các món ăn đặc sản dân tộc',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3260,
                'longitude' => 103.8540,
                'rating' => 4.4,
                'price_range' => '120,000 - 300,000 VND',
                'image' => 'restaurants/thit_lon_cap_nach_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Cá Tầm Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu cá tầm và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3240,
                'longitude' => 103.8560,
                'rating' => 4.5,
                'price_range' => '250,000 - 600,000 VND',
                'image' => 'restaurants/lau_ca_tam_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Dày Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh dày và các món ăn đặc sản dân tộc',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3220,
                'longitude' => 103.8580,
                'rating' => 4.3,
                'price_range' => '30,000 - 100,000 VND',
                'image' => 'restaurants/banh_day_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Gà Đen Nướng Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ gà đen nướng và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3200,
                'longitude' => 103.8600,
                'rating' => 4.4,
                'price_range' => '180,000 - 400,000 VND',
                'image' => 'restaurants/ga_den_nuong_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3180,
                'longitude' => 103.8620,
                'rating' => 4.2,
                'price_range' => '80,000 - 200,000 VND',
                'image' => 'restaurants/com_tam_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Bò Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu bò và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3160,
                'longitude' => 103.8640,
                'rating' => 4.3,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/lau_bo_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3140,
                'longitude' => 103.8660,
                'rating' => 4.1,
                'price_range' => '40,000 - 120,000 VND',
                'image' => 'restaurants/banh_mi_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Hồi Nướng Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ cá hồi nướng và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3120,
                'longitude' => 103.8680,
                'rating' => 4.5,
                'price_range' => '200,000 - 500,000 VND',
                'image' => 'restaurants/ca_hoi_nuong_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ phở và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3100,
                'longitude' => 103.8700,
                'rating' => 4.2,
                'price_range' => '60,000 - 150,000 VND',
                'image' => 'restaurants/pho_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Gà Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu gà và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3080,
                'longitude' => 103.8720,
                'rating' => 4.3,
                'price_range' => '180,000 - 400,000 VND',
                'image' => 'restaurants/lau_ga_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Nóng Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn nóng và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3060,
                'longitude' => 103.8740,
                'rating' => 4.4,
                'price_range' => '70,000 - 180,000 VND',
                'image' => 'restaurants/banh_cuon_nong_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Thịt Lợn Nướng Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ thịt lợn nướng và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3040,
                'longitude' => 103.8760,
                'rating' => 4.3,
                'price_range' => '150,000 - 350,000 VND',
                'image' => 'restaurants/thit_lon_nuong_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Cá Hồi Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu cá hồi và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3020,
                'longitude' => 103.8780,
                'rating' => 4.5,
                'price_range' => '300,000 - 700,000 VND',
                'image' => 'restaurants/lau_ca_hoi_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Dày Nướng Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh dày nướng và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.3000,
                'longitude' => 103.8800,
                'rating' => 4.2,
                'price_range' => '50,000 - 120,000 VND',
                'image' => 'restaurants/banh_day_nuong_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Gà Đen Hấp Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ gà đen hấp và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2980,
                'longitude' => 103.8820,
                'rating' => 4.4,
                'price_range' => '200,000 - 450,000 VND',
                'image' => 'restaurants/ga_den_hap_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Sườn Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm sườn và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2960,
                'longitude' => 103.8840,
                'rating' => 4.3,
                'price_range' => '100,000 - 250,000 VND',
                'image' => 'restaurants/com_tam_suon_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Bò Tái Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu bò tái và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2940,
                'longitude' => 103.8860,
                'rating' => 4.4,
                'price_range' => '250,000 - 550,000 VND',
                'image' => 'restaurants/lau_bo_tai_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Mì Thịt Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh mì thịt và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2920,
                'longitude' => 103.8880,
                'rating' => 4.2,
                'price_range' => '60,000 - 150,000 VND',
                'image' => 'restaurants/banh_mi_thit_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Cá Hồi Chiên Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ cá hồi chiên và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2900,
                'longitude' => 103.8900,
                'rating' => 4.5,
                'price_range' => '180,000 - 450,000 VND',
                'image' => 'restaurants/ca_hoi_chien_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Phở Bò Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ phở bò và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2880,
                'longitude' => 103.8920,
                'rating' => 4.3,
                'price_range' => '80,000 - 180,000 VND',
                'image' => 'restaurants/pho_bo_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Gà Đen Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu gà đen và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2860,
                'longitude' => 103.8940,
                'rating' => 4.4,
                'price_range' => '220,000 - 500,000 VND',
                'image' => 'restaurants/lau_ga_den_sapa_2.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Cuốn Hải Sản Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh cuốn hải sản và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2840,
                'longitude' => 103.8960,
                'rating' => 4.3,
                'price_range' => '90,000 - 220,000 VND',
                'image' => 'restaurants/banh_cuon_hai_san_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Thịt Lợn Hấp Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ thịt lợn hấp và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2820,
                'longitude' => 103.8980,
                'rating' => 4.4,
                'price_range' => '160,000 - 380,000 VND',
                'image' => 'restaurants/thit_lon_hap_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Lẩu Cá Tầm Nướng Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ lẩu cá tầm nướng và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2800,
                'longitude' => 103.9000,
                'rating' => 4.5,
                'price_range' => '280,000 - 650,000 VND',
                'image' => 'restaurants/lau_ca_tam_nuong_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Bánh Dày Thịt Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ bánh dày thịt và các món ăn đặc sản',
                'address' => 'Đường Nguyễn Huệ, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2780,
                'longitude' => 103.9020,
                'rating' => 4.2,
                'price_range' => '70,000 - 150,000 VND',
                'image' => 'restaurants/banh_day_thit_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Gà Đen Chiên Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ gà đen chiên và các món ăn đặc sản',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2760,
                'longitude' => 103.9040,
                'rating' => 4.4,
                'price_range' => '190,000 - 420,000 VND',
                'image' => 'restaurants/ga_den_chien_sapa.jpg',
            ],
            [
                'name' => 'Nhà hàng Cơm Tấm Chả Sa Pa',
                'description' => 'Nhà hàng chuyên phục vụ cơm tấm chả và các món ăn đặc sản',
                'address' => 'Đường Cầu Mây, Thị xã Sa Pa, Tỉnh Lào Cai',
                'latitude' => 22.2740,
                'longitude' => 103.9060,
                'rating' => 4.3,
                'price_range' => '110,000 - 270,000 VND',
                'image' => 'restaurants/com_tam_cha_sapa.jpg',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();
            DB::table('restaurants')->insert($restaurant);
        }
    }
}
