<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SaPaHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'Victoria Sapa Resort & Spa',
                'description' => 'Resort 4 sao cao cấp với view núi Fansipan tuyệt đẹp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/victoria_sapa_1.jpg', 'hotels/victoria_sapa_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@victoria-sapa.com',
                'phone' => '0214 3871 522',
                'website' => 'https://www.victoriahotels.asia/sapa',
            ],
            [
                'name' => 'Topas Ecolodge',
                'description' => 'Resort sinh thái 4 sao với view thung lũng Mường Hoa',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/topas_ecolodge_1.jpg', 'hotels/topas_ecolodge_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@topas-ecolodge.com',
                'phone' => '0214 3871 444',
                'website' => 'https://www.topasecolodge.com',
            ],
            [
                'name' => 'Sapa Jade Hill Resort',
                'description' => 'Resort 4 sao với view núi và thung lũng đẹp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_jade_hill_1.jpg', 'hotels/sapa_jade_hill_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-jade-hill.com',
                'phone' => '0214 3871 333',
                'website' => 'https://www.sapa-jade-hill.com',
            ],
            [
                'name' => 'Sapa Highland Resort',
                'description' => 'Resort 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_highland_1.jpg', 'hotels/sapa_highland_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-highland.com',
                'phone' => '0214 3871 222',
                'website' => 'https://www.sapa-highland.com',
            ],
            [
                'name' => 'Sapa Central Hotel',
                'description' => 'Khách sạn 3 sao với vị trí trung tâm thuận tiện',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_central_1.jpg', 'hotels/sapa_central_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-central.com',
                'phone' => '0214 3871 111',
                'website' => 'https://www.sapa-central.com',
            ],
            [
                'name' => 'Sapa Mountain View Hotel',
                'description' => 'Khách sạn 3 sao với view núi đẹp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_mountain_view_1.jpg', 'hotels/sapa_mountain_view_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-mountain-view.com',
                'phone' => '0214 3871 000',
                'website' => 'https://www.sapa-mountain-view.com',
            ],
            [
                'name' => 'Sapa Garden Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_garden_1.jpg', 'hotels/sapa_garden_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-garden.com',
                'phone' => '0214 3870 999',
                'website' => 'https://www.sapa-garden.com',
            ],
            [
                'name' => 'Sapa Valley Resort',
                'description' => 'Resort 4 sao với view thung lũng đẹp',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_valley_1.jpg', 'hotels/sapa_valley_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-valley.com',
                'phone' => '0214 3870 888',
                'website' => 'https://www.sapa-valley.com',
            ],
            [
                'name' => 'Sapa Royal Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và dịch vụ cao cấp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_royal_1.jpg', 'hotels/sapa_royal_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-royal.com',
                'phone' => '0214 3870 777',
                'website' => 'https://www.sapa-royal.com',
            ],
            [
                'name' => 'Sapa Sky Hotel',
                'description' => 'Khách sạn 4 sao với view toàn cảnh từ trên cao',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_sky_1.jpg', 'hotels/sapa_sky_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-sky.com',
                'phone' => '0214 3870 666',
                'website' => 'https://www.sapa-sky.com',
            ],
            [
                'name' => 'Sapa Tower Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và view đẹp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_tower_1.jpg', 'hotels/sapa_tower_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-tower.com',
                'phone' => '0214 3870 555',
                'website' => 'https://www.sapa-tower.com',
            ],
            [
                'name' => 'Sapa View Hotel',
                'description' => 'Khách sạn 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_view_1.jpg', 'hotels/sapa_view_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-view.com',
                'phone' => '0214 3870 444',
                'website' => 'https://www.sapa-view.com',
            ],
            [
                'name' => 'Sapa Central Plaza Hotel',
                'description' => 'Khách sạn 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_central_plaza_1.jpg', 'hotels/sapa_central_plaza_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-central-plaza.com',
                'phone' => '0214 3870 333',
                'website' => 'https://www.sapa-central-plaza.com',
            ],
            [
                'name' => 'Sapa Mountain Palace',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng và view núi đẹp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_mountain_palace_1.jpg', 'hotels/sapa_mountain_palace_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-mountain-palace.com',
                'phone' => '0214 3870 222',
                'website' => 'https://www.sapa-mountain-palace.com',
            ],
            [
                'name' => 'Sapa Golden Hotel',
                'description' => 'Khách sạn 3 sao với dịch vụ tốt và giá cả hợp lý',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_golden_1.jpg', 'hotels/sapa_golden_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-golden.com',
                'phone' => '0214 3870 111',
                'website' => 'https://www.sapa-golden.com',
            ],
            [
                'name' => 'Sapa Pearl Resort',
                'description' => 'Resort 4 sao với view núi và dịch vụ cao cấp',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_pearl_1.jpg', 'hotels/sapa_pearl_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-pearl.com',
                'phone' => '0214 3870 000',
                'website' => 'https://www.sapa-pearl.com',
            ],
            [
                'name' => 'Sapa Diamond Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế hiện đại và dịch vụ cao cấp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_diamond_1.jpg', 'hotels/sapa_diamond_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-diamond.com',
                'phone' => '0214 3869 999',
                'website' => 'https://www.sapa-diamond.com',
            ],
            [
                'name' => 'Sapa Ocean Resort',
                'description' => 'Resort 3 sao với view núi và không gian thoáng đãng',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_ocean_1.jpg', 'hotels/sapa_ocean_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-ocean.com',
                'phone' => '0214 3869 888',
                'website' => 'https://www.sapa-ocean.com',
            ],
            [
                'name' => 'Sapa Emerald Hotel',
                'description' => 'Khách sạn 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_emerald_1.jpg', 'hotels/sapa_emerald_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-emerald.com',
                'phone' => '0214 3869 777',
                'website' => 'https://www.sapa-emerald.com',
            ],
            [
                'name' => 'Sapa Crystal Resort',
                'description' => 'Resort 3 sao với view núi trong xanh như pha lê',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_crystal_1.jpg', 'hotels/sapa_crystal_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-crystal.com',
                'phone' => '0214 3869 666',
                'website' => 'https://www.sapa-crystal.com',
            ],
            [
                'name' => 'Sapa Sapphire Hotel',
                'description' => 'Khách sạn 4 sao với thiết kế sang trọng như ngọc bích',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_sapphire_1.jpg', 'hotels/sapa_sapphire_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-sapphire.com',
                'phone' => '0214 3869 555',
                'website' => 'https://www.sapa-sapphire.com',
            ],
            [
                'name' => 'Sapa Ruby Resort',
                'description' => 'Resort 4 sao với thiết kế sang trọng như ngọc ruby',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_ruby_1.jpg', 'hotels/sapa_ruby_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-ruby.com',
                'phone' => '0214 3869 444',
                'website' => 'https://www.sapa-ruby.com',
            ],
            [
                'name' => 'Sapa Highland Palace',
                'description' => 'Khách sạn 4 sao với thiết kế hoàng gia và view núi đẹp',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_highland_palace_1.jpg', 'hotels/sapa_highland_palace_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-highland-palace.com',
                'phone' => '0214 3869 333',
                'website' => 'https://www.sapa-highland-palace.com',
            ],
            [
                'name' => 'Sapa Valley Palace',
                'description' => 'Resort 4 sao với thiết kế sang trọng và view thung lũng đẹp',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_valley_palace_1.jpg', 'hotels/sapa_valley_palace_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-valley-palace.com',
                'phone' => '0214 3869 222',
                'website' => 'https://www.sapa-valley-palace.com',
            ],
            [
                'name' => 'Sapa Mountain View Resort',
                'description' => 'Resort 3 sao với view núi đẹp và không gian thoáng đãng',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_mountain_view_resort_1.jpg', 'hotels/sapa_mountain_view_resort_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-mountain-view-resort.com',
                'phone' => '0214 3869 111',
                'website' => 'https://www.sapa-mountain-view-resort.com',
            ],
            [
                'name' => 'Sapa Garden Resort',
                'description' => 'Resort 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_garden_resort_1.jpg', 'hotels/sapa_garden_resort_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-garden-resort.com',
                'phone' => '0214 3869 000',
                'website' => 'https://www.sapa-garden-resort.com',
            ],
            [
                'name' => 'Sapa Sky Resort',
                'description' => 'Resort 4 sao với view toàn cảnh từ trên cao',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_sky_resort_1.jpg', 'hotels/sapa_sky_resort_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-sky-resort.com',
                'phone' => '0214 3868 999',
                'website' => 'https://www.sapa-sky-resort.com',
            ],
            [
                'name' => 'Sapa Tower Resort',
                'description' => 'Resort 4 sao với thiết kế hiện đại và view đẹp',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_tower_resort_1.jpg', 'hotels/sapa_tower_resort_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-tower-resort.com',
                'phone' => '0214 3868 888',
                'website' => 'https://www.sapa-tower-resort.com',
            ],
            [
                'name' => 'Sapa View Resort',
                'description' => 'Resort 3 sao với view đẹp và giá cả hợp lý',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_view_resort_1.jpg', 'hotels/sapa_view_resort_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-view-resort.com',
                'phone' => '0214 3868 777',
                'website' => 'https://www.sapa-view-resort.com',
            ],
            [
                'name' => 'Sapa Central Resort',
                'description' => 'Resort 4 sao với vị trí trung tâm và dịch vụ cao cấp',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_central_resort_1.jpg', 'hotels/sapa_central_resort_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-central-resort.com',
                'phone' => '0214 3868 666',
                'website' => 'https://www.sapa-central-resort.com',
            ],
            [
                'name' => 'Sapa Highland Resort 2',
                'description' => 'Resort 3 sao với không gian xanh và yên tĩnh',
                'address' => 'Đường Fansipan, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_highland_2_1.jpg', 'hotels/sapa_highland_2_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-highland-2.com',
                'phone' => '0214 3868 555',
                'website' => 'https://www.sapa-highland-2.com',
            ],
            [
                'name' => 'Sapa Valley Resort 2',
                'description' => 'Resort 4 sao với view thung lũng đẹp',
                'address' => 'Thung lũng Mường Hoa, Thị xã Sa Pa, Tỉnh Lào Cai',
                'images' => json_encode(['hotels/sapa_valley_2_1.jpg', 'hotels/sapa_valley_2_2.jpg']),
                'latitude' => 22.3361,
                'longitude' => 103.8444,
                'email' => 'reservations@sapa-valley-2.com',
                'phone' => '0214 3868 444',
                'website' => 'https://www.sapa-valley-2.com',
            ],
        ];

        foreach ($hotels as $hotel) {
            $hotel['created_at'] = now();
            $hotel['updated_at'] = now();
            DB::table('hotels')->insert($hotel);
        }
    }
}
